USE petmedicalcare;
GO

-- En SQL Server borramos en orden estricto: Hijos -> Padres

-- 1. Eliminar tablas con dependencias (Hijos)
DROP TABLE IF EXISTS dbo.DETALLES_DOCUMENTO_DE_PAGO;
DROP TABLE IF EXISTS dbo.DETALLES_RECETA;
DROP TABLE IF EXISTS dbo.DETALLES_SERVICIO;
DROP TABLE IF EXISTS dbo.HORARIOS_LABORALES;
DROP TABLE IF EXISTS dbo.RECETAS_MEDICAS;
DROP TABLE IF EXISTS dbo.DOCUMENTOS_DE_PAGO;
DROP TABLE IF EXISTS dbo.CITAS_ATENCION;

-- 2. Eliminar tablas intermedias
DROP TABLE IF EXISTS dbo.PRODUCTOS;
DROP TABLE IF EXISTS dbo.SERVICIOS;
DROP TABLE IF EXISTS dbo.TIPOS_PRODUCTO;
DROP TABLE IF EXISTS dbo.TIPOS_SERVICIO;
DROP TABLE IF EXISTS dbo.MASCOTAS;
DROP TABLE IF EXISTS dbo.VETERINARIOS;
DROP TABLE IF EXISTS dbo.ROLES_USUARIO;

-- 3. Eliminar tablas base (Padres)
DROP TABLE IF EXISTS dbo.PERSONAS;
DROP TABLE IF EXISTS dbo.ROLES;
DROP TABLE IF EXISTS dbo.METODOS_DE_PAGO;
DROP TABLE IF EXISTS dbo.USUARIOS;
GO