USE petmedicalcare;
GO

-- ==========================================
-- 1. TABLAS MAESTRAS
-- ==========================================

-- Tabla: USUARIOS
CREATE TABLE dbo.USUARIOS (
  USUARIO_ID INT IDENTITY(1,1) NOT NULL,
  USERNAME VARCHAR(50) NOT NULL, 
  PASSWORD VARCHAR(255) NOT NULL,
  CORREO VARCHAR(150) NULL,      
  ACTIVO BIT NULL,
  USUARIO_CREADOR VARCHAR(50) NULL,
  FECHA_CREACION DATETIME NULL,
  USUARIO_MODIFICADOR VARCHAR(50) NULL,
  FECHA_MODIFICACION DATETIME NULL,
  PRIMARY KEY (USUARIO_ID)
);

-- Tabla: METODOS_DE_PAGO
CREATE TABLE dbo.METODOS_DE_PAGO (
  METODO_DE_PAGO_ID INT IDENTITY(1,1) NOT NULL,
  NOMBRE VARCHAR(60) NOT NULL,
  ACTIVO BIT NULL,
  PRIMARY KEY (METODO_DE_PAGO_ID)
);

-- Tabla: ROLES
CREATE TABLE dbo.ROLES (
  ROL_ID INT IDENTITY(1,1) NOT NULL,
  NOMBRE VARCHAR(50) NOT NULL,
  ACTIVO BIT NULL,
  PRIMARY KEY (ROL_ID)
);

-- Tabla: TIPOS_PRODUCTO
CREATE TABLE dbo.TIPOS_PRODUCTO (
  TIPO_PRODUCTO_ID INT IDENTITY(1,1) NOT NULL,
  NOMBRE VARCHAR(80) NOT NULL,
  DESCRIPCION VARCHAR(200) NULL,
  ACTIVO BIT NULL,
  PRIMARY KEY (TIPO_PRODUCTO_ID)
);

-- Tabla: TIPOS_SERVICIO
CREATE TABLE dbo.TIPOS_SERVICIO (
  TIPO_SERVICIO_ID INT IDENTITY(1,1) NOT NULL,
  NOMBRE VARCHAR(80) NOT NULL,
  DESCRIPCION VARCHAR(200) NULL,
  ACTIVO BIT NULL,
  PRIMARY KEY (TIPO_SERVICIO_ID)
);
GO

-- ==========================================
-- 2. TABLAS INTERMEDIAS
-- ==========================================

-- Tabla: PERSONAS
CREATE TABLE dbo.PERSONAS (
  PERSONA_ID INT IDENTITY(1,1) NOT NULL,
  USUARIO_ID INT NOT NULL,
  NOMBRE VARCHAR(120) NOT NULL,
  DIRECCION VARCHAR(200) NULL,
  TELEFONO VARCHAR(20) NULL,
  SEXO CHAR(1) NULL,
  NRO_DOCUMENTO VARCHAR(20) NULL,
  RUC VARCHAR(11) NULL,
  TIPO_DOCUMENTO VARCHAR(60) NULL,
  ACTIVO BIT NULL,
  PRIMARY KEY (PERSONA_ID),
  CONSTRAINT fk_PERSONAS_USUARIOS1 FOREIGN KEY (USUARIO_ID) 
    REFERENCES dbo.USUARIOS (USUARIO_ID) ON UPDATE CASCADE
);

-- Tabla: ROLES_USUARIO
CREATE TABLE dbo.ROLES_USUARIO (
  ROL_USUARIO_ID INT IDENTITY(1,1) NOT NULL,
  ROL_ID INT NOT NULL,
  USUARIO_ID INT NOT NULL,
  ACTIVO BIT NULL,
  PRIMARY KEY (ROL_USUARIO_ID),
  CONSTRAINT uq_roles_usuario UNIQUE (ROL_ID, USUARIO_ID),
  CONSTRAINT fk_ROLES_USUARIO_ROLES FOREIGN KEY (ROL_ID) REFERENCES dbo.ROLES (ROL_ID) ON UPDATE CASCADE,
  CONSTRAINT fk_ROLES_USUARIO_USUARIOS1 FOREIGN KEY (USUARIO_ID) REFERENCES dbo.USUARIOS (USUARIO_ID) ON UPDATE CASCADE
);

-- Tabla: PRODUCTOS
CREATE TABLE dbo.PRODUCTOS (
  PRODUCTO_ID INT IDENTITY(1,1) NOT NULL,
  TIPO_PRODUCTO_ID INT NOT NULL,
  NOMBRE VARCHAR(120) NOT NULL,
  PRESENTACION VARCHAR(120) NULL,
  PRECIO_UNITARIO DECIMAL(10,2) NULL,
  STOCK INT NULL,
  ACTIVO BIT NULL,
  USUARIO_CREADOR VARCHAR(50) NULL,
  FECHA_CREACION DATETIME NULL,
  USUARIO_MODIFICADOR VARCHAR(50) NULL,
  FECHA_MODIFICACION DATETIME NULL,
  PRIMARY KEY (PRODUCTO_ID),
  CONSTRAINT fk_PRODUCTOS_TIPOS_PRODUCTO1 FOREIGN KEY (TIPO_PRODUCTO_ID) 
    REFERENCES dbo.TIPOS_PRODUCTO (TIPO_PRODUCTO_ID) ON UPDATE CASCADE
);

-- Tabla: SERVICIOS
CREATE TABLE dbo.SERVICIOS (
  SERVICIO_ID INT IDENTITY(1,1) NOT NULL,
  TIPO_SERVICIO_ID INT NOT NULL,
  NOMBRE VARCHAR(100) NOT NULL,
  DESCRIPCION VARCHAR(200) NULL,
  COSTO DECIMAL(10,2) NULL,
  ESTADO VARCHAR(20) NULL,
  ACTIVO BIT NULL,
  USUARIO_CREADOR VARCHAR(50) NULL,
  FECHA_CREACION DATETIME NULL,
  USUARIO_MODIFICADOR VARCHAR(50) NULL,
  FECHA_MODIFICACION DATETIME NULL,
  PRIMARY KEY (SERVICIO_ID),
  CONSTRAINT fk_SERVICIOS_TIPOS_SERVICIO1 FOREIGN KEY (TIPO_SERVICIO_ID) 
    REFERENCES dbo.TIPOS_SERVICIO (TIPO_SERVICIO_ID) ON UPDATE CASCADE
);
GO

-- ==========================================
-- 3. TABLAS DE NEGOCIO
-- ==========================================

-- Tabla: MASCOTAS
CREATE TABLE dbo.MASCOTAS (
  MASCOTA_ID INT IDENTITY(1,1) NOT NULL,
  PERSONA_ID INT NOT NULL,
  NOMBRE VARCHAR(80) NOT NULL,
  ESPECIE VARCHAR(40) NULL,
  SEXO CHAR(1) NULL,
  RAZA VARCHAR(60) NULL,
  COLOR VARCHAR(40) NULL,
  FECHA_DEFUNCION DATE NULL,
  ACTIVO BIT NULL,
  PRIMARY KEY (MASCOTA_ID),
  CONSTRAINT fk_MASCOTAS_PERSONAS1 FOREIGN KEY (PERSONA_ID) 
    REFERENCES dbo.PERSONAS (PERSONA_ID) ON UPDATE NO ACTION -- Cambio para evitar ciclo
);

-- Tabla: VETERINARIOS
CREATE TABLE dbo.VETERINARIOS (
  VETERINARIO_ID INT IDENTITY(1,1) NOT NULL,
  PERSONA_ID INT NOT NULL,
  FECHA_DE_CONTRATACION DATE NULL,
  ESTADO VARCHAR(20) NULL,
  ESPECIALIDAD VARCHAR(50) NULL,
  ACTIVO BIT NULL,
  PRIMARY KEY (VETERINARIO_ID),
  CONSTRAINT fk_VETERINARIOS_PERSONAS1 FOREIGN KEY (PERSONA_ID) 
    REFERENCES dbo.PERSONAS (PERSONA_ID) ON UPDATE NO ACTION -- Cambio para evitar ciclo
);

-- Tabla: HORARIOS_LABORALES
CREATE TABLE dbo.HORARIOS_LABORALES (
  HORARIO_LABORAL_ID INT IDENTITY(1,1) NOT NULL,
  VETERINARIO_ID INT NOT NULL,
  FECHA DATE NULL,
  ESTADO VARCHAR(45) NULL,
  HORA_INICIO DATETIME NULL,
  HORA_FIN DATETIME NULL,
  ACTIVO BIT NULL,
  PRIMARY KEY (HORARIO_LABORAL_ID),
  CONSTRAINT fk_HORARIOS_LABORALES_VETERINARIOS1 FOREIGN KEY (VETERINARIO_ID) 
    REFERENCES dbo.VETERINARIOS (VETERINARIO_ID)
);

-- Tabla: CITAS_ATENCION
CREATE TABLE dbo.CITAS_ATENCION (
  CITA_ID INT IDENTITY(1,1) NOT NULL,
  VETERINARIO_ID INT NOT NULL,
  MASCOTA_ID INT NOT NULL,
  FECHA_REGISTRO DATE NULL,
  FECHA_HORA_INICIO DATETIME NULL,
  FECHA_HORA_FIN DATETIME NULL,
  PESO_MASCOTA DECIMAL(6,2) NULL,
  MONTO DECIMAL(10,2) NULL,
  ESTADO_CITA VARCHAR(20) NULL,
  OBSERVACION VARCHAR(250) NULL,
  ACTIVO BIT NULL,
  PRIMARY KEY (CITA_ID),
  -- Se elimina ON UPDATE CASCADE para romper el ciclo de referencia múltiple
  CONSTRAINT fk_CITAS_ATENCION_MASCOTAS1 FOREIGN KEY (MASCOTA_ID) 
    REFERENCES dbo.MASCOTAS (MASCOTA_ID),
  CONSTRAINT fk_CITAS_ATENCION_VETERINARIOS1 FOREIGN KEY (VETERINARIO_ID) 
    REFERENCES dbo.VETERINARIOS (VETERINARIO_ID)
);

-- Tabla: RECETAS_MEDICAS
CREATE TABLE dbo.RECETAS_MEDICAS (
  RECETA_MEDICA_ID INT IDENTITY(1,1) NOT NULL,
  CITA_ID INT NOT NULL,
  FECHA_EMISION DATE NOT NULL,
  VIGENCIA_HASTA DATE NULL,
  DIAGNOSTICO VARCHAR(250) NULL,
  OBSERVACIONES VARCHAR(300) NULL,
  ACTIVO BIT NULL,
  PRIMARY KEY (RECETA_MEDICA_ID),
  CONSTRAINT fk_RECETAS_MEDICAS_CITAS_ATENCION1 FOREIGN KEY (CITA_ID) 
    REFERENCES dbo.CITAS_ATENCION (CITA_ID) ON UPDATE CASCADE
);

-- Tabla: DETALLES_RECETA
CREATE TABLE dbo.DETALLES_RECETA (
  DETALLE_RECETA_ID INT IDENTITY(1,1) NOT NULL,
  RECETA_MEDICA_ID INT NOT NULL,
  DESCRIPCION_MEDICAMENTO VARCHAR(150) NOT NULL,
  PRESENTACION VARCHAR(50) NULL,
  VIA_ADMINISTRACION VARCHAR(20) NULL,
  DOSIS VARCHAR(50) NULL,
  FRECUENCIA VARCHAR(50) NULL,
  DURACION VARCHAR(50) NULL,
  INDICACION VARCHAR(250) NULL,
  CANTIDAD VARCHAR(50) NULL,
  ACTIVO BIT NULL,
  PRIMARY KEY (DETALLE_RECETA_ID),
  CONSTRAINT fk_DETALLES_RECETA_RECETAS_MEDICAS1 FOREIGN KEY (RECETA_MEDICA_ID) 
    REFERENCES dbo.RECETAS_MEDICAS (RECETA_MEDICA_ID) ON UPDATE CASCADE
);

-- Tabla: DETALLES_SERVICIO
CREATE TABLE dbo.DETALLES_SERVICIO (
  DETALLE_SERVICIO_ID INT IDENTITY(1,1) NOT NULL,
  CITA_ID INT NOT NULL,
  SERVICIO_ID INT NOT NULL,
  DESCRIPCION VARCHAR(200) NULL,
  COSTO DECIMAL(10,2) NULL,
  ACTIVO BIT NULL,
  PRIMARY KEY (DETALLE_SERVICIO_ID),
  CONSTRAINT fk_DETALLES_SERVICIO_CITAS_ATENCION1 FOREIGN KEY (CITA_ID) 
    REFERENCES dbo.CITAS_ATENCION (CITA_ID) ON UPDATE CASCADE,
  CONSTRAINT fk_DETALLES_SERVICIO_SERVICIOS1 FOREIGN KEY (SERVICIO_ID) 
    REFERENCES dbo.SERVICIOS (SERVICIO_ID) ON UPDATE CASCADE
);

-- Tabla: DOCUMENTOS_DE_PAGO
CREATE TABLE dbo.DOCUMENTOS_DE_PAGO (
  DOCUMENTO_DE_PAGO_ID INT IDENTITY(1,1) NOT NULL,
  METODO_DE_PAGO_ID INT NOT NULL,
  PERSONA_ID INT NULL,
  TIPO_DOCUMENTO VARCHAR(50) NOT NULL,
  SERIE VARCHAR(10) NOT NULL,
  NUMERO VARCHAR(12) NOT NULL,
  FECHA_EMISION DATE NOT NULL,
  ESTADO VARCHAR(20) NULL,
  SUBTOTAL DECIMAL(12,2) NULL,
  IGV_TOTAL DECIMAL(12,2) NULL,
  TOTAL DECIMAL(12,2) NULL,
  ACTIVO BIT NULL,
  PRIMARY KEY (DOCUMENTO_DE_PAGO_ID),
  CONSTRAINT uq_doc_pago_serie_numero UNIQUE (SERIE, NUMERO),
  CONSTRAINT fk_DOC_PAGO_PERSONAS1 FOREIGN KEY (PERSONA_ID) 
    REFERENCES dbo.PERSONAS (PERSONA_ID) ON UPDATE NO ACTION, -- Evita ciclo con Personas
  CONSTRAINT fk_DOCUMENTOS_DE_PAGO_METODOS_DE_PAGO1 FOREIGN KEY (METODO_DE_PAGO_ID) 
    REFERENCES dbo.METODOS_DE_PAGO (METODO_DE_PAGO_ID)
);

-- Tabla: DETALLES_DOCUMENTO_DE_PAGO
CREATE TABLE dbo.DETALLES_DOCUMENTO_DE_PAGO (
  DDDP_ID INT IDENTITY(1,1) NOT NULL,
  DOCUMENTO_DE_PAGO_ID INT NOT NULL,
  SERVICIO_ID INT NULL,
  PRODUCTO_ID INT NULL,
  NRO_ITEM INT NULL,
  DESCRIPCION VARCHAR(200) NULL,
  CANTIDAD INT NULL,
  PRECIO_UNITARIO DECIMAL(10,2) NULL,
  VALOR_VENTA DECIMAL(12,2) NULL,
  ACTIVO BIT NULL,
  PRIMARY KEY (DDDP_ID),
  CONSTRAINT fk_DDDP_DOCUMENTO_DE_PAGO1 FOREIGN KEY (DOCUMENTO_DE_PAGO_ID) 
    REFERENCES dbo.DOCUMENTOS_DE_PAGO (DOCUMENTO_DE_PAGO_ID) ON UPDATE CASCADE,
  CONSTRAINT fk_DDDP_PRODUCTOS1 FOREIGN KEY (PRODUCTO_ID) 
    REFERENCES dbo.PRODUCTOS (PRODUCTO_ID) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_DDDP_SERVICIOS1 FOREIGN KEY (SERVICIO_ID) 
    REFERENCES dbo.SERVICIOS (SERVICIO_ID) ON DELETE SET NULL ON UPDATE CASCADE
);
GO