/* =========================================================
   Script portable para SQL Server (T-SQL)
   Crea BD y tablas del esquema petmedicalcare
   ========================================================= */



USE petmedicalcare;
GO

/* -------------------------
   ROLES
------------------------- */
IF OBJECT_ID(N'dbo.ROLES', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.ROLES (
        ROL_ID  INT IDENTITY(1,1) PRIMARY KEY,
        NOMBRE  NVARCHAR(100) NULL,
        ACTIVO  BIT NULL
    );
END
GO

/* -------------------------
   USUARIOS
------------------------- */
IF OBJECT_ID(N'dbo.USUARIOS', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.USUARIOS (
        USUARIO_ID         INT IDENTITY(1,1) PRIMARY KEY,
        USERNAME           NVARCHAR(100) NULL,   -- corregido de USENAME
        [PASSWORD]         NVARCHAR(100) NULL,
        CORREO             NVARCHAR(100) NULL,
        ACTIVO             BIT NULL,
        FECHA_MODIFICACION DATETIME2(0) NULL,
        USUARIO_MODIFICADOR NVARCHAR(45) NULL,   -- corregido de USUARIO_MOFICADOR
        USUARIO_CREADOR    NVARCHAR(45) NULL,
        FECHA_CREACION     DATETIME2(0) NULL
    );
END
GO

/* -------------------------
   PERSONAS (FK USUARIOS)
------------------------- */
IF OBJECT_ID(N'dbo.PERSONAS', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.PERSONAS (
        PERSONA_ID     INT IDENTITY(1,1) PRIMARY KEY,
        NOMBRE         NVARCHAR(100) NULL,
        DIRECCION      NVARCHAR(100) NULL,
        TELEFONO       NVARCHAR(100) NULL,
        SEXO           CHAR(1) NULL,  -- 'S','M','O' (opcional)
        ACTIVO         BIT NULL,
        TIPO_DOCUMENTO NVARCHAR(45) NULL,
        NRO_DOCUMENTO  NVARCHAR(20) NULL,  -- más seguro que INT (conserva ceros)
        RUC            NVARCHAR(20) NULL,  -- RUC peruano hasta 11 dígitos
        USUARIO_ID     INT NOT NULL,
        CONSTRAINT FK_PERSONAS_USUARIOS
            FOREIGN KEY (USUARIO_ID) REFERENCES dbo.USUARIOS(USUARIO_ID)
                ON DELETE NO ACTION ON UPDATE NO ACTION
    );
    CREATE INDEX IX_PERSONAS_USUARIO_ID ON dbo.PERSONAS(USUARIO_ID);
END
GO

/* -------------------------
   TIPOS_SERVICIO
------------------------- */
IF OBJECT_ID(N'dbo.TIPOS_SERVICIO', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.TIPOS_SERVICIO (
        TIPO_SERVICIO_ID INT IDENTITY(1,1) PRIMARY KEY,
        NOMBRE           NVARCHAR(100) NULL,
        DESCRIPCION      NVARCHAR(100) NULL,
        ACTIVO           BIT NULL
    );
END
GO

/* -------------------------
   TIPOS_PRODUCTO
------------------------- */
IF OBJECT_ID(N'dbo.TIPOS_PRODUCTO', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.TIPOS_PRODUCTO (
        TIPO_PRODUCTO_ID INT IDENTITY(1,1) PRIMARY KEY,
        NOMBRE           NVARCHAR(100) NULL,
        DESCRIPCION      NVARCHAR(100) NULL,
        ACTIVO           BIT NULL
    );
END
GO

/* -------------------------
   TIPOS_DOCUMENTO
------------------------- */
IF OBJECT_ID(N'dbo.TIPOS_DOCUMENTO', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.TIPOS_DOCUMENTO (
        TIPO_DOCUMENTO_ID INT IDENTITY(1,1) PRIMARY KEY,
        NOMBRE            NVARCHAR(100) NULL,
        ACTIVO            BIT NULL
    );
END
GO

/* -------------------------
   MASCOTAS (FK PERSONAS)
------------------------- */
IF OBJECT_ID(N'dbo.MASCOTAS', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.MASCOTAS (
        MASCOTA_ID       INT IDENTITY(1,1) PRIMARY KEY,
        NOMBRE           NVARCHAR(100) NULL,
        ESPECIE          NVARCHAR(100) NULL,
        SEXO             CHAR(1) NULL,
        RAZA             NVARCHAR(45) NULL,
        COLOR            NVARCHAR(45) NULL,
        ACTIVO           BIT NULL,
        FECHA_DEFUNCION  DATETIME2(0) NULL,
        PERSONA_ID       INT NOT NULL,
        CONSTRAINT FK_MASCOTAS_PERSONAS
            FOREIGN KEY (PERSONA_ID) REFERENCES dbo.PERSONAS(PERSONA_ID)
                ON DELETE NO ACTION ON UPDATE NO ACTION
    );
    CREATE INDEX IX_MASCOTAS_PERSONA_ID ON dbo.MASCOTAS(PERSONA_ID);
END
GO

/* -------------------------
   VETERINARIOS (FK PERSONAS)
------------------------- */
IF OBJECT_ID(N'dbo.VETERINARIOS', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.VETERINARIOS (
        VETERINARIO_ID        INT IDENTITY(1,1) PRIMARY KEY,
        ESPECIALIZACION       NVARCHAR(100) NULL,
        FECHA_DE_CONTRATACION DATE NULL,
        ESTADO                NVARCHAR(45) NULL,
        ACTIVO                BIT NULL,
        PERSONA_ID            INT NOT NULL,
        CONSTRAINT FK_VETERINARIOS_PERSONAS
            FOREIGN KEY (PERSONA_ID) REFERENCES dbo.PERSONAS(PERSONA_ID)
                ON DELETE NO ACTION ON UPDATE NO ACTION
    );
    CREATE INDEX IX_VETERINARIOS_PERSONA_ID ON dbo.VETERINARIOS(PERSONA_ID);
END
GO

/* -------------------------
   SERVICIOS (FK TIPOS_SERVICIO)
------------------------- */
IF OBJECT_ID(N'dbo.SERVICIOS', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.SERVICIOS (
        SERVICIO_ID        INT IDENTITY(1,1) PRIMARY KEY,
        NOMBRE             NVARCHAR(100) NULL,
        COSTO              DECIMAL(18,2) NULL,
        ESTADO             NVARCHAR(45) NULL,
        DESCRIPCION        NVARCHAR(100) NULL,
        ACTIVO             BIT NULL,
        FECHA_MODIFICACION DATETIME2(0) NULL,
        USUARIO_MODIFICADOR NVARCHAR(45) NULL,  -- corregido
        USUARIO_CREADOR    NVARCHAR(45) NULL,
        FECHA_CREACION     DATETIME2(0) NULL,
        TIPO_SERVICIO_ID   INT NOT NULL,
        CONSTRAINT FK_SERVICIOS_TIPOS_SERVICIO
            FOREIGN KEY (TIPO_SERVICIO_ID) REFERENCES dbo.TIPOS_SERVICIO(TIPO_SERVICIO_ID)
                ON DELETE NO ACTION ON UPDATE NO ACTION
    );
    CREATE INDEX IX_SERVICIOS_TIPO_SERVICIO_ID ON dbo.SERVICIOS(TIPO_SERVICIO_ID);
END
GO

/* -------------------------
   PRODUCTOS (FK TIPOS_PRODUCTO)
------------------------- */
IF OBJECT_ID(N'dbo.PRODUCTOS', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.PRODUCTOS (
        PRODUCTO_ID        INT IDENTITY(1,1) PRIMARY KEY,
        NOMBRE             NVARCHAR(100) NULL,
        PRESENTACION       NVARCHAR(100) NULL,
        PRECIO_UNITARIO    DECIMAL(18,2) NULL,
        ACTIVO             BIT NULL,
        TIPO_PRODUCTO_ID   INT NOT NULL,
        FECHA_MODIFICACION DATETIME2(0) NULL,
        USUARIO_MODIFICADOR NVARCHAR(45) NULL,  -- corregido
        USUARIO_CREADOR    NVARCHAR(45) NULL,
        FECHA_CREACION     DATETIME2(0) NULL,
        STOCK              INT NULL,            -- de tu ALTER
        CONSTRAINT FK_PRODUCTOS_TIPOS_PRODUCTO
            FOREIGN KEY (TIPO_PRODUCTO_ID) REFERENCES dbo.TIPOS_PRODUCTO(TIPO_PRODUCTO_ID)
                ON DELETE NO ACTION ON UPDATE NO ACTION
    );
    CREATE INDEX IX_PRODUCTOS_TIPO_PRODUCTO_ID ON dbo.PRODUCTOS(TIPO_PRODUCTO_ID);
END
GO

/* -------------------------
   CITAS_ATENCION (FK VETERINARIOS, MASCOTAS)
------------------------- */
IF OBJECT_ID(N'dbo.CITAS_ATENCION', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.CITAS_ATENCION (
        CITA_ID           INT IDENTITY(1,1) PRIMARY KEY,
        OBSERVACION       NVARCHAR(100) NULL,
        FECHA_HORA_INICIO DATETIME2(0) NULL,
        FECHA_REGISTRO    DATE NULL,
        FECHA_HORA_FIN    DATETIME2(0) NULL,
        MONTO             DECIMAL(18,2) NULL,
        ACTIVO            BIT NULL,
        PESO_MASCOTA      DECIMAL(10,2) NULL,
        VETERINARIO_ID    INT NOT NULL,
        MASCOTA_ID        INT NOT NULL,
        ESTADO_CITA       NVARCHAR(255) NULL, -- de tu ALTER
        CONSTRAINT FK_CITAS_VETERINARIOS
            FOREIGN KEY (VETERINARIO_ID) REFERENCES dbo.VETERINARIOS(VETERINARIO_ID)
                ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT FK_CITAS_MASCOTAS
            FOREIGN KEY (MASCOTA_ID) REFERENCES dbo.MASCOTAS(MASCOTA_ID)
                ON DELETE NO ACTION ON UPDATE NO ACTION
    );
    CREATE INDEX IX_CITAS_VETERINARIO_ID ON dbo.CITAS_ATENCION(VETERINARIO_ID);
    CREATE INDEX IX_CITAS_MASCOTA_ID ON dbo.CITAS_ATENCION(MASCOTA_ID);
END
GO

/* -------------------------
   RECETAS_MEDICA (FK CITAS_ATENCION)
------------------------- */
IF OBJECT_ID(N'dbo.RECETAS_MEDICA', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.RECETAS_MEDICA (
        RECETAS_MEDICA_ID INT IDENTITY(1,1) PRIMARY KEY,
        DIAGNOSTICO       NVARCHAR(100) NULL,
        ACTIVO            BIT NULL,
        CITA_ID           INT NOT NULL,
        CONSTRAINT FK_RECETAS_CITAS
            FOREIGN KEY (CITA_ID) REFERENCES dbo.CITAS_ATENCION(CITA_ID)
                ON DELETE NO ACTION ON UPDATE NO ACTION
    );
    CREATE INDEX IX_RECETAS_CITA_ID ON dbo.RECETAS_MEDICA(CITA_ID);
END
GO

/* -------------------------
   ROLES_USUARIO (FK ROLES, USUARIOS)
------------------------- */
IF OBJECT_ID(N'dbo.ROLES_USUARIO', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.ROLES_USUARIO (
        ROL_USUARIO_ID INT IDENTITY(1,1) PRIMARY KEY,
        ROL_ID         INT NOT NULL,
        USUARIO_ID     INT NOT NULL,
        ACTIVO         BIT NULL,
        CONSTRAINT FK_ROLUSU_ROLES
            FOREIGN KEY (ROL_ID) REFERENCES dbo.ROLES(ROL_ID)
                ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT FK_ROLUSU_USUARIOS
            FOREIGN KEY (USUARIO_ID) REFERENCES dbo.USUARIOS(USUARIO_ID)
                ON DELETE NO ACTION ON UPDATE NO ACTION
    );
    CREATE INDEX IX_ROLUSU_ROL_ID ON dbo.ROLES_USUARIO(ROL_ID);
    CREATE INDEX IX_ROLUSU_USUARIO_ID ON dbo.ROLES_USUARIO(USUARIO_ID);
END
GO

/* -------------------------
   DETALLES_SERVICIO (FK SERVICIOS, CITAS_ATENCION)
------------------------- */
IF OBJECT_ID(N'dbo.DETALLES_SERVICIO', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.DETALLES_SERVICIO (
        DETALLE_SERVICIO_ID INT IDENTITY(1,1) PRIMARY KEY,
        DESCRIPCION         NVARCHAR(100) NULL,
        COSTO               DECIMAL(18,2) NULL,
        ACTIVO              BIT NULL,
        SERVICIO_ID         INT NOT NULL,
        CITA_ID             INT NOT NULL,
        CONSTRAINT FK_DETSERV_SERVICIOS
            FOREIGN KEY (SERVICIO_ID) REFERENCES dbo.SERVICIOS(SERVICIO_ID)
                ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT FK_DETSERV_CITAS
            FOREIGN KEY (CITA_ID) REFERENCES dbo.CITAS_ATENCION(CITA_ID)
                ON DELETE NO ACTION ON UPDATE NO ACTION
    );
    CREATE INDEX IX_DETSERV_SERVICIO_ID ON dbo.DETALLES_SERVICIO(SERVICIO_ID);
    CREATE INDEX IX_DETSERV_CITA_ID ON dbo.DETALLES_SERVICIO(CITA_ID);
END
GO

/* -------------------------
   DOCUMENTOS_DE_PAGO (FK TIPOS_DOCUMENTO, PERSONAS)
------------------------- */
IF OBJECT_ID(N'dbo.DOCUMENTOS_DE_PAGO', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.DOCUMENTOS_DE_PAGO (
        DOCUMENTO_DE_PAGO_ID   INT IDENTITY(1,1) PRIMARY KEY,
        SERIE                  NVARCHAR(45) NULL,
        NUMERO                 NVARCHAR(45) NULL,
        TASA_IGV               DECIMAL(5,2) NULL,
        FECHA_EMISION          DATE NULL,
        METODO_DE_PAGO         NVARCHAR(45) NULL,
        ESTADO                 NVARCHAR(100) NULL,
        SUBTOTAL_SIN_IGV       DECIMAL(18,2) NULL,
        IGV_TOTAL              DECIMAL(18,2) NULL,
        TOTAL                  DECIMAL(18,2) NULL,
        ACTIVO                 BIT NULL,
        TIPO_DOCUMENTO_ID      INT NOT NULL,
        PERSONA_ID             INT NOT NULL,
        CONSTRAINT FK_DDP_TIPOSDOC
            FOREIGN KEY (TIPO_DOCUMENTO_ID) REFERENCES dbo.TIPOS_DOCUMENTO(TIPO_DOCUMENTO_ID)
                ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT FK_DDP_PERSONAS
            FOREIGN KEY (PERSONA_ID) REFERENCES dbo.PERSONAS(PERSONA_ID)
                ON DELETE NO ACTION ON UPDATE NO ACTION
    );
    CREATE INDEX IX_DDP_TIPO_DOC_ID ON dbo.DOCUMENTOS_DE_PAGO(TIPO_DOCUMENTO_ID);
    CREATE INDEX IX_DDP_PERSONA_ID  ON dbo.DOCUMENTOS_DE_PAGO(PERSONA_ID);
END
GO

/* -------------------------
   DETALLES_RECETA (FK RECETAS_MEDICA)
------------------------- */
IF OBJECT_ID(N'dbo.DETALLES_RECETA', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.DETALLES_RECETA (
        DETALLE_RECETA_ID       INT IDENTITY(1,1) PRIMARY KEY,
        CANTIDAD                INT NULL,
        DESCRIPCION_MEDICAMENTO NVARCHAR(100) NULL,
        INDICACION              NVARCHAR(100) NULL,
        RECETA_MEDICA_ID        INT NOT NULL,
        ACTIVO                  BIT NULL,
        CONSTRAINT FK_DETREC_RECETA
            FOREIGN KEY (RECETA_MEDICA_ID) REFERENCES dbo.RECETAS_MEDICA(RECETAS_MEDICA_ID)
                ON DELETE NO ACTION ON UPDATE NO ACTION
    );
    CREATE INDEX IX_DETREC_RECETA_ID ON dbo.DETALLES_RECETA(RECETA_MEDICA_ID);
END
GO

/* -------------------------
   DETALLES_DOCUMENTO_DE_PAGO (FK DOCUMENTOS_DE_PAGO, SERVICIOS, PRODUCTOS)
------------------------- */
IF OBJECT_ID(N'dbo.DETALLES_DOCUMENTO_DE_PAGO', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.DETALLES_DOCUMENTO_DE_PAGO (
        DDDP_ID                 INT IDENTITY(1,1) PRIMARY KEY,
        NRO_ITEM                INT NULL,
        DESCRIPCION             NVARCHAR(100) NULL,
        CANTIDAD                INT NULL,
        PRECIO_UNITARIO_SIN_IGV DECIMAL(18,2) NULL,
        VALOR_VENTA             DECIMAL(18,2) NULL,
        IGV_ITEM                DECIMAL(18,2) NULL,
        IMPORTE_TOTAL           DECIMAL(18,2) NULL,
        DOCUMENTO_DE_PAGO_ID    INT NOT NULL,
        SERVICIO_ID             INT NULL,
        PRODUCTO_ID             INT NULL,
        CONSTRAINT FK_DDDP_DDP
            FOREIGN KEY (DOCUMENTO_DE_PAGO_ID) REFERENCES dbo.DOCUMENTOS_DE_PAGO(DOCUMENTO_DE_PAGO_ID)
                ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT FK_DDDP_SERVICIOS
            FOREIGN KEY (SERVICIO_ID) REFERENCES dbo.SERVICIOS(SERVICIO_ID)
                ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT FK_DDDP_PRODUCTOS
            FOREIGN KEY (PRODUCTO_ID) REFERENCES dbo.PRODUCTOS(PRODUCTO_ID)
                ON DELETE NO ACTION ON UPDATE NO ACTION
    );
    CREATE INDEX IX_DDDP_DDP_ID       ON dbo.DETALLES_DOCUMENTO_DE_PAGO(DOCUMENTO_DE_PAGO_ID);
    CREATE INDEX IX_DDDP_SERVICIO_ID  ON dbo.DETALLES_DOCUMENTO_DE_PAGO(SERVICIO_ID);
    CREATE INDEX IX_DDDP_PRODUCTO_ID  ON dbo.DETALLES_DOCUMENTO_DE_PAGO(PRODUCTO_ID);
END
GO

/* =========================================================
   Fin de creación
   ========================================================= */
