-- =====================================================
-- DDL portable (sin esquema) - listo para cualquier schema
-- Fecha: 2025-10-27 11:52:02
-- =====================================================
use petmedicalcare;
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- USUARIOS
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USUARIOS` (
  `USUARIO_ID` INT NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(50) NOT NULL,
  `PASSWORD` VARCHAR(255) NOT NULL COMMENT 'Hash de la contraseña',
  `CORREO` VARCHAR(150) NULL DEFAULT NULL,
  `ACTIVO` TINYINT NULL DEFAULT NULL,
  `USUARIO_CREADOR` VARCHAR(50) NULL DEFAULT NULL,
  `FECHA_CREACION` DATETIME NULL DEFAULT NULL,
  `USUARIO_MODIFICADOR` VARCHAR(50) NULL DEFAULT NULL,
  `FECHA_MODIFICACION` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`USUARIO_ID`),
  UNIQUE INDEX `uq_usuarios_username` (`USERNAME` ASC) VISIBLE,
  UNIQUE INDEX `uq_usuarios_correo` (`CORREO` ASC) VISIBLE
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
COMMENT='Cuentas de acceso al sistema.';

-- -----------------------------------------------------
-- PERSONAS
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PERSONAS` (
  `PERSONA_ID` INT NOT NULL AUTO_INCREMENT,
  `USUARIO_ID` INT NOT NULL,
  `NOMBRE` VARCHAR(120) NOT NULL,
  `DIRECCION` VARCHAR(200) NULL DEFAULT NULL,
  `TELEFONO` VARCHAR(20) NULL DEFAULT NULL,
  `SEXO` CHAR(1) NULL DEFAULT NULL COMMENT 'Valores: M, F, O',
  `NRO_DOCUMENTO` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Puede tener ceros a la izquierda',
  `RUC` VARCHAR(11) NULL DEFAULT NULL COMMENT 'RUC peruano (11 dígitos)',
  `TIPO_DOCUMENTO` VARCHAR(60) NULL DEFAULT NULL,
  `ACTIVO` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`PERSONA_ID`),
  INDEX `fk_PERSONAS_USUARIOS1_idx` (`USUARIO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PERSONAS_USUARIOS1`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `USUARIOS` (`USUARIO_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
COMMENT='Datos personales de clientes/usuarios del servicio.';

-- -----------------------------------------------------
-- MASCOTAS
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MASCOTAS` (
  `MASCOTA_ID` INT NOT NULL AUTO_INCREMENT,
  `PERSONA_ID` INT NOT NULL COMMENT 'Propietario (persona)',
  `NOMBRE` VARCHAR(80) NOT NULL,
  `ESPECIE` VARCHAR(40) NULL DEFAULT NULL,
  `SEXO` CHAR(1) NULL DEFAULT NULL COMMENT 'Valores: M, F, O',
  `RAZA` VARCHAR(60) NULL DEFAULT NULL,
  `COLOR` VARCHAR(40) NULL DEFAULT NULL,
  `FECHA_DEFUNCION` DATE NULL DEFAULT NULL,
  `ACTIVO` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`MASCOTA_ID`),
  INDEX `fk_MASCOTAS_PERSONAS1_idx` (`PERSONA_ID` ASC) VISIBLE,
  CONSTRAINT `fk_MASCOTAS_PERSONAS1`
    FOREIGN KEY (`PERSONA_ID`)
    REFERENCES `PERSONAS` (`PERSONA_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
COMMENT='Mascotas de los clientes.';

-- -----------------------------------------------------
-- VETERINARIOS
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VETERINARIOS` (
  `VETERINARIO_ID` INT NOT NULL AUTO_INCREMENT,
  `PERSONA_ID` INT NOT NULL,
  `FECHA_DE_CONTRATACION` DATE NULL DEFAULT NULL,
  `ESTADO` VARCHAR(20) NULL DEFAULT NULL COMMENT ' ACTIVO, INACTIVO, SUSPENDIDO',
  `ESPECIALIDAD` VARCHAR(50) NULL DEFAULT NULL,
  `ACTIVO` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`VETERINARIO_ID`),
  INDEX `fk_VETERINARIOS_PERSONAS1_idx` (`PERSONA_ID` ASC) VISIBLE,
  CONSTRAINT `fk_VETERINARIOS_PERSONAS1`
    FOREIGN KEY (`PERSONA_ID`)
    REFERENCES `PERSONAS` (`PERSONA_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
COMMENT='Veterinarios. Especialidad normalizada.';

-- -----------------------------------------------------
-- CITAS_ATENCION
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CITAS_ATENCION` (
  `CITA_ID` INT NOT NULL AUTO_INCREMENT,
  `VETERINARIO_ID` INT NOT NULL,
  `MASCOTA_ID` INT NOT NULL,
  `FECHA_REGISTRO` DATE NULL DEFAULT NULL,
  `FECHA_HORA_INICIO` DATETIME NULL DEFAULT NULL,
  `FECHA_HORA_FIN` DATETIME NULL DEFAULT NULL,
  `PESO_MASCOTA` DECIMAL(6,2) NULL DEFAULT NULL,
  `MONTO` DECIMAL(10,2) NULL DEFAULT NULL COMMENT 'Monto estimado o cobrado por la cita (si aplica)',
  `ESTADO_CITA` VARCHAR(20) NULL DEFAULT NULL COMMENT ' PROGRAMADA, ATENDIDA, CANCELADA',
  `OBSERVACION` VARCHAR(250) NULL DEFAULT NULL,
  `ACTIVO` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`CITA_ID`),
  INDEX `fk_CITAS_ATENCION_VETERINARIOS1_idx` (`VETERINARIO_ID` ASC) VISIBLE,
  INDEX `fk_CITAS_ATENCION_MASCOTAS1_idx` (`MASCOTA_ID` ASC) VISIBLE,
  INDEX `idx_CITAS_ATENCION_INICIO` (`FECHA_HORA_INICIO` ASC) VISIBLE,
  CONSTRAINT `fk_CITAS_ATENCION_MASCOTAS1`
    FOREIGN KEY (`MASCOTA_ID`)
    REFERENCES `MASCOTAS` (`MASCOTA_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_CITAS_ATENCION_VETERINARIOS1`
    FOREIGN KEY (`VETERINARIO_ID`)
    REFERENCES `VETERINARIOS` (`VETERINARIO_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
COMMENT='Citas de atención veterinaria.';

-- -----------------------------------------------------
-- METODOS_DE_PAGO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `METODOS_DE_PAGO` (
  `METODO_DE_PAGO_ID` INT NOT NULL,
  `NOMBRE` VARCHAR(60) NOT NULL,
  `ACTIVO` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`METODO_DE_PAGO_ID`)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- DOCUMENTOS_DE_PAGO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DOCUMENTOS_DE_PAGO` (
  `DOCUMENTO_DE_PAGO_ID` INT NOT NULL AUTO_INCREMENT,
  `METODO_DE_PAGO_ID` INT NOT NULL,
  `PERSONA_ID` INT NULL DEFAULT NULL COMMENT 'Cliente que recibe el documento (puede ser null para el caso que se emita una compra con una persona fuera del sistema o sea compra de una empresa)',
  `TIPO_DOCUMENTO` VARCHAR(50) NOT NULL COMMENT 'tipos: Boleta o Factura solamente\n',
  `SERIE` VARCHAR(10) NOT NULL,
  `NUMERO` VARCHAR(12) NOT NULL,
  `FECHA_EMISION` DATE NOT NULL,
  `ESTADO` VARCHAR(20) NULL DEFAULT NULL COMMENT 'EMITIDO, PAGADO, ANULADO',
  `SUBTOTAL` DECIMAL(12,2) NULL DEFAULT NULL COMMENT 'Antes: SUBTOTAL_SIN_IGV',
  `IGV_TOTAL` DECIMAL(12,2) NULL DEFAULT NULL COMMENT 'IGV (18%) calculado a nivel cabecera',
  `TOTAL` DECIMAL(12,2) NULL DEFAULT NULL,
  `ACTIVO` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`DOCUMENTO_DE_PAGO_ID`),
  UNIQUE INDEX `uq_doc_pago_serie_numero` (`SERIE` ASC, `NUMERO` ASC) VISIBLE,
  INDEX `fk_DOC_PAGO_PERSONAS1_idx` (`PERSONA_ID` ASC) VISIBLE,
  INDEX `fk_DOCUMENTOS_DE_PAGO_METODOS_DE_PAGO1_idx` (`METODO_DE_PAGO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_DOC_PAGO_PERSONAS1`
    FOREIGN KEY (`PERSONA_ID`)
    REFERENCES `PERSONAS` (`PERSONA_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_DOCUMENTOS_DE_PAGO_METODOS_DE_PAGO1`
    FOREIGN KEY (`METODO_DE_PAGO_ID`)
    REFERENCES `METODOS_DE_PAGO` (`METODO_DE_PAGO_ID`)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
COMMENT='Documentos de venta. ';

-- -----------------------------------------------------
-- TIPOS_PRODUCTO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TIPOS_PRODUCTO` (
  `TIPO_PRODUCTO_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(80) NOT NULL,
  `DESCRIPCION` VARCHAR(200) NULL DEFAULT NULL,
  `ACTIVO` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`TIPO_PRODUCTO_ID`)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
COMMENT='Catálogo de tipos de producto (medicamentos, accesorios, etc.).';

-- -----------------------------------------------------
-- PRODUCTOS
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRODUCTOS` (
  `PRODUCTO_ID` INT NOT NULL AUTO_INCREMENT,
  `TIPO_PRODUCTO_ID` INT NOT NULL,
  `NOMBRE` VARCHAR(120) NOT NULL,
  `PRESENTACION` VARCHAR(120) NULL DEFAULT NULL COMMENT 'Ej: 50 mg/ml frasco 30 ml',
  `PRECIO_UNITARIO` DECIMAL(10,2) NULL DEFAULT NULL,
  `STOCK` INT NULL DEFAULT NULL,
  `ACTIVO` TINYINT(1) NULL DEFAULT NULL,
  `USUARIO_CREADOR` VARCHAR(50) NULL DEFAULT NULL,
  `FECHA_CREACION` DATETIME NULL DEFAULT NULL,
  `USUARIO_MODIFICADOR` VARCHAR(50) NULL DEFAULT NULL,
  `FECHA_MODIFICACION` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`PRODUCTO_ID`),
  INDEX `fk_PRODUCTOS_TIPOS_PRODUCTO1_idx` (`TIPO_PRODUCTO_ID` ASC) VISIBLE,
  INDEX `idx_PRODUCTOS_NOMBRE` (`NOMBRE` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTOS_TIPOS_PRODUCTO1`
    FOREIGN KEY (`TIPO_PRODUCTO_ID`)
    REFERENCES `TIPOS_PRODUCTO` (`TIPO_PRODUCTO_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
COMMENT='Productos y medicamentos vendidos.';

-- -----------------------------------------------------
-- TIPOS_SERVICIO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TIPOS_SERVICIO` (
  `TIPO_SERVICIO_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(80) NOT NULL,
  `DESCRIPCION` VARCHAR(200) NULL DEFAULT NULL,
  `ACTIVO` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`TIPO_SERVICIO_ID`)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
COMMENT='Catálogo de tipos de servicio (consulta, cirugía, etc.).';

-- -----------------------------------------------------
-- SERVICIOS
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SERVICIOS` (
  `SERVICIO_ID` INT NOT NULL AUTO_INCREMENT,
  `TIPO_SERVICIO_ID` INT NOT NULL,
  `NOMBRE` VARCHAR(100) NOT NULL,
  `DESCRIPCION` VARCHAR(200) NULL DEFAULT NULL,
  `COSTO` DECIMAL(10,2) NULL DEFAULT NULL,
  `ESTADO` VARCHAR(20) NULL DEFAULT NULL COMMENT ' ACTIVO, INACTIVO, SUSPENDIDO',
  `ACTIVO` TINYINT(1) NULL DEFAULT NULL,
  `USUARIO_CREADOR` VARCHAR(50) NULL DEFAULT NULL,
  `FECHA_CREACION` DATETIME NULL DEFAULT NULL,
  `USUARIO_MODIFICADOR` VARCHAR(50) NULL DEFAULT NULL,
  `FECHA_MODIFICACION` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`SERVICIO_ID`),
  INDEX `fk_SERVICIOS_TIPOS_SERVICIO1_idx` (`TIPO_SERVICIO_ID` ASC) VISIBLE,
  INDEX `idx_SERVICIOS_NOMBRE` (`NOMBRE` ASC) VISIBLE,
  CONSTRAINT `fk_SERVICIOS_TIPOS_SERVICIO1`
    FOREIGN KEY (`TIPO_SERVICIO_ID`)
    REFERENCES `TIPOS_SERVICIO` (`TIPO_SERVICIO_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
COMMENT='Servicios que ofrece la veterinaria.';

-- -----------------------------------------------------
-- DETALLES_DOCUMENTO_DE_PAGO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DETALLES_DOCUMENTO_DE_PAGO` (
  `DDDP_ID` INT NOT NULL AUTO_INCREMENT,
  `DOCUMENTO_DE_PAGO_ID` INT NOT NULL,
  `SERVICIO_ID` INT NULL DEFAULT NULL COMMENT 'Si es línea de servicio (opcional, una de las dos: servicio o producto)',
  `PRODUCTO_ID` INT NULL DEFAULT NULL COMMENT 'Si es línea de producto (opcional, una de las dos: servicio o producto)',
  `NRO_ITEM` INT NULL DEFAULT NULL,
  `DESCRIPCION` VARCHAR(200) NULL DEFAULT NULL,
  `CANTIDAD` INT NULL DEFAULT NULL,
  `PRECIO_UNITARIO` DECIMAL(10,2) NULL DEFAULT NULL COMMENT 'Precio unitario sin IGV (el IGV solo se calcula en cabecera)',
  `VALOR_VENTA` DECIMAL(12,2) NULL DEFAULT NULL COMMENT 'CANTIDAD * PRECIO_UNITARIO (sin IGV)',
  `ACTIVO` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`DDDP_ID`),
  INDEX `fk_DDDP_DOCUMENTO_DE_PAGO1_idx` (`DOCUMENTO_DE_PAGO_ID` ASC) VISIBLE,
  INDEX `fk_DDDP_SERVICIOS1_idx` (`SERVICIO_ID` ASC) VISIBLE,
  INDEX `fk_DDDP_PRODUCTOS1_idx` (`PRODUCTO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_DDDP_DOCUMENTO_DE_PAGO1`
    FOREIGN KEY (`DOCUMENTO_DE_PAGO_ID`)
    REFERENCES `DOCUMENTOS_DE_PAGO` (`DOCUMENTO_DE_PAGO_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_DDDP_PRODUCTOS1`
    FOREIGN KEY (`PRODUCTO_ID`)
    REFERENCES `PRODUCTOS` (`PRODUCTO_ID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_DDDP_SERVICIOS1`
    FOREIGN KEY (`SERVICIO_ID`)
    REFERENCES `SERVICIOS` (`SERVICIO_ID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
COMMENT='Detalle del documento de pago. No almacena IGV por línea.';

-- -----------------------------------------------------
-- RECETAS_MEDICAS
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RECETAS_MEDICAS` (
  `RECETA_MEDICA_ID` INT NOT NULL AUTO_INCREMENT,
  `CITA_ID` INT NOT NULL,
  `FECHA_EMISION` DATE NOT NULL,
  `VIGENCIA_HASTA` DATE NULL DEFAULT NULL COMMENT 'Fecha opcional de vigencia',
  `DIAGNOSTICO` VARCHAR(250) NULL DEFAULT NULL,
  `OBSERVACIONES` VARCHAR(300) NULL DEFAULT NULL,
  `ACTIVO` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`RECETA_MEDICA_ID`),
  INDEX `fk_RECETAS_MEDICAS_CITAS_ATENCION1_idx` (`CITA_ID` ASC) VISIBLE,
  CONSTRAINT `fk_RECETAS_MEDICAS_CITAS_ATENCION1`
    FOREIGN KEY (`CITA_ID`)
    REFERENCES `CITAS_ATENCION` (`CITA_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
COMMENT='Recetas médicas emitidas a partir de una cita.';

-- -----------------------------------------------------
-- DETALLES_RECETA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DETALLES_RECETA` (
  `DETALLE_RECETA_ID` INT NOT NULL AUTO_INCREMENT,
  `RECETA_MEDICA_ID` INT NOT NULL,
  `DESCRIPCION_MEDICAMENTO` VARCHAR(150) NOT NULL COMMENT 'Nombre del medicamento',
  `PRESENTACION` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Ej: 50 mg/ml',
  `VIA_ADMINISTRACION` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Ej: ORAL, IV, IM, SC, TOPICA',
  `DOSIS` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Ej: 5 ml',
  `FRECUENCIA` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Ej: cada 8 horas',
  `DURACION` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Ej: 7 días',
  `INDICACION` VARCHAR(250) NULL DEFAULT NULL COMMENT 'Indicaciones adicionales del médico',
  `CANTIDAD` VARCHAR(50) NULL DEFAULT NULL COMMENT'Cantidad que debe comprar',
  `ACTIVO` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`DETALLE_RECETA_ID`),
  INDEX `fk_DETALLES_RECETA_RECETAS_MEDICAS1_idx` (`RECETA_MEDICA_ID` ASC) VISIBLE,
  CONSTRAINT `fk_DETALLES_RECETA_RECETAS_MEDICAS1`
    FOREIGN KEY (`RECETA_MEDICA_ID`)
    REFERENCES `RECETAS_MEDICAS` (`RECETA_MEDICA_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
COMMENT='Detalle de medicamentos e indicaciones de una receta.';

-- -----------------------------------------------------
-- DETALLES_SERVICIO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DETALLES_SERVICIO` (
  `DETALLE_SERVICIO_ID` INT NOT NULL AUTO_INCREMENT,
  `CITA_ID` INT NOT NULL,
  `SERVICIO_ID` INT NOT NULL,
  `DESCRIPCION` VARCHAR(200) NULL DEFAULT NULL,
  `COSTO` DECIMAL(10,2) NULL DEFAULT NULL,
  `ACTIVO` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`DETALLE_SERVICIO_ID`),
  INDEX `fk_DETALLES_SERVICIO_CITAS_ATENCION1_idx` (`CITA_ID` ASC) VISIBLE,
  INDEX `fk_DETALLES_SERVICIO_SERVICIOS1_idx` (`SERVICIO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_DETALLES_SERVICIO_CITAS_ATENCION1`
    FOREIGN KEY (`CITA_ID`)
    REFERENCES `CITAS_ATENCION` (`CITA_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_DETALLES_SERVICIO_SERVICIOS1`
    FOREIGN KEY (`SERVICIO_ID`)
    REFERENCES `SERVICIOS` (`SERVICIO_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
COMMENT='Desglose de servicios realizados en una cita.';

-- -----------------------------------------------------
-- HORARIOS_LABORALES
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HORARIOS_LABORALES` (
  `HORARIO_LABORAL_ID` INT NOT NULL,
  `VETERINARIO_ID` INT NOT NULL COMMENT 'Medico que trabajara en una fecha especifica',
  `FECHA` DATE NULL COMMENT 'La fecha que trabajará', 
  `ESTADO` VARCHAR(45) NULL COMMENT 'DISPONIBLE, NO_DISPONIBLE',
  `HORA_INICIO` DATETIME NULL DEFAULT NULL COMMENT 'Hora que iniciará a trabajar',
  `HORA_FIN` DATETIME NULL DEFAULT NULL  COMMENT 'Hora de fin que trabajará',
  `ACTIVO` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`HORARIO_LABORAL_ID`),
  INDEX `fk_HORARIOS_LABORALES_VETERINARIOS1_idx` (`VETERINARIO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_HORARIOS_LABORALES_VETERINARIOS1`
    FOREIGN KEY (`VETERINARIO_ID`)
    REFERENCES `VETERINARIOS` (`VETERINARIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- ROLES
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ROLES` (
  `ROL_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(50) NOT NULL,
  `ACTIVO` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`ROL_ID`)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
COMMENT='Catálogo de roles de usuario (ADMIN, VET, RECEPCION, etc.).';

-- -----------------------------------------------------
-- ROLES_USUARIO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ROLES_USUARIO` (
  `ROL_USUARIO_ID` INT NOT NULL AUTO_INCREMENT,
  `ROL_ID` INT NOT NULL,
  `USUARIO_ID` INT NOT NULL,
  `ACTIVO` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`ROL_USUARIO_ID`),
  UNIQUE INDEX `uq_roles_usuario` (`ROL_ID` ASC, `USUARIO_ID` ASC) VISIBLE,
  INDEX `fk_ROLES_USUARIO_ROLES_idx` (`ROL_ID` ASC) VISIBLE,
  INDEX `fk_ROLES_USUARIO_USUARIOS1_idx` (`USUARIO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ROLES_USUARIO_ROLES`
    FOREIGN KEY (`ROL_ID`)
    REFERENCES `ROLES` (`ROL_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ROLES_USUARIO_USUARIOS1`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `USUARIOS` (`USUARIO_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
COMMENT='Asignación de roles a usuarios.';
ALTER TABLE HORARIOS_LABORALES
MODIFY COLUMN HORARIO_LABORAL_ID INT NOT NULL AUTO_INCREMENT;
ALTER TABLE METODOS_DE_PAGO
MODIFY COLUMN METODO_DE_PAGO_ID INT NOT NULL AUTO_INCREMENT;

ALTER TABLE VETERINARIOS
DROP COLUMN ESPECIALIDAD_ID;

-- =====================================================
-- FIN
-- =====================================================
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
