//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPetBussiness.DetalleRecetaClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/", ConfigurationName="DetalleRecetaClient.DetallesReceta")]
    public interface DetallesReceta {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://detallereceta.softpetws.pucp.edu.pe/DetallesReceta/listar_detalles_por_rec" +
            "etaRequest", ReplyAction="http://detallereceta.softpetws.pucp.edu.pe/DetallesReceta/listar_detalles_por_rec" +
            "etaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.DetalleRecetaClient.listar_detalles_por_recetaResponse listar_detalles_por_receta(SoftPetBussiness.DetalleRecetaClient.listar_detalles_por_recetaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://detallereceta.softpetws.pucp.edu.pe/DetallesReceta/listar_detalles_por_rec" +
            "etaRequest", ReplyAction="http://detallereceta.softpetws.pucp.edu.pe/DetallesReceta/listar_detalles_por_rec" +
            "etaResponse")]
        System.Threading.Tasks.Task<SoftPetBussiness.DetalleRecetaClient.listar_detalles_por_recetaResponse> listar_detalles_por_recetaAsync(SoftPetBussiness.DetalleRecetaClient.listar_detalles_por_recetaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://detallereceta.softpetws.pucp.edu.pe/DetallesReceta/insertar_detallerecetaR" +
            "equest", ReplyAction="http://detallereceta.softpetws.pucp.edu.pe/DetallesReceta/insertar_detallerecetaR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.DetalleRecetaClient.insertar_detallerecetaResponse insertar_detallereceta(SoftPetBussiness.DetalleRecetaClient.insertar_detallerecetaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://detallereceta.softpetws.pucp.edu.pe/DetallesReceta/insertar_detallerecetaR" +
            "equest", ReplyAction="http://detallereceta.softpetws.pucp.edu.pe/DetallesReceta/insertar_detallerecetaR" +
            "esponse")]
        System.Threading.Tasks.Task<SoftPetBussiness.DetalleRecetaClient.insertar_detallerecetaResponse> insertar_detallerecetaAsync(SoftPetBussiness.DetalleRecetaClient.insertar_detallerecetaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://detallereceta.softpetws.pucp.edu.pe/DetallesReceta/modificar_detallereceta" +
            "Request", ReplyAction="http://detallereceta.softpetws.pucp.edu.pe/DetallesReceta/modificar_detallereceta" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.DetalleRecetaClient.modificar_detallerecetaResponse modificar_detallereceta(SoftPetBussiness.DetalleRecetaClient.modificar_detallerecetaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://detallereceta.softpetws.pucp.edu.pe/DetallesReceta/modificar_detallereceta" +
            "Request", ReplyAction="http://detallereceta.softpetws.pucp.edu.pe/DetallesReceta/modificar_detallereceta" +
            "Response")]
        System.Threading.Tasks.Task<SoftPetBussiness.DetalleRecetaClient.modificar_detallerecetaResponse> modificar_detallerecetaAsync(SoftPetBussiness.DetalleRecetaClient.modificar_detallerecetaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://detallereceta.softpetws.pucp.edu.pe/DetallesReceta/eliminar_detallerecetaR" +
            "equest", ReplyAction="http://detallereceta.softpetws.pucp.edu.pe/DetallesReceta/eliminar_detallerecetaR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.DetalleRecetaClient.eliminar_detallerecetaResponse eliminar_detallereceta(SoftPetBussiness.DetalleRecetaClient.eliminar_detallerecetaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://detallereceta.softpetws.pucp.edu.pe/DetallesReceta/eliminar_detallerecetaR" +
            "equest", ReplyAction="http://detallereceta.softpetws.pucp.edu.pe/DetallesReceta/eliminar_detallerecetaR" +
            "esponse")]
        System.Threading.Tasks.Task<SoftPetBussiness.DetalleRecetaClient.eliminar_detallerecetaResponse> eliminar_detallerecetaAsync(SoftPetBussiness.DetalleRecetaClient.eliminar_detallerecetaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://detallereceta.softpetws.pucp.edu.pe/DetallesReceta/obtener_por_idRequest", ReplyAction="http://detallereceta.softpetws.pucp.edu.pe/DetallesReceta/obtener_por_idResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.DetalleRecetaClient.obtener_por_idResponse obtener_por_id(SoftPetBussiness.DetalleRecetaClient.obtener_por_idRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://detallereceta.softpetws.pucp.edu.pe/DetallesReceta/obtener_por_idRequest", ReplyAction="http://detallereceta.softpetws.pucp.edu.pe/DetallesReceta/obtener_por_idResponse")]
        System.Threading.Tasks.Task<SoftPetBussiness.DetalleRecetaClient.obtener_por_idResponse> obtener_por_idAsync(SoftPetBussiness.DetalleRecetaClient.obtener_por_idRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://detallereceta.softpetws.pucp.edu.pe/DetallesReceta/listar_todosRequest", ReplyAction="http://detallereceta.softpetws.pucp.edu.pe/DetallesReceta/listar_todosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.DetalleRecetaClient.listar_todosResponse listar_todos(SoftPetBussiness.DetalleRecetaClient.listar_todosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://detallereceta.softpetws.pucp.edu.pe/DetallesReceta/listar_todosRequest", ReplyAction="http://detallereceta.softpetws.pucp.edu.pe/DetallesReceta/listar_todosResponse")]
        System.Threading.Tasks.Task<SoftPetBussiness.DetalleRecetaClient.listar_todosResponse> listar_todosAsync(SoftPetBussiness.DetalleRecetaClient.listar_todosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/")]
    public partial class detalleRecetaDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private string cantidadField;
        
        private string descripcionMedicamentoField;
        
        private int detalleRecetaIdField;
        
        private bool detalleRecetaIdFieldSpecified;
        
        private string dosisField;
        
        private string duracionField;
        
        private string frecuenciaField;
        
        private string indicacionField;
        
        private string presentacionField;
        
        private recetaMedicaDto recetaField;
        
        private string viaAdministracionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcionMedicamento {
            get {
                return this.descripcionMedicamentoField;
            }
            set {
                this.descripcionMedicamentoField = value;
                this.RaisePropertyChanged("descripcionMedicamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int detalleRecetaId {
            get {
                return this.detalleRecetaIdField;
            }
            set {
                this.detalleRecetaIdField = value;
                this.RaisePropertyChanged("detalleRecetaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool detalleRecetaIdSpecified {
            get {
                return this.detalleRecetaIdFieldSpecified;
            }
            set {
                this.detalleRecetaIdFieldSpecified = value;
                this.RaisePropertyChanged("detalleRecetaIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string dosis {
            get {
                return this.dosisField;
            }
            set {
                this.dosisField = value;
                this.RaisePropertyChanged("dosis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string duracion {
            get {
                return this.duracionField;
            }
            set {
                this.duracionField = value;
                this.RaisePropertyChanged("duracion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string frecuencia {
            get {
                return this.frecuenciaField;
            }
            set {
                this.frecuenciaField = value;
                this.RaisePropertyChanged("frecuencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string indicacion {
            get {
                return this.indicacionField;
            }
            set {
                this.indicacionField = value;
                this.RaisePropertyChanged("indicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string presentacion {
            get {
                return this.presentacionField;
            }
            set {
                this.presentacionField = value;
                this.RaisePropertyChanged("presentacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public recetaMedicaDto receta {
            get {
                return this.recetaField;
            }
            set {
                this.recetaField = value;
                this.RaisePropertyChanged("receta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string viaAdministracion {
            get {
                return this.viaAdministracionField;
            }
            set {
                this.viaAdministracionField = value;
                this.RaisePropertyChanged("viaAdministracion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/")]
    public partial class recetaMedicaDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private citaAtencionDto citaField;
        
        private string diagnosticoField;
        
        private System.DateTime fechaEmisionField;
        
        private bool fechaEmisionFieldSpecified;
        
        private string fechaEmisionstrField;
        
        private string observacionesField;
        
        private int recetaMedicaIdField;
        
        private bool recetaMedicaIdFieldSpecified;
        
        private System.DateTime vigenciaHastaField;
        
        private bool vigenciaHastaFieldSpecified;
        
        private string vigenciaHastastrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public citaAtencionDto cita {
            get {
                return this.citaField;
            }
            set {
                this.citaField = value;
                this.RaisePropertyChanged("cita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string diagnostico {
            get {
                return this.diagnosticoField;
            }
            set {
                this.diagnosticoField = value;
                this.RaisePropertyChanged("diagnostico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaEmision {
            get {
                return this.fechaEmisionField;
            }
            set {
                this.fechaEmisionField = value;
                this.RaisePropertyChanged("fechaEmision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaEmisionSpecified {
            get {
                return this.fechaEmisionFieldSpecified;
            }
            set {
                this.fechaEmisionFieldSpecified = value;
                this.RaisePropertyChanged("fechaEmisionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string fechaEmisionstr {
            get {
                return this.fechaEmisionstrField;
            }
            set {
                this.fechaEmisionstrField = value;
                this.RaisePropertyChanged("fechaEmisionstr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string observaciones {
            get {
                return this.observacionesField;
            }
            set {
                this.observacionesField = value;
                this.RaisePropertyChanged("observaciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int recetaMedicaId {
            get {
                return this.recetaMedicaIdField;
            }
            set {
                this.recetaMedicaIdField = value;
                this.RaisePropertyChanged("recetaMedicaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool recetaMedicaIdSpecified {
            get {
                return this.recetaMedicaIdFieldSpecified;
            }
            set {
                this.recetaMedicaIdFieldSpecified = value;
                this.RaisePropertyChanged("recetaMedicaIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime vigenciaHasta {
            get {
                return this.vigenciaHastaField;
            }
            set {
                this.vigenciaHastaField = value;
                this.RaisePropertyChanged("vigenciaHasta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vigenciaHastaSpecified {
            get {
                return this.vigenciaHastaFieldSpecified;
            }
            set {
                this.vigenciaHastaFieldSpecified = value;
                this.RaisePropertyChanged("vigenciaHastaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string vigenciaHastastr {
            get {
                return this.vigenciaHastastrField;
            }
            set {
                this.vigenciaHastastrField = value;
                this.RaisePropertyChanged("vigenciaHastastr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/")]
    public partial class citaAtencionDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private int citaIdField;
        
        private bool citaIdFieldSpecified;
        
        private estadoCita estadoField;
        
        private bool estadoFieldSpecified;
        
        private timestamp fechaHoraFinField;
        
        private string fechaHoraFinStrField;
        
        private timestamp fechaHoraInicioField;
        
        private string fechaHoraInicioStrField;
        
        private date fechaRegistroField;
        
        private string fechaRegistroStrField;
        
        private mascotaDto mascotaField;
        
        private double montoField;
        
        private bool montoFieldSpecified;
        
        private string observacionField;
        
        private double pesoMascotaField;
        
        private bool pesoMascotaFieldSpecified;
        
        private veterinarioDto veterinarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int citaId {
            get {
                return this.citaIdField;
            }
            set {
                this.citaIdField = value;
                this.RaisePropertyChanged("citaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool citaIdSpecified {
            get {
                return this.citaIdFieldSpecified;
            }
            set {
                this.citaIdFieldSpecified = value;
                this.RaisePropertyChanged("citaIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public estadoCita estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public timestamp fechaHoraFin {
            get {
                return this.fechaHoraFinField;
            }
            set {
                this.fechaHoraFinField = value;
                this.RaisePropertyChanged("fechaHoraFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string fechaHoraFinStr {
            get {
                return this.fechaHoraFinStrField;
            }
            set {
                this.fechaHoraFinStrField = value;
                this.RaisePropertyChanged("fechaHoraFinStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public timestamp fechaHoraInicio {
            get {
                return this.fechaHoraInicioField;
            }
            set {
                this.fechaHoraInicioField = value;
                this.RaisePropertyChanged("fechaHoraInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string fechaHoraInicioStr {
            get {
                return this.fechaHoraInicioStrField;
            }
            set {
                this.fechaHoraInicioStrField = value;
                this.RaisePropertyChanged("fechaHoraInicioStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public date fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
                this.RaisePropertyChanged("fechaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string fechaRegistroStr {
            get {
                return this.fechaRegistroStrField;
            }
            set {
                this.fechaRegistroStrField = value;
                this.RaisePropertyChanged("fechaRegistroStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public mascotaDto mascota {
            get {
                return this.mascotaField;
            }
            set {
                this.mascotaField = value;
                this.RaisePropertyChanged("mascota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public double monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
                this.RaisePropertyChanged("monto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool montoSpecified {
            get {
                return this.montoFieldSpecified;
            }
            set {
                this.montoFieldSpecified = value;
                this.RaisePropertyChanged("montoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string observacion {
            get {
                return this.observacionField;
            }
            set {
                this.observacionField = value;
                this.RaisePropertyChanged("observacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public double pesoMascota {
            get {
                return this.pesoMascotaField;
            }
            set {
                this.pesoMascotaField = value;
                this.RaisePropertyChanged("pesoMascota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pesoMascotaSpecified {
            get {
                return this.pesoMascotaFieldSpecified;
            }
            set {
                this.pesoMascotaFieldSpecified = value;
                this.RaisePropertyChanged("pesoMascotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public veterinarioDto veterinario {
            get {
                return this.veterinarioField;
            }
            set {
                this.veterinarioField = value;
                this.RaisePropertyChanged("veterinario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/")]
    public enum estadoCita {
        
        /// <remarks/>
        PROGRAMADA,
        
        /// <remarks/>
        ATENDIDA,
        
        /// <remarks/>
        CANCELADA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/")]
    public partial class timestamp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int nanosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int nanos {
            get {
                return this.nanosField;
            }
            set {
                this.nanosField = value;
                this.RaisePropertyChanged("nanos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/")]
    public partial class veterinarioDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private string especialidadField;
        
        private estadoVeterinario estadoField;
        
        private bool estadoFieldSpecified;
        
        private System.DateTime fechaContratacionField;
        
        private bool fechaContratacionFieldSpecified;
        
        private personaDto personaField;
        
        private int veterinarioIdField;
        
        private bool veterinarioIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
                this.RaisePropertyChanged("especialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public estadoVeterinario estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaContratacion {
            get {
                return this.fechaContratacionField;
            }
            set {
                this.fechaContratacionField = value;
                this.RaisePropertyChanged("fechaContratacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaContratacionSpecified {
            get {
                return this.fechaContratacionFieldSpecified;
            }
            set {
                this.fechaContratacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaContratacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public personaDto persona {
            get {
                return this.personaField;
            }
            set {
                this.personaField = value;
                this.RaisePropertyChanged("persona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int veterinarioId {
            get {
                return this.veterinarioIdField;
            }
            set {
                this.veterinarioIdField = value;
                this.RaisePropertyChanged("veterinarioId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool veterinarioIdSpecified {
            get {
                return this.veterinarioIdFieldSpecified;
            }
            set {
                this.veterinarioIdFieldSpecified = value;
                this.RaisePropertyChanged("veterinarioIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/")]
    public enum estadoVeterinario {
        
        /// <remarks/>
        ACTIVO,
        
        /// <remarks/>
        INACTIVO,
        
        /// <remarks/>
        SUSPENDIDO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/")]
    public partial class personaDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private string direccionField;
        
        private string nombreField;
        
        private int nroDocumentoField;
        
        private bool nroDocumentoFieldSpecified;
        
        private int personaIdField;
        
        private bool personaIdFieldSpecified;
        
        private int rucField;
        
        private bool rucFieldSpecified;
        
        private sexo sexoField;
        
        private bool sexoFieldSpecified;
        
        private string telefonoField;
        
        private string tipoDocumentoField;
        
        private usuarioDto usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int nroDocumento {
            get {
                return this.nroDocumentoField;
            }
            set {
                this.nroDocumentoField = value;
                this.RaisePropertyChanged("nroDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nroDocumentoSpecified {
            get {
                return this.nroDocumentoFieldSpecified;
            }
            set {
                this.nroDocumentoFieldSpecified = value;
                this.RaisePropertyChanged("nroDocumentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int personaId {
            get {
                return this.personaIdField;
            }
            set {
                this.personaIdField = value;
                this.RaisePropertyChanged("personaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool personaIdSpecified {
            get {
                return this.personaIdFieldSpecified;
            }
            set {
                this.personaIdFieldSpecified = value;
                this.RaisePropertyChanged("personaIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int ruc {
            get {
                return this.rucField;
            }
            set {
                this.rucField = value;
                this.RaisePropertyChanged("ruc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rucSpecified {
            get {
                return this.rucFieldSpecified;
            }
            set {
                this.rucFieldSpecified = value;
                this.RaisePropertyChanged("rucSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public sexo sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sexoSpecified {
            get {
                return this.sexoFieldSpecified;
            }
            set {
                this.sexoFieldSpecified = value;
                this.RaisePropertyChanged("sexoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public usuarioDto usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/")]
    public enum sexo {
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        O,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/")]
    public partial class usuarioDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private string correoField;
        
        private date fechaCreacionField;
        
        private date fechaModificacionField;
        
        private string passwordField;
        
        private string usernameField;
        
        private string usuarioCreadorField;
        
        private int usuarioIdField;
        
        private bool usuarioIdFieldSpecified;
        
        private string usuarioModificadorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public date fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public date fechaModificacion {
            get {
                return this.fechaModificacionField;
            }
            set {
                this.fechaModificacionField = value;
                this.RaisePropertyChanged("fechaModificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string usuarioCreador {
            get {
                return this.usuarioCreadorField;
            }
            set {
                this.usuarioCreadorField = value;
                this.RaisePropertyChanged("usuarioCreador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int usuarioId {
            get {
                return this.usuarioIdField;
            }
            set {
                this.usuarioIdField = value;
                this.RaisePropertyChanged("usuarioId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usuarioIdSpecified {
            get {
                return this.usuarioIdFieldSpecified;
            }
            set {
                this.usuarioIdFieldSpecified = value;
                this.RaisePropertyChanged("usuarioIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string usuarioModificador {
            get {
                return this.usuarioModificadorField;
            }
            set {
                this.usuarioModificadorField = value;
                this.RaisePropertyChanged("usuarioModificador");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/")]
    public partial class date : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/")]
    public partial class mascotaDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private string colorField;
        
        private string especieField;
        
        private System.DateTime fechaDefuncionField;
        
        private bool fechaDefuncionFieldSpecified;
        
        private int mascotaIdField;
        
        private bool mascotaIdFieldSpecified;
        
        private string nombreField;
        
        private personaDto personaField;
        
        private string razaField;
        
        private string sexoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
                this.RaisePropertyChanged("color");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string especie {
            get {
                return this.especieField;
            }
            set {
                this.especieField = value;
                this.RaisePropertyChanged("especie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaDefuncion {
            get {
                return this.fechaDefuncionField;
            }
            set {
                this.fechaDefuncionField = value;
                this.RaisePropertyChanged("fechaDefuncion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaDefuncionSpecified {
            get {
                return this.fechaDefuncionFieldSpecified;
            }
            set {
                this.fechaDefuncionFieldSpecified = value;
                this.RaisePropertyChanged("fechaDefuncionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int mascotaId {
            get {
                return this.mascotaIdField;
            }
            set {
                this.mascotaIdField = value;
                this.RaisePropertyChanged("mascotaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mascotaIdSpecified {
            get {
                return this.mascotaIdFieldSpecified;
            }
            set {
                this.mascotaIdFieldSpecified = value;
                this.RaisePropertyChanged("mascotaIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public personaDto persona {
            get {
                return this.personaField;
            }
            set {
                this.personaField = value;
                this.RaisePropertyChanged("persona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string raza {
            get {
                return this.razaField;
            }
            set {
                this.razaField = value;
                this.RaisePropertyChanged("raza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listar_detalles_por_receta", WrapperNamespace="http://detallereceta.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class listar_detalles_por_recetaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int recetaId;
        
        public listar_detalles_por_recetaRequest() {
        }
        
        public listar_detalles_por_recetaRequest(int recetaId) {
            this.recetaId = recetaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listar_detalles_por_recetaResponse", WrapperNamespace="http://detallereceta.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class listar_detalles_por_recetaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPetBussiness.DetalleRecetaClient.detalleRecetaDto[] @return;
        
        public listar_detalles_por_recetaResponse() {
        }
        
        public listar_detalles_por_recetaResponse(SoftPetBussiness.DetalleRecetaClient.detalleRecetaDto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertar_detallereceta", WrapperNamespace="http://detallereceta.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertar_detallerecetaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int recetaMedicaId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcionMedicamento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string presentacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string viaAdministracion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dosis;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string frecuencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string duracion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string indicacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cantidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool activo;
        
        public insertar_detallerecetaRequest() {
        }
        
        public insertar_detallerecetaRequest(int recetaMedicaId, string descripcionMedicamento, string presentacion, string viaAdministracion, string dosis, string frecuencia, string duracion, string indicacion, string cantidad, bool activo) {
            this.recetaMedicaId = recetaMedicaId;
            this.descripcionMedicamento = descripcionMedicamento;
            this.presentacion = presentacion;
            this.viaAdministracion = viaAdministracion;
            this.dosis = dosis;
            this.frecuencia = frecuencia;
            this.duracion = duracion;
            this.indicacion = indicacion;
            this.cantidad = cantidad;
            this.activo = activo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertar_detallerecetaResponse", WrapperNamespace="http://detallereceta.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertar_detallerecetaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertar_detallerecetaResponse() {
        }
        
        public insertar_detallerecetaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificar_detallereceta", WrapperNamespace="http://detallereceta.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificar_detallerecetaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int detalleRecetaId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int recetaMedicaId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcionMedicamento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string presentacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string viaAdministracion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dosis;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string frecuencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string duracion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string indicacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cantidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool activo;
        
        public modificar_detallerecetaRequest() {
        }
        
        public modificar_detallerecetaRequest(int detalleRecetaId, int recetaMedicaId, string descripcionMedicamento, string presentacion, string viaAdministracion, string dosis, string frecuencia, string duracion, string indicacion, string cantidad, bool activo) {
            this.detalleRecetaId = detalleRecetaId;
            this.recetaMedicaId = recetaMedicaId;
            this.descripcionMedicamento = descripcionMedicamento;
            this.presentacion = presentacion;
            this.viaAdministracion = viaAdministracion;
            this.dosis = dosis;
            this.frecuencia = frecuencia;
            this.duracion = duracion;
            this.indicacion = indicacion;
            this.cantidad = cantidad;
            this.activo = activo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificar_detallerecetaResponse", WrapperNamespace="http://detallereceta.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificar_detallerecetaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificar_detallerecetaResponse() {
        }
        
        public modificar_detallerecetaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminar_detallereceta", WrapperNamespace="http://detallereceta.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminar_detallerecetaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int detalleRecetaId;
        
        public eliminar_detallerecetaRequest() {
        }
        
        public eliminar_detallerecetaRequest(int detalleRecetaId) {
            this.detalleRecetaId = detalleRecetaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminar_detallerecetaResponse", WrapperNamespace="http://detallereceta.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminar_detallerecetaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminar_detallerecetaResponse() {
        }
        
        public eliminar_detallerecetaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtener_por_id", WrapperNamespace="http://detallereceta.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtener_por_idRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int detalleRecetaId;
        
        public obtener_por_idRequest() {
        }
        
        public obtener_por_idRequest(int detalleRecetaId) {
            this.detalleRecetaId = detalleRecetaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtener_por_idResponse", WrapperNamespace="http://detallereceta.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtener_por_idResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPetBussiness.DetalleRecetaClient.detalleRecetaDto @return;
        
        public obtener_por_idResponse() {
        }
        
        public obtener_por_idResponse(SoftPetBussiness.DetalleRecetaClient.detalleRecetaDto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listar_todos", WrapperNamespace="http://detallereceta.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class listar_todosRequest {
        
        public listar_todosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listar_todosResponse", WrapperNamespace="http://detallereceta.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class listar_todosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detallereceta.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPetBussiness.DetalleRecetaClient.detalleRecetaDto[] @return;
        
        public listar_todosResponse() {
        }
        
        public listar_todosResponse(SoftPetBussiness.DetalleRecetaClient.detalleRecetaDto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DetallesRecetaChannel : SoftPetBussiness.DetalleRecetaClient.DetallesReceta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DetallesRecetaClient : System.ServiceModel.ClientBase<SoftPetBussiness.DetalleRecetaClient.DetallesReceta>, SoftPetBussiness.DetalleRecetaClient.DetallesReceta {
        
        public DetallesRecetaClient() {
        }
        
        public DetallesRecetaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DetallesRecetaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DetallesRecetaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DetallesRecetaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.DetalleRecetaClient.listar_detalles_por_recetaResponse SoftPetBussiness.DetalleRecetaClient.DetallesReceta.listar_detalles_por_receta(SoftPetBussiness.DetalleRecetaClient.listar_detalles_por_recetaRequest request) {
            return base.Channel.listar_detalles_por_receta(request);
        }
        
        public SoftPetBussiness.DetalleRecetaClient.detalleRecetaDto[] listar_detalles_por_receta(int recetaId) {
            SoftPetBussiness.DetalleRecetaClient.listar_detalles_por_recetaRequest inValue = new SoftPetBussiness.DetalleRecetaClient.listar_detalles_por_recetaRequest();
            inValue.recetaId = recetaId;
            SoftPetBussiness.DetalleRecetaClient.listar_detalles_por_recetaResponse retVal = ((SoftPetBussiness.DetalleRecetaClient.DetallesReceta)(this)).listar_detalles_por_receta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.DetalleRecetaClient.listar_detalles_por_recetaResponse> SoftPetBussiness.DetalleRecetaClient.DetallesReceta.listar_detalles_por_recetaAsync(SoftPetBussiness.DetalleRecetaClient.listar_detalles_por_recetaRequest request) {
            return base.Channel.listar_detalles_por_recetaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.DetalleRecetaClient.listar_detalles_por_recetaResponse> listar_detalles_por_recetaAsync(int recetaId) {
            SoftPetBussiness.DetalleRecetaClient.listar_detalles_por_recetaRequest inValue = new SoftPetBussiness.DetalleRecetaClient.listar_detalles_por_recetaRequest();
            inValue.recetaId = recetaId;
            return ((SoftPetBussiness.DetalleRecetaClient.DetallesReceta)(this)).listar_detalles_por_recetaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.DetalleRecetaClient.insertar_detallerecetaResponse SoftPetBussiness.DetalleRecetaClient.DetallesReceta.insertar_detallereceta(SoftPetBussiness.DetalleRecetaClient.insertar_detallerecetaRequest request) {
            return base.Channel.insertar_detallereceta(request);
        }
        
        public int insertar_detallereceta(int recetaMedicaId, string descripcionMedicamento, string presentacion, string viaAdministracion, string dosis, string frecuencia, string duracion, string indicacion, string cantidad, bool activo) {
            SoftPetBussiness.DetalleRecetaClient.insertar_detallerecetaRequest inValue = new SoftPetBussiness.DetalleRecetaClient.insertar_detallerecetaRequest();
            inValue.recetaMedicaId = recetaMedicaId;
            inValue.descripcionMedicamento = descripcionMedicamento;
            inValue.presentacion = presentacion;
            inValue.viaAdministracion = viaAdministracion;
            inValue.dosis = dosis;
            inValue.frecuencia = frecuencia;
            inValue.duracion = duracion;
            inValue.indicacion = indicacion;
            inValue.cantidad = cantidad;
            inValue.activo = activo;
            SoftPetBussiness.DetalleRecetaClient.insertar_detallerecetaResponse retVal = ((SoftPetBussiness.DetalleRecetaClient.DetallesReceta)(this)).insertar_detallereceta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.DetalleRecetaClient.insertar_detallerecetaResponse> SoftPetBussiness.DetalleRecetaClient.DetallesReceta.insertar_detallerecetaAsync(SoftPetBussiness.DetalleRecetaClient.insertar_detallerecetaRequest request) {
            return base.Channel.insertar_detallerecetaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.DetalleRecetaClient.insertar_detallerecetaResponse> insertar_detallerecetaAsync(int recetaMedicaId, string descripcionMedicamento, string presentacion, string viaAdministracion, string dosis, string frecuencia, string duracion, string indicacion, string cantidad, bool activo) {
            SoftPetBussiness.DetalleRecetaClient.insertar_detallerecetaRequest inValue = new SoftPetBussiness.DetalleRecetaClient.insertar_detallerecetaRequest();
            inValue.recetaMedicaId = recetaMedicaId;
            inValue.descripcionMedicamento = descripcionMedicamento;
            inValue.presentacion = presentacion;
            inValue.viaAdministracion = viaAdministracion;
            inValue.dosis = dosis;
            inValue.frecuencia = frecuencia;
            inValue.duracion = duracion;
            inValue.indicacion = indicacion;
            inValue.cantidad = cantidad;
            inValue.activo = activo;
            return ((SoftPetBussiness.DetalleRecetaClient.DetallesReceta)(this)).insertar_detallerecetaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.DetalleRecetaClient.modificar_detallerecetaResponse SoftPetBussiness.DetalleRecetaClient.DetallesReceta.modificar_detallereceta(SoftPetBussiness.DetalleRecetaClient.modificar_detallerecetaRequest request) {
            return base.Channel.modificar_detallereceta(request);
        }
        
        public int modificar_detallereceta(int detalleRecetaId, int recetaMedicaId, string descripcionMedicamento, string presentacion, string viaAdministracion, string dosis, string frecuencia, string duracion, string indicacion, string cantidad, bool activo) {
            SoftPetBussiness.DetalleRecetaClient.modificar_detallerecetaRequest inValue = new SoftPetBussiness.DetalleRecetaClient.modificar_detallerecetaRequest();
            inValue.detalleRecetaId = detalleRecetaId;
            inValue.recetaMedicaId = recetaMedicaId;
            inValue.descripcionMedicamento = descripcionMedicamento;
            inValue.presentacion = presentacion;
            inValue.viaAdministracion = viaAdministracion;
            inValue.dosis = dosis;
            inValue.frecuencia = frecuencia;
            inValue.duracion = duracion;
            inValue.indicacion = indicacion;
            inValue.cantidad = cantidad;
            inValue.activo = activo;
            SoftPetBussiness.DetalleRecetaClient.modificar_detallerecetaResponse retVal = ((SoftPetBussiness.DetalleRecetaClient.DetallesReceta)(this)).modificar_detallereceta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.DetalleRecetaClient.modificar_detallerecetaResponse> SoftPetBussiness.DetalleRecetaClient.DetallesReceta.modificar_detallerecetaAsync(SoftPetBussiness.DetalleRecetaClient.modificar_detallerecetaRequest request) {
            return base.Channel.modificar_detallerecetaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.DetalleRecetaClient.modificar_detallerecetaResponse> modificar_detallerecetaAsync(int detalleRecetaId, int recetaMedicaId, string descripcionMedicamento, string presentacion, string viaAdministracion, string dosis, string frecuencia, string duracion, string indicacion, string cantidad, bool activo) {
            SoftPetBussiness.DetalleRecetaClient.modificar_detallerecetaRequest inValue = new SoftPetBussiness.DetalleRecetaClient.modificar_detallerecetaRequest();
            inValue.detalleRecetaId = detalleRecetaId;
            inValue.recetaMedicaId = recetaMedicaId;
            inValue.descripcionMedicamento = descripcionMedicamento;
            inValue.presentacion = presentacion;
            inValue.viaAdministracion = viaAdministracion;
            inValue.dosis = dosis;
            inValue.frecuencia = frecuencia;
            inValue.duracion = duracion;
            inValue.indicacion = indicacion;
            inValue.cantidad = cantidad;
            inValue.activo = activo;
            return ((SoftPetBussiness.DetalleRecetaClient.DetallesReceta)(this)).modificar_detallerecetaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.DetalleRecetaClient.eliminar_detallerecetaResponse SoftPetBussiness.DetalleRecetaClient.DetallesReceta.eliminar_detallereceta(SoftPetBussiness.DetalleRecetaClient.eliminar_detallerecetaRequest request) {
            return base.Channel.eliminar_detallereceta(request);
        }
        
        public int eliminar_detallereceta(int detalleRecetaId) {
            SoftPetBussiness.DetalleRecetaClient.eliminar_detallerecetaRequest inValue = new SoftPetBussiness.DetalleRecetaClient.eliminar_detallerecetaRequest();
            inValue.detalleRecetaId = detalleRecetaId;
            SoftPetBussiness.DetalleRecetaClient.eliminar_detallerecetaResponse retVal = ((SoftPetBussiness.DetalleRecetaClient.DetallesReceta)(this)).eliminar_detallereceta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.DetalleRecetaClient.eliminar_detallerecetaResponse> SoftPetBussiness.DetalleRecetaClient.DetallesReceta.eliminar_detallerecetaAsync(SoftPetBussiness.DetalleRecetaClient.eliminar_detallerecetaRequest request) {
            return base.Channel.eliminar_detallerecetaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.DetalleRecetaClient.eliminar_detallerecetaResponse> eliminar_detallerecetaAsync(int detalleRecetaId) {
            SoftPetBussiness.DetalleRecetaClient.eliminar_detallerecetaRequest inValue = new SoftPetBussiness.DetalleRecetaClient.eliminar_detallerecetaRequest();
            inValue.detalleRecetaId = detalleRecetaId;
            return ((SoftPetBussiness.DetalleRecetaClient.DetallesReceta)(this)).eliminar_detallerecetaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.DetalleRecetaClient.obtener_por_idResponse SoftPetBussiness.DetalleRecetaClient.DetallesReceta.obtener_por_id(SoftPetBussiness.DetalleRecetaClient.obtener_por_idRequest request) {
            return base.Channel.obtener_por_id(request);
        }
        
        public SoftPetBussiness.DetalleRecetaClient.detalleRecetaDto obtener_por_id(int detalleRecetaId) {
            SoftPetBussiness.DetalleRecetaClient.obtener_por_idRequest inValue = new SoftPetBussiness.DetalleRecetaClient.obtener_por_idRequest();
            inValue.detalleRecetaId = detalleRecetaId;
            SoftPetBussiness.DetalleRecetaClient.obtener_por_idResponse retVal = ((SoftPetBussiness.DetalleRecetaClient.DetallesReceta)(this)).obtener_por_id(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.DetalleRecetaClient.obtener_por_idResponse> SoftPetBussiness.DetalleRecetaClient.DetallesReceta.obtener_por_idAsync(SoftPetBussiness.DetalleRecetaClient.obtener_por_idRequest request) {
            return base.Channel.obtener_por_idAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.DetalleRecetaClient.obtener_por_idResponse> obtener_por_idAsync(int detalleRecetaId) {
            SoftPetBussiness.DetalleRecetaClient.obtener_por_idRequest inValue = new SoftPetBussiness.DetalleRecetaClient.obtener_por_idRequest();
            inValue.detalleRecetaId = detalleRecetaId;
            return ((SoftPetBussiness.DetalleRecetaClient.DetallesReceta)(this)).obtener_por_idAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.DetalleRecetaClient.listar_todosResponse SoftPetBussiness.DetalleRecetaClient.DetallesReceta.listar_todos(SoftPetBussiness.DetalleRecetaClient.listar_todosRequest request) {
            return base.Channel.listar_todos(request);
        }
        
        public SoftPetBussiness.DetalleRecetaClient.detalleRecetaDto[] listar_todos() {
            SoftPetBussiness.DetalleRecetaClient.listar_todosRequest inValue = new SoftPetBussiness.DetalleRecetaClient.listar_todosRequest();
            SoftPetBussiness.DetalleRecetaClient.listar_todosResponse retVal = ((SoftPetBussiness.DetalleRecetaClient.DetallesReceta)(this)).listar_todos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.DetalleRecetaClient.listar_todosResponse> SoftPetBussiness.DetalleRecetaClient.DetallesReceta.listar_todosAsync(SoftPetBussiness.DetalleRecetaClient.listar_todosRequest request) {
            return base.Channel.listar_todosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.DetalleRecetaClient.listar_todosResponse> listar_todosAsync() {
            SoftPetBussiness.DetalleRecetaClient.listar_todosRequest inValue = new SoftPetBussiness.DetalleRecetaClient.listar_todosRequest();
            return ((SoftPetBussiness.DetalleRecetaClient.DetallesReceta)(this)).listar_todosAsync(inValue);
        }
    }
}
