USE petmedicalcare;
GO

-- ROLES
SELECT TOP (100) * FROM dbo.ROLES ORDER BY ROL_ID;
GO

-- USUARIOS
SELECT TOP (100) * FROM dbo.USUARIOS ORDER BY USUARIO_ID;
GO

-- PERSONAS
SELECT TOP (100) * FROM dbo.PERSONAS ORDER BY PERSONA_ID;
GO

-- TIPOS_SERVICIO
SELECT TOP (100) * FROM dbo.TIPOS_SERVICIO ORDER BY TIPO_SERVICIO_ID;
GO

-- TIPOS_PRODUCTO
SELECT TOP (100) * FROM dbo.TIPOS_PRODUCTO ORDER BY TIPO_PRODUCTO_ID;
GO

-- TIPOS_DOCUMENTO
SELECT TOP (100) * FROM dbo.TIPOS_DOCUMENTO ORDER BY TIPO_DOCUMENTO_ID;
GO

-- MASCOTAS
SELECT TOP (100) * FROM dbo.MASCOTAS ORDER BY MASCOTA_ID;
GO

-- VETERINARIOS
SELECT TOP (100) * FROM dbo.VETERINARIOS ORDER BY VETERINARIO_ID;
GO

-- SERVICIOS
SELECT TOP (100) * FROM dbo.SERVICIOS ORDER BY SERVICIO_ID;
GO

-- PRODUCTOS
SELECT TOP (100) * FROM dbo.PRODUCTOS ORDER BY PRODUCTO_ID;
GO

-- CITAS_ATENCION
SELECT TOP (100) * FROM dbo.CITAS_ATENCION ORDER BY CITA_ID;
GO

-- RECETAS_MEDICA
SELECT TOP (100) * FROM dbo.RECETAS_MEDICA ORDER BY RECETAS_MEDICA_ID;
GO

-- ROLES_USUARIO
SELECT TOP (100) * FROM dbo.ROLES_USUARIO ORDER BY ROL_USUARIO_ID;
GO

-- DETALLES_SERVICIO
SELECT TOP (100) * FROM dbo.DETALLES_SERVICIO ORDER BY DETALLE_SERVICIO_ID;
GO

-- DOCUMENTOS_DE_PAGO
SELECT TOP (100) * FROM dbo.DOCUMENTOS_DE_PAGO ORDER BY DOCUMENTO_DE_PAGO_ID;
GO

-- DETALLES_RECETA
SELECT TOP (100) * FROM dbo.DETALLES_RECETA ORDER BY DETALLE_RECETA_ID;
GO

-- DETALLES_DOCUMENTO_DE_PAGO
SELECT TOP (100) * FROM dbo.DETALLES_DOCUMENTO_DE_PAGO ORDER BY DDDP_ID;
GO
