USE petmedicalcare;

-- =========================
-- USUARIOS  (6)
-- =========================
INSERT INTO USUARIOS (USERNAME, PASSWORD, CORREO, ACTIVO, USUARIO_CREADOR, FECHA_CREACION) VALUES
('admin',         '$2b$12$adminhashxxxxxxxxxxxxxxxxxxxxx', 'admin@demo.com',         1, 'system', '2025-10-25 09:00:00'),
('vet.ana',       '$2b$12$anahashxxxxxxxxxxxxxxxxxxxxxxx', 'ana.vet@demo.com',       1, 'admin',  '2025-10-25 09:10:00'),
('vet.juan',      '$2b$12$juanhashxxxxxxxxxxxxxxxxxxxxxx', 'juan.vet@demo.com',      1, 'admin',  '2025-10-25 09:20:00'),
('recepcion',     '$2b$12$recephashxxxxxxxxxxxxxxxxxxxxx', 'recep@demo.com',         1, 'admin',  '2025-10-25 09:30:00'),
('cliente.luisa', '$2b$12$luisahashxxxxxxxxxxxxxxxxxxxxx', 'luisa@demo.com',         1, 'admin',  '2025-10-25 09:40:00'),
('cliente.carlos','$2b$12$carloshashxxxxxxxxxxxxxxxxxxxxx','carlos@demo.com',        1, 'admin',  '2025-10-25 09:50:00');

-- =========================
-- PERSONAS  (6)
-- =========================
INSERT INTO PERSONAS (USUARIO_ID, NOMBRE, DIRECCION, TELEFONO, SEXO, NRO_DOCUMENTO, RUC, TIPO_DOCUMENTO, ACTIVO) VALUES
((SELECT USUARIO_ID FROM USUARIOS WHERE USERNAME='admin'),          'Administrador General','Av. Principal 123','900111111','O','00000001',NULL,'DNI',1),
((SELECT USUARIO_ID FROM USUARIOS WHERE USERNAME='vet.ana'),        'Ana Pérez',            'Jr. Los Cedros 456','900222222','F','45678912',NULL,'DNI',1),
((SELECT USUARIO_ID FROM USUARIOS WHERE USERNAME='vet.juan'),       'Juan García',          'Calle Sol 789',     '900333333','M','12345678',NULL,'DNI',1),
((SELECT USUARIO_ID FROM USUARIOS WHERE USERNAME='recepcion'),      'Rosa Díaz',            'Av. Norte 555',     '900444444','F','87654321',NULL,'DNI',1),
((SELECT USUARIO_ID FROM USUARIOS WHERE USERNAME='cliente.luisa'),  'Luisa Romero',         'Psj. Sur 321',      '900555555','F','11223344',NULL,'DNI',1),
((SELECT USUARIO_ID FROM USUARIOS WHERE USERNAME='cliente.carlos'), 'Carlos Torres',        'Mz A Lt 10',        '900666666','M','44332211',NULL,'DNI',1);

-- =========================
-- MASCOTAS  (5)
-- =========================
INSERT INTO MASCOTAS (PERSONA_ID, NOMBRE, ESPECIE, SEXO, RAZA, COLOR, FECHA_DEFUNCION, ACTIVO) VALUES
((SELECT PERSONA_ID FROM PERSONAS WHERE NOMBRE='Luisa Romero'), 'Firulais','Perro','M','Mestizo','Marrón',NULL,1),
((SELECT PERSONA_ID FROM PERSONAS WHERE NOMBRE='Luisa Romero'), 'Misha',   'Gato', 'F','Siames', 'Gris',  NULL,1),
((SELECT PERSONA_ID FROM PERSONAS WHERE NOMBRE='Carlos Torres'),'Rocky',   'Perro','M','Pitbull','Negro', NULL,1),
((SELECT PERSONA_ID FROM PERSONAS WHERE NOMBRE='Carlos Torres'),'Luna',    'Gato', 'F','Criollo','Blanco',NULL,1),
((SELECT PERSONA_ID FROM PERSONAS WHERE NOMBRE='Carlos Torres'),'Paco',    'Ave',  'O','Loro',   'Verde', NULL,1);

-- =========================
-- VETERINARIOS  (2)
-- (EstadoVeterinario: ACTIVO, INACTIVO, SUSPENDIDO)
-- =========================
INSERT INTO VETERINARIOS (PERSONA_ID, FECHA_DE_CONTRATACION, ESTADO, ESPECIALIDAD, ACTIVO) VALUES
((SELECT PERSONA_ID FROM PERSONAS WHERE NOMBRE='Ana Pérez'),  '2025-09-01','ACTIVO',   'Cirugía',      1),
((SELECT PERSONA_ID FROM PERSONAS WHERE NOMBRE='Juan García'),'2025-09-15','INACTIVO', 'Dermatología', 1);

-- =========================
-- ROLES  (4)
-- =========================
INSERT INTO ROLES (NOMBRE, ACTIVO) VALUES
('ADMIN',1),('VET',1),('RECEPCION',1),('CLIENTE',1);

-- =========================
-- ROLES_USUARIO  (6)
-- =========================
INSERT INTO ROLES_USUARIO (ROL_ID, USUARIO_ID, ACTIVO) VALUES
((SELECT ROL_ID FROM ROLES WHERE NOMBRE='ADMIN'),     (SELECT USUARIO_ID FROM USUARIOS WHERE USERNAME='admin'),         1),
((SELECT ROL_ID FROM ROLES WHERE NOMBRE='VET'),       (SELECT USUARIO_ID FROM USUARIOS WHERE USERNAME='vet.ana'),       1),
((SELECT ROL_ID FROM ROLES WHERE NOMBRE='VET'),       (SELECT USUARIO_ID FROM USUARIOS WHERE USERNAME='vet.juan'),      1),
((SELECT ROL_ID FROM ROLES WHERE NOMBRE='RECEPCION'), (SELECT USUARIO_ID FROM USUARIOS WHERE USERNAME='recepcion'),     1),
((SELECT ROL_ID FROM ROLES WHERE NOMBRE='CLIENTE'),   (SELECT USUARIO_ID FROM USUARIOS WHERE USERNAME='cliente.luisa'), 1),
((SELECT ROL_ID FROM ROLES WHERE NOMBRE='CLIENTE'),   (SELECT USUARIO_ID FROM USUARIOS WHERE USERNAME='cliente.carlos'),1);

-- =========================
-- METODOS_DE_PAGO  (4)
-- (TipoMetodoPago: EFECTIVO, TRANSFERENCIA, YAPE, PLIN)
-- =========================
INSERT INTO METODOS_DE_PAGO (NOMBRE, ACTIVO) VALUES
('EFECTIVO',1),('TRANSFERENCIA',1),('YAPE',1),('PLIN',1);

-- =========================
-- TIPOS_PRODUCTO  (3)
-- =========================
INSERT INTO TIPOS_PRODUCTO (NOMBRE, DESCRIPCION, ACTIVO) VALUES
('MEDICAMENTO','Fármacos veterinarios',1),
('ACCESORIO','Accesorios varios',1),
('ALIMENTO','Alimento para mascotas',1);

-- =========================
-- PRODUCTOS  (6)
-- =========================
INSERT INTO PRODUCTOS (TIPO_PRODUCTO_ID, NOMBRE, PRESENTACION, PRECIO_UNITARIO, STOCK, ACTIVO, USUARIO_CREADOR, FECHA_CREACION) VALUES
((SELECT TIPO_PRODUCTO_ID FROM TIPOS_PRODUCTO WHERE NOMBRE='MEDICAMENTO'),'Amoxicilina 500mg','Blíster x10',   25.00,100,1,'admin','2025-10-26 10:00:00'),
((SELECT TIPO_PRODUCTO_ID FROM TIPOS_PRODUCTO WHERE NOMBRE='MEDICAMENTO'),'Antipulgas Spot-On','Pipeta 2.5 ml',35.00, 80,1,'admin','2025-10-26 10:05:00'),
((SELECT TIPO_PRODUCTO_ID FROM TIPOS_PRODUCTO WHERE NOMBRE='ACCESORIO'),  'Collar isabelino',  'Talla M',       20.00, 40,1,'admin','2025-10-26 10:10:00'),
((SELECT TIPO_PRODUCTO_ID FROM TIPOS_PRODUCTO WHERE NOMBRE='ALIMENTO'),   'Comida premium',    'Bolsa 2 kg',    60.00, 50,1,'admin','2025-10-26 10:15:00'),
((SELECT TIPO_PRODUCTO_ID FROM TIPOS_PRODUCTO WHERE NOMBRE='ACCESORIO'),  'Jeringa 5 ml',      'Unidad',         2.50,200,1,'admin','2025-10-26 10:20:00'),
((SELECT TIPO_PRODUCTO_ID FROM TIPOS_PRODUCTO WHERE NOMBRE='MEDICAMENTO'),'Vitaminas Pet',     'Frasco 30 caps',28.00, 60,1,'admin','2025-10-26 10:25:00');

-- =========================
-- TIPOS_SERVICIO  (3)
-- =========================
INSERT INTO TIPOS_SERVICIO (NOMBRE, DESCRIPCION, ACTIVO) VALUES
('CONSULTA','Consultas generales',1),
('VACUNACION','Vacunaciones',1),
('CIRUGIA','Procedimientos Qx',1);

-- =========================
-- SERVICIOS  (6)
-- (Estado texto: ACTIVO, INACTIVO, SUSPENDIDO)
-- =========================
INSERT INTO SERVICIOS (TIPO_SERVICIO_ID, NOMBRE, DESCRIPCION, COSTO, ESTADO, ACTIVO, USUARIO_CREADOR, FECHA_CREACION) VALUES
((SELECT TIPO_SERVICIO_ID FROM TIPOS_SERVICIO WHERE NOMBRE='CONSULTA'),  'Consulta general',       'Evaluación clínica básica',    50.00,'ACTIVO',    1,'admin','2025-10-26 11:00:00'),
((SELECT TIPO_SERVICIO_ID FROM TIPOS_SERVICIO WHERE NOMBRE='VACUNACION'),'Vacunación antirrábica', 'Vacuna antirrábica canina',    80.00,'ACTIVO',    1,'admin','2025-10-26 11:05:00'),
((SELECT TIPO_SERVICIO_ID FROM TIPOS_SERVICIO WHERE NOMBRE='CIRUGIA'),   'Esterilización felina',  'Cirugía de esterilización',   300.00,'ACTIVO',    1,'admin','2025-10-26 11:10:00'),
((SELECT TIPO_SERVICIO_ID FROM TIPOS_SERVICIO WHERE NOMBRE='VACUNACION'),'Desparasitación',        'Tratamiento antiparasitario',  60.00,'INACTIVO',  1,'admin','2025-10-26 11:15:00'),
((SELECT TIPO_SERVICIO_ID FROM TIPOS_SERVICIO WHERE NOMBRE='CONSULTA'),  'Consulta dermatológica', 'Evaluación de piel y pelaje',  70.00,'ACTIVO',    1,'admin','2025-10-26 11:20:00'),
((SELECT TIPO_SERVICIO_ID FROM TIPOS_SERVICIO WHERE NOMBRE='CIRUGIA'),   'Cirugía menor',          'Procedimiento Qx ambulatorio',450.00,'SUSPENDIDO',1,'admin','2025-10-26 11:25:00');

-- =========================
-- CITAS_ATENCION  (6)
-- (EstadoCita: PROGRAMADA, ATENDIDA, CANCELADA)
-- =========================
INSERT INTO CITAS_ATENCION
(VETERINARIO_ID, MASCOTA_ID, FECHA_REGISTRO, FECHA_HORA_INICIO, FECHA_HORA_FIN, PESO_MASCOTA, MONTO, ESTADO_CITA, OBSERVACION, ACTIVO)
VALUES
((SELECT V.VETERINARIO_ID FROM VETERINARIOS V JOIN PERSONAS P ON P.PERSONA_ID=V.PERSONA_ID WHERE P.NOMBRE='Ana Pérez'),
 (SELECT MASCOTA_ID FROM MASCOTAS WHERE NOMBRE='Firulais'),
 '2025-10-27','2025-10-28 09:00:00','2025-10-28 09:30:00',12.50, 50.00,'ATENDIDA','Control general',1),

((SELECT V.VETERINARIO_ID FROM VETERINARIOS V JOIN PERSONAS P ON P.PERSONA_ID=V.PERSONA_ID WHERE P.NOMBRE='Juan García'),
 (SELECT MASCOTA_ID FROM MASCOTAS WHERE NOMBRE='Misha'),
 '2025-10-28','2025-10-29 10:00:00','2025-10-29 10:45:00', 4.20,150.00,'ATENDIDA','Vacuna + dermo',1),

((SELECT V.VETERINARIO_ID FROM VETERINARIOS V JOIN PERSONAS P ON P.PERSONA_ID=V.PERSONA_ID WHERE P.NOMBRE='Ana Pérez'),
 (SELECT MASCOTA_ID FROM MASCOTAS WHERE NOMBRE='Rocky'),
 '2025-10-30','2025-11-01 11:00:00','2025-11-01 11:30:00',22.00, 50.00,'PROGRAMADA','Consulta previa',1),

((SELECT V.VETERINARIO_ID FROM VETERINARIOS V JOIN PERSONAS P ON P.PERSONA_ID=V.PERSONA_ID WHERE P.NOMBRE='Juan García'),
 (SELECT MASCOTA_ID FROM MASCOTAS WHERE NOMBRE='Luna'),
 '2025-10-30','2025-11-02 12:00:00','2025-11-02 12:10:00', 3.60,  0.00,'CANCELADA','Cliente canceló',1),

((SELECT V.VETERINARIO_ID FROM VETERINARIOS V JOIN PERSONAS P ON P.PERSONA_ID=V.PERSONA_ID WHERE P.NOMBRE='Ana Pérez'),
 (SELECT MASCOTA_ID FROM MASCOTAS WHERE NOMBRE='Paco'),
 '2025-10-31','2025-11-03 14:00:00','2025-11-03 14:30:00', 1.10, 50.00,'PROGRAMADA','Chequeo general',1),

((SELECT V.VETERINARIO_ID FROM VETERINARIOS V JOIN PERSONAS P ON P.PERSONA_ID=V.PERSONA_ID WHERE P.NOMBRE='Juan García'),
 (SELECT MASCOTA_ID FROM MASCOTAS WHERE NOMBRE='Firulais'),
 '2025-11-02','2025-11-03 15:00:00','2025-11-03 15:40:00',12.70, 60.00,'ATENDIDA','Desparasitación',1);

-- =========================
-- HORARIOS_LABORALES  (6)
-- (EstadoLaboral: DISPONIBLE, NO_DISPONIBLE)
-- =========================
INSERT INTO HORARIOS_LABORALES (VETERINARIO_ID, FECHA, ESTADO, HORA_INICIO, HORA_FIN, ACTIVO) VALUES
((SELECT V.VETERINARIO_ID FROM VETERINARIOS V JOIN PERSONAS P ON P.PERSONA_ID=V.PERSONA_ID WHERE P.NOMBRE='Ana Pérez'),'2025-11-01','DISPONIBLE',    '2025-11-01 09:00:00','2025-11-01 17:00:00',1),
((SELECT V.VETERINARIO_ID FROM VETERINARIOS V JOIN PERSONAS P ON P.PERSONA_ID=V.PERSONA_ID WHERE P.NOMBRE='Ana Pérez'),'2025-11-02','NO_DISPONIBLE','2025-11-02 09:00:00','2025-11-02 17:00:00',1),
((SELECT V.VETERINARIO_ID FROM VETERINARIOS V JOIN PERSONAS P ON P.PERSONA_ID=V.PERSONA_ID WHERE P.NOMBRE='Ana Pérez'),'2025-11-03','DISPONIBLE',    '2025-11-03 09:00:00','2025-11-03 17:00:00',1),
((SELECT V.VETERINARIO_ID FROM VETERINARIOS V JOIN PERSONAS P ON P.PERSONA_ID=V.PERSONA_ID WHERE P.NOMBRE='Juan García'),'2025-11-01','DISPONIBLE',  '2025-11-01 09:00:00','2025-11-01 17:00:00',1),
((SELECT V.VETERINARIO_ID FROM VETERINARIOS V JOIN PERSONAS P ON P.PERSONA_ID=V.PERSONA_ID WHERE P.NOMBRE='Juan García'),'2025-11-02','DISPONIBLE',  '2025-11-02 09:00:00','2025-11-02 17:00:00',1),
((SELECT V.VETERINARIO_ID FROM VETERINARIOS V JOIN PERSONAS P ON P.PERSONA_ID=V.PERSONA_ID WHERE P.NOMBRE='Juan García'),'2025-11-03','DISPONIBLE',  '2025-11-03 09:00:00','2025-11-03 17:00:00',1);

-- =========================
-- DOCUMENTOS_DE_PAGO  (4)
-- (TipoDocumentoDePago: BOLETA, FACTURA; EstadoDocumentoDePago: EMITIDO, PAGADO, ANULADO)
-- =========================
INSERT INTO DOCUMENTOS_DE_PAGO
(METODO_DE_PAGO_ID, PERSONA_ID, TIPO_DOCUMENTO, SERIE, NUMERO, FECHA_EMISION, ESTADO, SUBTOTAL, IGV_TOTAL, TOTAL, ACTIVO) VALUES
((SELECT METODO_DE_PAGO_ID FROM METODOS_DE_PAGO WHERE NOMBRE='EFECTIVO'),
 (SELECT PERSONA_ID FROM PERSONAS WHERE NOMBRE='Luisa Romero'),
 'BOLETA','B001','00000001','2025-10-30','PAGADO', 110.00, 19.80,129.80,1),

((SELECT METODO_DE_PAGO_ID FROM METODOS_DE_PAGO WHERE NOMBRE='TRANSFERENCIA'),
 (SELECT PERSONA_ID FROM PERSONAS WHERE NOMBRE='Luisa Romero'),
 'FACTURA','F001','00000001','2025-10-30','EMITIDO',115.00, 20.70,135.70,1),

((SELECT METODO_DE_PAGO_ID FROM METODOS_DE_PAGO WHERE NOMBRE='YAPE'),
 (SELECT PERSONA_ID FROM PERSONAS WHERE NOMBRE='Carlos Torres'),
 'BOLETA','B001','00000002','2025-11-01','ANULADO', 70.00, 12.60, 82.60,1),

((SELECT METODO_DE_PAGO_ID FROM METODOS_DE_PAGO WHERE NOMBRE='PLIN'),
 (SELECT PERSONA_ID FROM PERSONAS WHERE NOMBRE='Carlos Torres'),
 'FACTURA','F001','00000002','2025-11-03','PAGADO',  50.00,  9.00, 59.00,1);

-- =========================
-- DETALLES_SERVICIO  (6)
-- =========================
INSERT INTO DETALLES_SERVICIO (CITA_ID, SERVICIO_ID, DESCRIPCION, COSTO, ACTIVO) VALUES
((SELECT CITA_ID FROM CITAS_ATENCION WHERE FECHA_HORA_INICIO='2025-10-28 09:00:00'),
 (SELECT SERVICIO_ID FROM SERVICIOS WHERE NOMBRE='Consulta general'),'Consulta general',50.00,1),

((SELECT CITA_ID FROM CITAS_ATENCION WHERE FECHA_HORA_INICIO='2025-10-29 10:00:00'),
 (SELECT SERVICIO_ID FROM SERVICIOS WHERE NOMBRE='Vacunación antirrábica'),'Vacunación antirrábica',80.00,1),

((SELECT CITA_ID FROM CITAS_ATENCION WHERE FECHA_HORA_INICIO='2025-10-29 10:00:00'),
 (SELECT SERVICIO_ID FROM SERVICIOS WHERE NOMBRE='Consulta dermatológica'),'Consulta dermatológica',70.00,1),

((SELECT CITA_ID FROM CITAS_ATENCION WHERE FECHA_HORA_INICIO='2025-11-03 15:00:00'),
 (SELECT SERVICIO_ID FROM SERVICIOS WHERE NOMBRE='Desparasitación'),'Desparasitación',60.00,1),

((SELECT CITA_ID FROM CITAS_ATENCION WHERE FECHA_HORA_INICIO='2025-11-01 11:00:00'),
 (SELECT SERVICIO_ID FROM SERVICIOS WHERE NOMBRE='Consulta general'),'Consulta programada',50.00,1),

((SELECT CITA_ID FROM CITAS_ATENCION WHERE FECHA_HORA_INICIO='2025-11-03 14:00:00'),
 (SELECT SERVICIO_ID FROM SERVICIOS WHERE NOMBRE='Consulta general'),'Consulta programada',50.00,1);

-- =========================
-- RECETAS_MEDICAS  (3)
-- =========================
INSERT INTO RECETAS_MEDICAS (CITA_ID, FECHA_EMISION, VIGENCIA_HASTA, DIAGNOSTICO, OBSERVACIONES, ACTIVO) VALUES
((SELECT CITA_ID FROM CITAS_ATENCION WHERE FECHA_HORA_INICIO='2025-10-28 09:00:00'),'2025-10-28',NULL,         'Gastritis leve','Reposo y control en 7 días',1),
((SELECT CITA_ID FROM CITAS_ATENCION WHERE FECHA_HORA_INICIO='2025-10-29 10:00:00'),'2025-10-29','2025-11-12','Dermatitis','Baños medicados',1),
((SELECT CITA_ID FROM CITAS_ATENCION WHERE FECHA_HORA_INICIO='2025-11-03 15:00:00'),'2025-11-03','2025-11-10','Parasitosis','Completar tratamiento',1);

-- =========================
-- DETALLES_RECETA  (6)
-- =========================
INSERT INTO DETALLES_RECETA
(RECETA_MEDICA_ID, DESCRIPCION_MEDICAMENTO, PRESENTACION, VIA_ADMINISTRACION, DOSIS, FRECUENCIA, DURACION, INDICACION, CANTIDAD, ACTIVO) VALUES
((SELECT RECETA_MEDICA_ID FROM RECETAS_MEDICAS WHERE CITA_ID=(SELECT CITA_ID FROM CITAS_ATENCION WHERE FECHA_HORA_INICIO='2025-10-28 09:00:00')),
 'Omeprazol','10 mg','ORAL','1 tab','cada 12 h','7 días','Tomar con comida','14',1),

((SELECT RECETA_MEDICA_ID FROM RECETAS_MEDICAS WHERE CITA_ID=(SELECT CITA_ID FROM CITAS_ATENCION WHERE FECHA_HORA_INICIO='2025-10-28 09:00:00')),
 'Sucralfato','1 g/5 ml','ORAL','5 ml','cada 8 h','7 días','Agitar antes','1 frasco',1),

((SELECT RECETA_MEDICA_ID FROM RECETAS_MEDICAS WHERE CITA_ID=(SELECT CITA_ID FROM CITAS_ATENCION WHERE FECHA_HORA_INICIO='2025-10-29 10:00:00')),
 'Corticoide tópico','Crema','TOPICA','capa fina','2/día','10 días','Evitar lamido','1 tubo',1),

((SELECT RECETA_MEDICA_ID FROM RECETAS_MEDICAS WHERE CITA_ID=(SELECT CITA_ID FROM CITAS_ATENCION WHERE FECHA_HORA_INICIO='2025-10-29 10:00:00')),
 'Antibiótico','250 mg','ORAL','1 tab','cada 12 h','7 días','Completar dosis','14',1),

((SELECT RECETA_MEDICA_ID FROM RECETAS_MEDICAS WHERE CITA_ID=(SELECT CITA_ID FROM CITAS_ATENCION WHERE FECHA_HORA_INICIO='2025-11-03 15:00:00')),
 'Antiparasitario','Susp.','ORAL','según peso','Única','1 día','Repetir en 15 d','1',1),

((SELECT RECETA_MEDICA_ID FROM RECETAS_MEDICAS WHERE CITA_ID=(SELECT CITA_ID FROM CITAS_ATENCION WHERE FECHA_HORA_INICIO='2025-11-03 15:00:00')),
 'Probiótico','Caps','ORAL','1 cap','al día','10 días','—','10',1);

-- =========================
-- DETALLES_DOCUMENTO_DE_PAGO  (6)
-- =========================
INSERT INTO DETALLES_DOCUMENTO_DE_PAGO
(DOCUMENTO_DE_PAGO_ID, SERVICIO_ID, PRODUCTO_ID, NRO_ITEM, DESCRIPCION, CANTIDAD, PRECIO_UNITARIO, VALOR_VENTA, ACTIVO) VALUES
((SELECT DOCUMENTO_DE_PAGO_ID FROM DOCUMENTOS_DE_PAGO WHERE SERIE='B001' AND NUMERO='00000001'),
 (SELECT SERVICIO_ID FROM SERVICIOS WHERE NOMBRE='Consulta general'), NULL, 1,'Consulta general',      1, 50.00, 50.00,1),

((SELECT DOCUMENTO_DE_PAGO_ID FROM DOCUMENTOS_DE_PAGO WHERE SERIE='B001' AND NUMERO='00000001'),
 NULL, (SELECT PRODUCTO_ID FROM PRODUCTOS WHERE NOMBRE='Comida premium'), 2,'Comida premium 2 kg',1, 60.00, 60.00,1),

((SELECT DOCUMENTO_DE_PAGO_ID FROM DOCUMENTOS_DE_PAGO WHERE SERIE='F001' AND NUMERO='00000001'),
 (SELECT SERVICIO_ID FROM SERVICIOS WHERE NOMBRE='Vacunación antirrábica'), NULL, 1,'Vacunación antirrábica',1,80.00,80.00,1),

((SELECT DOCUMENTO_DE_PAGO_ID FROM DOCUMENTOS_DE_PAGO WHERE SERIE='F001' AND NUMERO='00000001'),
 NULL, (SELECT PRODUCTO_ID FROM PRODUCTOS WHERE NOMBRE='Antipulgas Spot-On'), 2,'Antipulgas Spot-On',1,35.00,35.00,1),

((SELECT DOCUMENTO_DE_PAGO_ID FROM DOCUMENTOS_DE_PAGO WHERE SERIE='B001' AND NUMERO='00000002'),
 (SELECT SERVICIO_ID FROM SERVICIOS WHERE NOMBRE='Consulta dermatológica'), NULL, 1,'Consulta dermatológica',1,70.00,70.00,1),

((SELECT DOCUMENTO_DE_PAGO_ID FROM DOCUMENTOS_DE_PAGO WHERE SERIE='F001' AND NUMERO='00000002'),
 NULL, (SELECT PRODUCTO_ID FROM PRODUCTOS WHERE NOMBRE='Amoxicilina 500mg'), 1,'Amoxicilina 500mg',2,25.00,50.00,1);
