//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPetBussiness.MascotaClient {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/")]
    public partial class IOException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/")]
    public partial class date : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/")]
    public partial class usuarioDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private string correoField;
        
        private date fechaCreacionField;
        
        private date fechaModificacionField;
        
        private string passwordField;
        
        private string usernameField;
        
        private string usuarioCreadorField;
        
        private int usuarioIdField;
        
        private bool usuarioIdFieldSpecified;
        
        private string usuarioModificadorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public date fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public date fechaModificacion {
            get {
                return this.fechaModificacionField;
            }
            set {
                this.fechaModificacionField = value;
                this.RaisePropertyChanged("fechaModificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string usuarioCreador {
            get {
                return this.usuarioCreadorField;
            }
            set {
                this.usuarioCreadorField = value;
                this.RaisePropertyChanged("usuarioCreador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int usuarioId {
            get {
                return this.usuarioIdField;
            }
            set {
                this.usuarioIdField = value;
                this.RaisePropertyChanged("usuarioId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usuarioIdSpecified {
            get {
                return this.usuarioIdFieldSpecified;
            }
            set {
                this.usuarioIdFieldSpecified = value;
                this.RaisePropertyChanged("usuarioIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string usuarioModificador {
            get {
                return this.usuarioModificadorField;
            }
            set {
                this.usuarioModificadorField = value;
                this.RaisePropertyChanged("usuarioModificador");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/")]
    public partial class personaDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private string direccionField;
        
        private string nombreField;
        
        private int nroDocumentoField;
        
        private bool nroDocumentoFieldSpecified;
        
        private int personaIdField;
        
        private bool personaIdFieldSpecified;
        
        private int rucField;
        
        private bool rucFieldSpecified;
        
        private sexo sexoField;
        
        private bool sexoFieldSpecified;
        
        private string telefonoField;
        
        private string tipoDocumentoField;
        
        private usuarioDto usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int nroDocumento {
            get {
                return this.nroDocumentoField;
            }
            set {
                this.nroDocumentoField = value;
                this.RaisePropertyChanged("nroDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nroDocumentoSpecified {
            get {
                return this.nroDocumentoFieldSpecified;
            }
            set {
                this.nroDocumentoFieldSpecified = value;
                this.RaisePropertyChanged("nroDocumentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int personaId {
            get {
                return this.personaIdField;
            }
            set {
                this.personaIdField = value;
                this.RaisePropertyChanged("personaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool personaIdSpecified {
            get {
                return this.personaIdFieldSpecified;
            }
            set {
                this.personaIdFieldSpecified = value;
                this.RaisePropertyChanged("personaIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int ruc {
            get {
                return this.rucField;
            }
            set {
                this.rucField = value;
                this.RaisePropertyChanged("ruc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rucSpecified {
            get {
                return this.rucFieldSpecified;
            }
            set {
                this.rucFieldSpecified = value;
                this.RaisePropertyChanged("rucSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public sexo sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sexoSpecified {
            get {
                return this.sexoFieldSpecified;
            }
            set {
                this.sexoFieldSpecified = value;
                this.RaisePropertyChanged("sexoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public usuarioDto usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/")]
    public enum sexo {
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        O,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/")]
    public partial class mascotaDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private string colorField;
        
        private string especieField;
        
        private System.DateTime fechaDefuncionField;
        
        private bool fechaDefuncionFieldSpecified;
        
        private int mascotaIdField;
        
        private bool mascotaIdFieldSpecified;
        
        private string nombreField;
        
        private personaDto personaField;
        
        private string razaField;
        
        private string sexoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
                this.RaisePropertyChanged("color");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string especie {
            get {
                return this.especieField;
            }
            set {
                this.especieField = value;
                this.RaisePropertyChanged("especie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaDefuncion {
            get {
                return this.fechaDefuncionField;
            }
            set {
                this.fechaDefuncionField = value;
                this.RaisePropertyChanged("fechaDefuncion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaDefuncionSpecified {
            get {
                return this.fechaDefuncionFieldSpecified;
            }
            set {
                this.fechaDefuncionFieldSpecified = value;
                this.RaisePropertyChanged("fechaDefuncionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int mascotaId {
            get {
                return this.mascotaIdField;
            }
            set {
                this.mascotaIdField = value;
                this.RaisePropertyChanged("mascotaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mascotaIdSpecified {
            get {
                return this.mascotaIdFieldSpecified;
            }
            set {
                this.mascotaIdFieldSpecified = value;
                this.RaisePropertyChanged("mascotaIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public personaDto persona {
            get {
                return this.personaField;
            }
            set {
                this.personaField = value;
                this.RaisePropertyChanged("persona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string raza {
            get {
                return this.razaField;
            }
            set {
                this.razaField = value;
                this.RaisePropertyChanged("raza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/")]
    public partial class InterruptedException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", ConfigurationName="MascotaClient.Mascotas")]
    public interface Mascotas {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://mascota.softpetws.pucp.edu.pe/Mascotas/listar_mascotas_por_personaRequest", ReplyAction="http://mascota.softpetws.pucp.edu.pe/Mascotas/listar_mascotas_por_personaResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftPetBussiness.MascotaClient.IOException), Action="http://mascota.softpetws.pucp.edu.pe/Mascotas/listar_mascotas_por_persona/Fault/I" +
            "OException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftPetBussiness.MascotaClient.InterruptedException), Action="http://mascota.softpetws.pucp.edu.pe/Mascotas/listar_mascotas_por_persona/Fault/I" +
            "nterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.MascotaClient.listar_mascotas_por_personaResponse listar_mascotas_por_persona(SoftPetBussiness.MascotaClient.listar_mascotas_por_personaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mascota.softpetws.pucp.edu.pe/Mascotas/listar_mascotas_por_personaRequest", ReplyAction="http://mascota.softpetws.pucp.edu.pe/Mascotas/listar_mascotas_por_personaResponse" +
            "")]
        System.Threading.Tasks.Task<SoftPetBussiness.MascotaClient.listar_mascotas_por_personaResponse> listar_mascotas_por_personaAsync(SoftPetBussiness.MascotaClient.listar_mascotas_por_personaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://mascota.softpetws.pucp.edu.pe/Mascotas/ListasBusquedaAvanzadaRequest", ReplyAction="http://mascota.softpetws.pucp.edu.pe/Mascotas/ListasBusquedaAvanzadaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.MascotaClient.ListasBusquedaAvanzadaResponse ListasBusquedaAvanzada(SoftPetBussiness.MascotaClient.ListasBusquedaAvanzadaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mascota.softpetws.pucp.edu.pe/Mascotas/ListasBusquedaAvanzadaRequest", ReplyAction="http://mascota.softpetws.pucp.edu.pe/Mascotas/ListasBusquedaAvanzadaResponse")]
        System.Threading.Tasks.Task<SoftPetBussiness.MascotaClient.ListasBusquedaAvanzadaResponse> ListasBusquedaAvanzadaAsync(SoftPetBussiness.MascotaClient.ListasBusquedaAvanzadaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://mascota.softpetws.pucp.edu.pe/Mascotas/listar_mascotas_activasRequest", ReplyAction="http://mascota.softpetws.pucp.edu.pe/Mascotas/listar_mascotas_activasResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftPetBussiness.MascotaClient.IOException), Action="http://mascota.softpetws.pucp.edu.pe/Mascotas/listar_mascotas_activas/Fault/IOExc" +
            "eption", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftPetBussiness.MascotaClient.InterruptedException), Action="http://mascota.softpetws.pucp.edu.pe/Mascotas/listar_mascotas_activas/Fault/Inter" +
            "ruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.MascotaClient.listar_mascotas_activasResponse listar_mascotas_activas(SoftPetBussiness.MascotaClient.listar_mascotas_activasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mascota.softpetws.pucp.edu.pe/Mascotas/listar_mascotas_activasRequest", ReplyAction="http://mascota.softpetws.pucp.edu.pe/Mascotas/listar_mascotas_activasResponse")]
        System.Threading.Tasks.Task<SoftPetBussiness.MascotaClient.listar_mascotas_activasResponse> listar_mascotas_activasAsync(SoftPetBussiness.MascotaClient.listar_mascotas_activasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://mascota.softpetws.pucp.edu.pe/Mascotas/insertar_mascotaRequest", ReplyAction="http://mascota.softpetws.pucp.edu.pe/Mascotas/insertar_mascotaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.MascotaClient.insertar_mascotaResponse insertar_mascota(SoftPetBussiness.MascotaClient.insertar_mascotaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mascota.softpetws.pucp.edu.pe/Mascotas/insertar_mascotaRequest", ReplyAction="http://mascota.softpetws.pucp.edu.pe/Mascotas/insertar_mascotaResponse")]
        System.Threading.Tasks.Task<SoftPetBussiness.MascotaClient.insertar_mascotaResponse> insertar_mascotaAsync(SoftPetBussiness.MascotaClient.insertar_mascotaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://mascota.softpetws.pucp.edu.pe/Mascotas/modificar_mascotaRequest", ReplyAction="http://mascota.softpetws.pucp.edu.pe/Mascotas/modificar_mascotaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.MascotaClient.modificar_mascotaResponse modificar_mascota(SoftPetBussiness.MascotaClient.modificar_mascotaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mascota.softpetws.pucp.edu.pe/Mascotas/modificar_mascotaRequest", ReplyAction="http://mascota.softpetws.pucp.edu.pe/Mascotas/modificar_mascotaResponse")]
        System.Threading.Tasks.Task<SoftPetBussiness.MascotaClient.modificar_mascotaResponse> modificar_mascotaAsync(SoftPetBussiness.MascotaClient.modificar_mascotaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://mascota.softpetws.pucp.edu.pe/Mascotas/eliminar_mascotaRequest", ReplyAction="http://mascota.softpetws.pucp.edu.pe/Mascotas/eliminar_mascotaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.MascotaClient.eliminar_mascotaResponse eliminar_mascota(SoftPetBussiness.MascotaClient.eliminar_mascotaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mascota.softpetws.pucp.edu.pe/Mascotas/eliminar_mascotaRequest", ReplyAction="http://mascota.softpetws.pucp.edu.pe/Mascotas/eliminar_mascotaResponse")]
        System.Threading.Tasks.Task<SoftPetBussiness.MascotaClient.eliminar_mascotaResponse> eliminar_mascotaAsync(SoftPetBussiness.MascotaClient.eliminar_mascotaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://mascota.softpetws.pucp.edu.pe/Mascotas/obtenerPorId_mascotaRequest", ReplyAction="http://mascota.softpetws.pucp.edu.pe/Mascotas/obtenerPorId_mascotaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.MascotaClient.obtenerPorId_mascotaResponse obtenerPorId_mascota(SoftPetBussiness.MascotaClient.obtenerPorId_mascotaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mascota.softpetws.pucp.edu.pe/Mascotas/obtenerPorId_mascotaRequest", ReplyAction="http://mascota.softpetws.pucp.edu.pe/Mascotas/obtenerPorId_mascotaResponse")]
        System.Threading.Tasks.Task<SoftPetBussiness.MascotaClient.obtenerPorId_mascotaResponse> obtenerPorId_mascotaAsync(SoftPetBussiness.MascotaClient.obtenerPorId_mascotaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://mascota.softpetws.pucp.edu.pe/Mascotas/listar_mascotasRequest", ReplyAction="http://mascota.softpetws.pucp.edu.pe/Mascotas/listar_mascotasResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftPetBussiness.MascotaClient.IOException), Action="http://mascota.softpetws.pucp.edu.pe/Mascotas/listar_mascotas/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftPetBussiness.MascotaClient.InterruptedException), Action="http://mascota.softpetws.pucp.edu.pe/Mascotas/listar_mascotas/Fault/InterruptedEx" +
            "ception", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.MascotaClient.listar_mascotasResponse listar_mascotas(SoftPetBussiness.MascotaClient.listar_mascotasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mascota.softpetws.pucp.edu.pe/Mascotas/listar_mascotasRequest", ReplyAction="http://mascota.softpetws.pucp.edu.pe/Mascotas/listar_mascotasResponse")]
        System.Threading.Tasks.Task<SoftPetBussiness.MascotaClient.listar_mascotasResponse> listar_mascotasAsync(SoftPetBussiness.MascotaClient.listar_mascotasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://mascota.softpetws.pucp.edu.pe/Mascotas/VerificarSiLaMascotaTieneInformacio" +
            "nRequest", ReplyAction="http://mascota.softpetws.pucp.edu.pe/Mascotas/VerificarSiLaMascotaTieneInformacio" +
            "nResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.MascotaClient.VerificarSiLaMascotaTieneInformacionResponse VerificarSiLaMascotaTieneInformacion(SoftPetBussiness.MascotaClient.VerificarSiLaMascotaTieneInformacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mascota.softpetws.pucp.edu.pe/Mascotas/VerificarSiLaMascotaTieneInformacio" +
            "nRequest", ReplyAction="http://mascota.softpetws.pucp.edu.pe/Mascotas/VerificarSiLaMascotaTieneInformacio" +
            "nResponse")]
        System.Threading.Tasks.Task<SoftPetBussiness.MascotaClient.VerificarSiLaMascotaTieneInformacionResponse> VerificarSiLaMascotaTieneInformacionAsync(SoftPetBussiness.MascotaClient.VerificarSiLaMascotaTieneInformacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listar_mascotas_por_persona", WrapperNamespace="http://mascota.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class listar_mascotas_por_personaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int personaId;
        
        public listar_mascotas_por_personaRequest() {
        }
        
        public listar_mascotas_por_personaRequest(int personaId) {
            this.personaId = personaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listar_mascotas_por_personaResponse", WrapperNamespace="http://mascota.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class listar_mascotas_por_personaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPetBussiness.MascotaClient.mascotaDto[] @return;
        
        public listar_mascotas_por_personaResponse() {
        }
        
        public listar_mascotas_por_personaResponse(SoftPetBussiness.MascotaClient.mascotaDto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListasBusquedaAvanzada", WrapperNamespace="http://mascota.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class ListasBusquedaAvanzadaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreMascota;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string especie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreDeLaPersona;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int estadoActivo;
        
        public ListasBusquedaAvanzadaRequest() {
        }
        
        public ListasBusquedaAvanzadaRequest(string nombreMascota, string especie, string nombreDeLaPersona, int estadoActivo) {
            this.nombreMascota = nombreMascota;
            this.especie = especie;
            this.nombreDeLaPersona = nombreDeLaPersona;
            this.estadoActivo = estadoActivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListasBusquedaAvanzadaResponse", WrapperNamespace="http://mascota.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class ListasBusquedaAvanzadaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPetBussiness.MascotaClient.mascotaDto[] @return;
        
        public ListasBusquedaAvanzadaResponse() {
        }
        
        public ListasBusquedaAvanzadaResponse(SoftPetBussiness.MascotaClient.mascotaDto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listar_mascotas_activas", WrapperNamespace="http://mascota.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class listar_mascotas_activasRequest {
        
        public listar_mascotas_activasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listar_mascotas_activasResponse", WrapperNamespace="http://mascota.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class listar_mascotas_activasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPetBussiness.MascotaClient.mascotaDto[] @return;
        
        public listar_mascotas_activasResponse() {
        }
        
        public listar_mascotas_activasResponse(SoftPetBussiness.MascotaClient.mascotaDto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertar_mascota", WrapperNamespace="http://mascota.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertar_mascotaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int personaId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string especie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sexo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string raza;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string color;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaDefuncion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool activo;
        
        public insertar_mascotaRequest() {
        }
        
        public insertar_mascotaRequest(int personaId, string nombre, string especie, string sexo, string raza, string color, string fechaDefuncion, bool activo) {
            this.personaId = personaId;
            this.nombre = nombre;
            this.especie = especie;
            this.sexo = sexo;
            this.raza = raza;
            this.color = color;
            this.fechaDefuncion = fechaDefuncion;
            this.activo = activo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertar_mascotaResponse", WrapperNamespace="http://mascota.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertar_mascotaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertar_mascotaResponse() {
        }
        
        public insertar_mascotaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificar_mascota", WrapperNamespace="http://mascota.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificar_mascotaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int mascotaId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int personaId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string especie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sexo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string raza;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string color;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaDefuncion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool activo;
        
        public modificar_mascotaRequest() {
        }
        
        public modificar_mascotaRequest(int mascotaId, int personaId, string nombre, string especie, string sexo, string raza, string color, string fechaDefuncion, bool activo) {
            this.mascotaId = mascotaId;
            this.personaId = personaId;
            this.nombre = nombre;
            this.especie = especie;
            this.sexo = sexo;
            this.raza = raza;
            this.color = color;
            this.fechaDefuncion = fechaDefuncion;
            this.activo = activo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificar_mascotaResponse", WrapperNamespace="http://mascota.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificar_mascotaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificar_mascotaResponse() {
        }
        
        public modificar_mascotaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminar_mascota", WrapperNamespace="http://mascota.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminar_mascotaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int mascotaId;
        
        public eliminar_mascotaRequest() {
        }
        
        public eliminar_mascotaRequest(int mascotaId) {
            this.mascotaId = mascotaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminar_mascotaResponse", WrapperNamespace="http://mascota.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminar_mascotaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminar_mascotaResponse() {
        }
        
        public eliminar_mascotaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorId_mascota", WrapperNamespace="http://mascota.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorId_mascotaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int mascotaId;
        
        public obtenerPorId_mascotaRequest() {
        }
        
        public obtenerPorId_mascotaRequest(int mascotaId) {
            this.mascotaId = mascotaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorId_mascotaResponse", WrapperNamespace="http://mascota.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorId_mascotaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPetBussiness.MascotaClient.mascotaDto @return;
        
        public obtenerPorId_mascotaResponse() {
        }
        
        public obtenerPorId_mascotaResponse(SoftPetBussiness.MascotaClient.mascotaDto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listar_mascotas", WrapperNamespace="http://mascota.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class listar_mascotasRequest {
        
        public listar_mascotasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listar_mascotasResponse", WrapperNamespace="http://mascota.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class listar_mascotasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPetBussiness.MascotaClient.mascotaDto[] @return;
        
        public listar_mascotasResponse() {
        }
        
        public listar_mascotasResponse(SoftPetBussiness.MascotaClient.mascotaDto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerificarSiLaMascotaTieneInformacion", WrapperNamespace="http://mascota.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class VerificarSiLaMascotaTieneInformacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int nombreTipo;
        
        public VerificarSiLaMascotaTieneInformacionRequest() {
        }
        
        public VerificarSiLaMascotaTieneInformacionRequest(int nombreTipo) {
            this.nombreTipo = nombreTipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerificarSiLaMascotaTieneInformacionResponse", WrapperNamespace="http://mascota.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class VerificarSiLaMascotaTieneInformacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mascota.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public VerificarSiLaMascotaTieneInformacionResponse() {
        }
        
        public VerificarSiLaMascotaTieneInformacionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MascotasChannel : SoftPetBussiness.MascotaClient.Mascotas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MascotasClient : System.ServiceModel.ClientBase<SoftPetBussiness.MascotaClient.Mascotas>, SoftPetBussiness.MascotaClient.Mascotas {
        
        public MascotasClient() {
        }
        
        public MascotasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MascotasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MascotasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MascotasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.MascotaClient.listar_mascotas_por_personaResponse SoftPetBussiness.MascotaClient.Mascotas.listar_mascotas_por_persona(SoftPetBussiness.MascotaClient.listar_mascotas_por_personaRequest request) {
            return base.Channel.listar_mascotas_por_persona(request);
        }
        
        public SoftPetBussiness.MascotaClient.mascotaDto[] listar_mascotas_por_persona(int personaId) {
            SoftPetBussiness.MascotaClient.listar_mascotas_por_personaRequest inValue = new SoftPetBussiness.MascotaClient.listar_mascotas_por_personaRequest();
            inValue.personaId = personaId;
            SoftPetBussiness.MascotaClient.listar_mascotas_por_personaResponse retVal = ((SoftPetBussiness.MascotaClient.Mascotas)(this)).listar_mascotas_por_persona(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.MascotaClient.listar_mascotas_por_personaResponse> SoftPetBussiness.MascotaClient.Mascotas.listar_mascotas_por_personaAsync(SoftPetBussiness.MascotaClient.listar_mascotas_por_personaRequest request) {
            return base.Channel.listar_mascotas_por_personaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.MascotaClient.listar_mascotas_por_personaResponse> listar_mascotas_por_personaAsync(int personaId) {
            SoftPetBussiness.MascotaClient.listar_mascotas_por_personaRequest inValue = new SoftPetBussiness.MascotaClient.listar_mascotas_por_personaRequest();
            inValue.personaId = personaId;
            return ((SoftPetBussiness.MascotaClient.Mascotas)(this)).listar_mascotas_por_personaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.MascotaClient.ListasBusquedaAvanzadaResponse SoftPetBussiness.MascotaClient.Mascotas.ListasBusquedaAvanzada(SoftPetBussiness.MascotaClient.ListasBusquedaAvanzadaRequest request) {
            return base.Channel.ListasBusquedaAvanzada(request);
        }
        
        public SoftPetBussiness.MascotaClient.mascotaDto[] ListasBusquedaAvanzada(string nombreMascota, string especie, string nombreDeLaPersona, int estadoActivo) {
            SoftPetBussiness.MascotaClient.ListasBusquedaAvanzadaRequest inValue = new SoftPetBussiness.MascotaClient.ListasBusquedaAvanzadaRequest();
            inValue.nombreMascota = nombreMascota;
            inValue.especie = especie;
            inValue.nombreDeLaPersona = nombreDeLaPersona;
            inValue.estadoActivo = estadoActivo;
            SoftPetBussiness.MascotaClient.ListasBusquedaAvanzadaResponse retVal = ((SoftPetBussiness.MascotaClient.Mascotas)(this)).ListasBusquedaAvanzada(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.MascotaClient.ListasBusquedaAvanzadaResponse> SoftPetBussiness.MascotaClient.Mascotas.ListasBusquedaAvanzadaAsync(SoftPetBussiness.MascotaClient.ListasBusquedaAvanzadaRequest request) {
            return base.Channel.ListasBusquedaAvanzadaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.MascotaClient.ListasBusquedaAvanzadaResponse> ListasBusquedaAvanzadaAsync(string nombreMascota, string especie, string nombreDeLaPersona, int estadoActivo) {
            SoftPetBussiness.MascotaClient.ListasBusquedaAvanzadaRequest inValue = new SoftPetBussiness.MascotaClient.ListasBusquedaAvanzadaRequest();
            inValue.nombreMascota = nombreMascota;
            inValue.especie = especie;
            inValue.nombreDeLaPersona = nombreDeLaPersona;
            inValue.estadoActivo = estadoActivo;
            return ((SoftPetBussiness.MascotaClient.Mascotas)(this)).ListasBusquedaAvanzadaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.MascotaClient.listar_mascotas_activasResponse SoftPetBussiness.MascotaClient.Mascotas.listar_mascotas_activas(SoftPetBussiness.MascotaClient.listar_mascotas_activasRequest request) {
            return base.Channel.listar_mascotas_activas(request);
        }
        
        public SoftPetBussiness.MascotaClient.mascotaDto[] listar_mascotas_activas() {
            SoftPetBussiness.MascotaClient.listar_mascotas_activasRequest inValue = new SoftPetBussiness.MascotaClient.listar_mascotas_activasRequest();
            SoftPetBussiness.MascotaClient.listar_mascotas_activasResponse retVal = ((SoftPetBussiness.MascotaClient.Mascotas)(this)).listar_mascotas_activas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.MascotaClient.listar_mascotas_activasResponse> SoftPetBussiness.MascotaClient.Mascotas.listar_mascotas_activasAsync(SoftPetBussiness.MascotaClient.listar_mascotas_activasRequest request) {
            return base.Channel.listar_mascotas_activasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.MascotaClient.listar_mascotas_activasResponse> listar_mascotas_activasAsync() {
            SoftPetBussiness.MascotaClient.listar_mascotas_activasRequest inValue = new SoftPetBussiness.MascotaClient.listar_mascotas_activasRequest();
            return ((SoftPetBussiness.MascotaClient.Mascotas)(this)).listar_mascotas_activasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.MascotaClient.insertar_mascotaResponse SoftPetBussiness.MascotaClient.Mascotas.insertar_mascota(SoftPetBussiness.MascotaClient.insertar_mascotaRequest request) {
            return base.Channel.insertar_mascota(request);
        }
        
        public int insertar_mascota(int personaId, string nombre, string especie, string sexo, string raza, string color, string fechaDefuncion, bool activo) {
            SoftPetBussiness.MascotaClient.insertar_mascotaRequest inValue = new SoftPetBussiness.MascotaClient.insertar_mascotaRequest();
            inValue.personaId = personaId;
            inValue.nombre = nombre;
            inValue.especie = especie;
            inValue.sexo = sexo;
            inValue.raza = raza;
            inValue.color = color;
            inValue.fechaDefuncion = fechaDefuncion;
            inValue.activo = activo;
            SoftPetBussiness.MascotaClient.insertar_mascotaResponse retVal = ((SoftPetBussiness.MascotaClient.Mascotas)(this)).insertar_mascota(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.MascotaClient.insertar_mascotaResponse> SoftPetBussiness.MascotaClient.Mascotas.insertar_mascotaAsync(SoftPetBussiness.MascotaClient.insertar_mascotaRequest request) {
            return base.Channel.insertar_mascotaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.MascotaClient.insertar_mascotaResponse> insertar_mascotaAsync(int personaId, string nombre, string especie, string sexo, string raza, string color, string fechaDefuncion, bool activo) {
            SoftPetBussiness.MascotaClient.insertar_mascotaRequest inValue = new SoftPetBussiness.MascotaClient.insertar_mascotaRequest();
            inValue.personaId = personaId;
            inValue.nombre = nombre;
            inValue.especie = especie;
            inValue.sexo = sexo;
            inValue.raza = raza;
            inValue.color = color;
            inValue.fechaDefuncion = fechaDefuncion;
            inValue.activo = activo;
            return ((SoftPetBussiness.MascotaClient.Mascotas)(this)).insertar_mascotaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.MascotaClient.modificar_mascotaResponse SoftPetBussiness.MascotaClient.Mascotas.modificar_mascota(SoftPetBussiness.MascotaClient.modificar_mascotaRequest request) {
            return base.Channel.modificar_mascota(request);
        }
        
        public int modificar_mascota(int mascotaId, int personaId, string nombre, string especie, string sexo, string raza, string color, string fechaDefuncion, bool activo) {
            SoftPetBussiness.MascotaClient.modificar_mascotaRequest inValue = new SoftPetBussiness.MascotaClient.modificar_mascotaRequest();
            inValue.mascotaId = mascotaId;
            inValue.personaId = personaId;
            inValue.nombre = nombre;
            inValue.especie = especie;
            inValue.sexo = sexo;
            inValue.raza = raza;
            inValue.color = color;
            inValue.fechaDefuncion = fechaDefuncion;
            inValue.activo = activo;
            SoftPetBussiness.MascotaClient.modificar_mascotaResponse retVal = ((SoftPetBussiness.MascotaClient.Mascotas)(this)).modificar_mascota(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.MascotaClient.modificar_mascotaResponse> SoftPetBussiness.MascotaClient.Mascotas.modificar_mascotaAsync(SoftPetBussiness.MascotaClient.modificar_mascotaRequest request) {
            return base.Channel.modificar_mascotaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.MascotaClient.modificar_mascotaResponse> modificar_mascotaAsync(int mascotaId, int personaId, string nombre, string especie, string sexo, string raza, string color, string fechaDefuncion, bool activo) {
            SoftPetBussiness.MascotaClient.modificar_mascotaRequest inValue = new SoftPetBussiness.MascotaClient.modificar_mascotaRequest();
            inValue.mascotaId = mascotaId;
            inValue.personaId = personaId;
            inValue.nombre = nombre;
            inValue.especie = especie;
            inValue.sexo = sexo;
            inValue.raza = raza;
            inValue.color = color;
            inValue.fechaDefuncion = fechaDefuncion;
            inValue.activo = activo;
            return ((SoftPetBussiness.MascotaClient.Mascotas)(this)).modificar_mascotaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.MascotaClient.eliminar_mascotaResponse SoftPetBussiness.MascotaClient.Mascotas.eliminar_mascota(SoftPetBussiness.MascotaClient.eliminar_mascotaRequest request) {
            return base.Channel.eliminar_mascota(request);
        }
        
        public int eliminar_mascota(int mascotaId) {
            SoftPetBussiness.MascotaClient.eliminar_mascotaRequest inValue = new SoftPetBussiness.MascotaClient.eliminar_mascotaRequest();
            inValue.mascotaId = mascotaId;
            SoftPetBussiness.MascotaClient.eliminar_mascotaResponse retVal = ((SoftPetBussiness.MascotaClient.Mascotas)(this)).eliminar_mascota(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.MascotaClient.eliminar_mascotaResponse> SoftPetBussiness.MascotaClient.Mascotas.eliminar_mascotaAsync(SoftPetBussiness.MascotaClient.eliminar_mascotaRequest request) {
            return base.Channel.eliminar_mascotaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.MascotaClient.eliminar_mascotaResponse> eliminar_mascotaAsync(int mascotaId) {
            SoftPetBussiness.MascotaClient.eliminar_mascotaRequest inValue = new SoftPetBussiness.MascotaClient.eliminar_mascotaRequest();
            inValue.mascotaId = mascotaId;
            return ((SoftPetBussiness.MascotaClient.Mascotas)(this)).eliminar_mascotaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.MascotaClient.obtenerPorId_mascotaResponse SoftPetBussiness.MascotaClient.Mascotas.obtenerPorId_mascota(SoftPetBussiness.MascotaClient.obtenerPorId_mascotaRequest request) {
            return base.Channel.obtenerPorId_mascota(request);
        }
        
        public SoftPetBussiness.MascotaClient.mascotaDto obtenerPorId_mascota(int mascotaId) {
            SoftPetBussiness.MascotaClient.obtenerPorId_mascotaRequest inValue = new SoftPetBussiness.MascotaClient.obtenerPorId_mascotaRequest();
            inValue.mascotaId = mascotaId;
            SoftPetBussiness.MascotaClient.obtenerPorId_mascotaResponse retVal = ((SoftPetBussiness.MascotaClient.Mascotas)(this)).obtenerPorId_mascota(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.MascotaClient.obtenerPorId_mascotaResponse> SoftPetBussiness.MascotaClient.Mascotas.obtenerPorId_mascotaAsync(SoftPetBussiness.MascotaClient.obtenerPorId_mascotaRequest request) {
            return base.Channel.obtenerPorId_mascotaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.MascotaClient.obtenerPorId_mascotaResponse> obtenerPorId_mascotaAsync(int mascotaId) {
            SoftPetBussiness.MascotaClient.obtenerPorId_mascotaRequest inValue = new SoftPetBussiness.MascotaClient.obtenerPorId_mascotaRequest();
            inValue.mascotaId = mascotaId;
            return ((SoftPetBussiness.MascotaClient.Mascotas)(this)).obtenerPorId_mascotaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.MascotaClient.listar_mascotasResponse SoftPetBussiness.MascotaClient.Mascotas.listar_mascotas(SoftPetBussiness.MascotaClient.listar_mascotasRequest request) {
            return base.Channel.listar_mascotas(request);
        }
        
        public SoftPetBussiness.MascotaClient.mascotaDto[] listar_mascotas() {
            SoftPetBussiness.MascotaClient.listar_mascotasRequest inValue = new SoftPetBussiness.MascotaClient.listar_mascotasRequest();
            SoftPetBussiness.MascotaClient.listar_mascotasResponse retVal = ((SoftPetBussiness.MascotaClient.Mascotas)(this)).listar_mascotas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.MascotaClient.listar_mascotasResponse> SoftPetBussiness.MascotaClient.Mascotas.listar_mascotasAsync(SoftPetBussiness.MascotaClient.listar_mascotasRequest request) {
            return base.Channel.listar_mascotasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.MascotaClient.listar_mascotasResponse> listar_mascotasAsync() {
            SoftPetBussiness.MascotaClient.listar_mascotasRequest inValue = new SoftPetBussiness.MascotaClient.listar_mascotasRequest();
            return ((SoftPetBussiness.MascotaClient.Mascotas)(this)).listar_mascotasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.MascotaClient.VerificarSiLaMascotaTieneInformacionResponse SoftPetBussiness.MascotaClient.Mascotas.VerificarSiLaMascotaTieneInformacion(SoftPetBussiness.MascotaClient.VerificarSiLaMascotaTieneInformacionRequest request) {
            return base.Channel.VerificarSiLaMascotaTieneInformacion(request);
        }
        
        public int VerificarSiLaMascotaTieneInformacion(int nombreTipo) {
            SoftPetBussiness.MascotaClient.VerificarSiLaMascotaTieneInformacionRequest inValue = new SoftPetBussiness.MascotaClient.VerificarSiLaMascotaTieneInformacionRequest();
            inValue.nombreTipo = nombreTipo;
            SoftPetBussiness.MascotaClient.VerificarSiLaMascotaTieneInformacionResponse retVal = ((SoftPetBussiness.MascotaClient.Mascotas)(this)).VerificarSiLaMascotaTieneInformacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.MascotaClient.VerificarSiLaMascotaTieneInformacionResponse> SoftPetBussiness.MascotaClient.Mascotas.VerificarSiLaMascotaTieneInformacionAsync(SoftPetBussiness.MascotaClient.VerificarSiLaMascotaTieneInformacionRequest request) {
            return base.Channel.VerificarSiLaMascotaTieneInformacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.MascotaClient.VerificarSiLaMascotaTieneInformacionResponse> VerificarSiLaMascotaTieneInformacionAsync(int nombreTipo) {
            SoftPetBussiness.MascotaClient.VerificarSiLaMascotaTieneInformacionRequest inValue = new SoftPetBussiness.MascotaClient.VerificarSiLaMascotaTieneInformacionRequest();
            inValue.nombreTipo = nombreTipo;
            return ((SoftPetBussiness.MascotaClient.Mascotas)(this)).VerificarSiLaMascotaTieneInformacionAsync(inValue);
        }
    }
}
