//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPetBussiness.DocumentoDePagoClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", ConfigurationName="DocumentoDePagoClient.DocumentosDePago")]
    public interface DocumentosDePago {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/enviar_comprobante_al_corre" +
            "oRequest", ReplyAction="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/enviar_comprobante_al_corre" +
            "oResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.DocumentoDePagoClient.enviar_comprobante_al_correoResponse enviar_comprobante_al_correo(SoftPetBussiness.DocumentoDePagoClient.enviar_comprobante_al_correoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/enviar_comprobante_al_corre" +
            "oRequest", ReplyAction="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/enviar_comprobante_al_corre" +
            "oResponse")]
        System.Threading.Tasks.Task<SoftPetBussiness.DocumentoDePagoClient.enviar_comprobante_al_correoResponse> enviar_comprobante_al_correoAsync(SoftPetBussiness.DocumentoDePagoClient.enviar_comprobante_al_correoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/listar_por_fechaRequest", ReplyAction="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/listar_por_fechaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.DocumentoDePagoClient.listar_por_fechaResponse listar_por_fecha(SoftPetBussiness.DocumentoDePagoClient.listar_por_fechaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/listar_por_fechaRequest", ReplyAction="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/listar_por_fechaResponse")]
        System.Threading.Tasks.Task<SoftPetBussiness.DocumentoDePagoClient.listar_por_fechaResponse> listar_por_fechaAsync(SoftPetBussiness.DocumentoDePagoClient.listar_por_fechaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/generar_comprobante_de_pago" +
            "_pdfRequest", ReplyAction="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/generar_comprobante_de_pago" +
            "_pdfResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.DocumentoDePagoClient.generar_comprobante_de_pago_pdfResponse generar_comprobante_de_pago_pdf(SoftPetBussiness.DocumentoDePagoClient.generar_comprobante_de_pago_pdfRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/generar_comprobante_de_pago" +
            "_pdfRequest", ReplyAction="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/generar_comprobante_de_pago" +
            "_pdfResponse")]
        System.Threading.Tasks.Task<SoftPetBussiness.DocumentoDePagoClient.generar_comprobante_de_pago_pdfResponse> generar_comprobante_de_pago_pdfAsync(SoftPetBussiness.DocumentoDePagoClient.generar_comprobante_de_pago_pdfRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/insertar_Documento_De_PagoR" +
            "equest", ReplyAction="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/insertar_Documento_De_PagoR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.DocumentoDePagoClient.insertar_Documento_De_PagoResponse insertar_Documento_De_Pago(SoftPetBussiness.DocumentoDePagoClient.insertar_Documento_De_PagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/insertar_Documento_De_PagoR" +
            "equest", ReplyAction="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/insertar_Documento_De_PagoR" +
            "esponse")]
        System.Threading.Tasks.Task<SoftPetBussiness.DocumentoDePagoClient.insertar_Documento_De_PagoResponse> insertar_Documento_De_PagoAsync(SoftPetBussiness.DocumentoDePagoClient.insertar_Documento_De_PagoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/modificar_Documento_De_Pago" +
            "Request", ReplyAction="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/modificar_Documento_De_Pago" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.DocumentoDePagoClient.modificar_Documento_De_PagoResponse modificar_Documento_De_Pago(SoftPetBussiness.DocumentoDePagoClient.modificar_Documento_De_PagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/modificar_Documento_De_Pago" +
            "Request", ReplyAction="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/modificar_Documento_De_Pago" +
            "Response")]
        System.Threading.Tasks.Task<SoftPetBussiness.DocumentoDePagoClient.modificar_Documento_De_PagoResponse> modificar_Documento_De_PagoAsync(SoftPetBussiness.DocumentoDePagoClient.modificar_Documento_De_PagoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/eliminar_Documento_De_PagoR" +
            "equest", ReplyAction="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/eliminar_Documento_De_PagoR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.DocumentoDePagoClient.eliminar_Documento_De_PagoResponse eliminar_Documento_De_Pago(SoftPetBussiness.DocumentoDePagoClient.eliminar_Documento_De_PagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/eliminar_Documento_De_PagoR" +
            "equest", ReplyAction="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/eliminar_Documento_De_PagoR" +
            "esponse")]
        System.Threading.Tasks.Task<SoftPetBussiness.DocumentoDePagoClient.eliminar_Documento_De_PagoResponse> eliminar_Documento_De_PagoAsync(SoftPetBussiness.DocumentoDePagoClient.eliminar_Documento_De_PagoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/obtener_por_idRequest", ReplyAction="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/obtener_por_idResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.DocumentoDePagoClient.obtener_por_idResponse obtener_por_id(SoftPetBussiness.DocumentoDePagoClient.obtener_por_idRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/obtener_por_idRequest", ReplyAction="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/obtener_por_idResponse")]
        System.Threading.Tasks.Task<SoftPetBussiness.DocumentoDePagoClient.obtener_por_idResponse> obtener_por_idAsync(SoftPetBussiness.DocumentoDePagoClient.obtener_por_idRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/listar_todosRequest", ReplyAction="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/listar_todosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.DocumentoDePagoClient.listar_todosResponse listar_todos(SoftPetBussiness.DocumentoDePagoClient.listar_todosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/listar_todosRequest", ReplyAction="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/listar_todosResponse")]
        System.Threading.Tasks.Task<SoftPetBussiness.DocumentoDePagoClient.listar_todosResponse> listar_todosAsync(SoftPetBussiness.DocumentoDePagoClient.listar_todosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/GeneracionDeSiguienteBoleta" +
            "OFacturaRequest", ReplyAction="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/GeneracionDeSiguienteBoleta" +
            "OFacturaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.DocumentoDePagoClient.GeneracionDeSiguienteBoletaOFacturaResponse GeneracionDeSiguienteBoletaOFactura(SoftPetBussiness.DocumentoDePagoClient.GeneracionDeSiguienteBoletaOFacturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/GeneracionDeSiguienteBoleta" +
            "OFacturaRequest", ReplyAction="http://docpago.softpetws.pucp.edu.pe/DocumentosDePago/GeneracionDeSiguienteBoleta" +
            "OFacturaResponse")]
        System.Threading.Tasks.Task<SoftPetBussiness.DocumentoDePagoClient.GeneracionDeSiguienteBoletaOFacturaResponse> GeneracionDeSiguienteBoletaOFacturaAsync(SoftPetBussiness.DocumentoDePagoClient.GeneracionDeSiguienteBoletaOFacturaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviar_comprobante_al_correo", WrapperNamespace="http://docpago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class enviar_comprobante_al_correoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idcomprobante;
        
        public enviar_comprobante_al_correoRequest() {
        }
        
        public enviar_comprobante_al_correoRequest(string correo, string tipoDocumento, int idcomprobante) {
            this.correo = correo;
            this.tipoDocumento = tipoDocumento;
            this.idcomprobante = idcomprobante;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviar_comprobante_al_correoResponse", WrapperNamespace="http://docpago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class enviar_comprobante_al_correoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public enviar_comprobante_al_correoResponse() {
        }
        
        public enviar_comprobante_al_correoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/")]
    public partial class documentoPagoDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private int documentoPagoIdField;
        
        private bool documentoPagoIdFieldSpecified;
        
        private estadoDocumentoDePago estadoField;
        
        private bool estadoFieldSpecified;
        
        private date fechaEmisionField;
        
        private string fechaEmisionStringField;
        
        private double iGVTotalField;
        
        private bool iGVTotalFieldSpecified;
        
        private metodoDePagoDto metodoDePagoField;
        
        private string numeroField;
        
        private personaDto personaField;
        
        private string serieField;
        
        private double subtotalField;
        
        private bool subtotalFieldSpecified;
        
        private tipoDocumentoDePago tipoDocumentoField;
        
        private bool tipoDocumentoFieldSpecified;
        
        private double totalField;
        
        private bool totalFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int documentoPagoId {
            get {
                return this.documentoPagoIdField;
            }
            set {
                this.documentoPagoIdField = value;
                this.RaisePropertyChanged("documentoPagoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool documentoPagoIdSpecified {
            get {
                return this.documentoPagoIdFieldSpecified;
            }
            set {
                this.documentoPagoIdFieldSpecified = value;
                this.RaisePropertyChanged("documentoPagoIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public estadoDocumentoDePago estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public date fechaEmision {
            get {
                return this.fechaEmisionField;
            }
            set {
                this.fechaEmisionField = value;
                this.RaisePropertyChanged("fechaEmision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string fechaEmisionString {
            get {
                return this.fechaEmisionStringField;
            }
            set {
                this.fechaEmisionStringField = value;
                this.RaisePropertyChanged("fechaEmisionString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double IGVTotal {
            get {
                return this.iGVTotalField;
            }
            set {
                this.iGVTotalField = value;
                this.RaisePropertyChanged("IGVTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IGVTotalSpecified {
            get {
                return this.iGVTotalFieldSpecified;
            }
            set {
                this.iGVTotalFieldSpecified = value;
                this.RaisePropertyChanged("IGVTotalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public metodoDePagoDto metodoDePago {
            get {
                return this.metodoDePagoField;
            }
            set {
                this.metodoDePagoField = value;
                this.RaisePropertyChanged("metodoDePago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public personaDto persona {
            get {
                return this.personaField;
            }
            set {
                this.personaField = value;
                this.RaisePropertyChanged("persona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
                this.RaisePropertyChanged("serie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public double subtotal {
            get {
                return this.subtotalField;
            }
            set {
                this.subtotalField = value;
                this.RaisePropertyChanged("subtotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subtotalSpecified {
            get {
                return this.subtotalFieldSpecified;
            }
            set {
                this.subtotalFieldSpecified = value;
                this.RaisePropertyChanged("subtotalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public tipoDocumentoDePago tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoDocumentoSpecified {
            get {
                return this.tipoDocumentoFieldSpecified;
            }
            set {
                this.tipoDocumentoFieldSpecified = value;
                this.RaisePropertyChanged("tipoDocumentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public double total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalSpecified {
            get {
                return this.totalFieldSpecified;
            }
            set {
                this.totalFieldSpecified = value;
                this.RaisePropertyChanged("totalSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/")]
    public enum estadoDocumentoDePago {
        
        /// <remarks/>
        EMITIDO,
        
        /// <remarks/>
        PAGADO,
        
        /// <remarks/>
        ANULADO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/")]
    public partial class date : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/")]
    public partial class usuarioDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private string correoField;
        
        private date fechaCreacionField;
        
        private date fechaModificacionField;
        
        private string passwordField;
        
        private string usernameField;
        
        private string usuarioCreadorField;
        
        private int usuarioIdField;
        
        private bool usuarioIdFieldSpecified;
        
        private string usuarioModificadorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public date fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public date fechaModificacion {
            get {
                return this.fechaModificacionField;
            }
            set {
                this.fechaModificacionField = value;
                this.RaisePropertyChanged("fechaModificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string usuarioCreador {
            get {
                return this.usuarioCreadorField;
            }
            set {
                this.usuarioCreadorField = value;
                this.RaisePropertyChanged("usuarioCreador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int usuarioId {
            get {
                return this.usuarioIdField;
            }
            set {
                this.usuarioIdField = value;
                this.RaisePropertyChanged("usuarioId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usuarioIdSpecified {
            get {
                return this.usuarioIdFieldSpecified;
            }
            set {
                this.usuarioIdFieldSpecified = value;
                this.RaisePropertyChanged("usuarioIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string usuarioModificador {
            get {
                return this.usuarioModificadorField;
            }
            set {
                this.usuarioModificadorField = value;
                this.RaisePropertyChanged("usuarioModificador");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/")]
    public partial class personaDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private string direccionField;
        
        private string nombreField;
        
        private int nroDocumentoField;
        
        private bool nroDocumentoFieldSpecified;
        
        private int personaIdField;
        
        private bool personaIdFieldSpecified;
        
        private int rucField;
        
        private bool rucFieldSpecified;
        
        private sexo sexoField;
        
        private bool sexoFieldSpecified;
        
        private string telefonoField;
        
        private string tipoDocumentoField;
        
        private usuarioDto usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int nroDocumento {
            get {
                return this.nroDocumentoField;
            }
            set {
                this.nroDocumentoField = value;
                this.RaisePropertyChanged("nroDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nroDocumentoSpecified {
            get {
                return this.nroDocumentoFieldSpecified;
            }
            set {
                this.nroDocumentoFieldSpecified = value;
                this.RaisePropertyChanged("nroDocumentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int personaId {
            get {
                return this.personaIdField;
            }
            set {
                this.personaIdField = value;
                this.RaisePropertyChanged("personaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool personaIdSpecified {
            get {
                return this.personaIdFieldSpecified;
            }
            set {
                this.personaIdFieldSpecified = value;
                this.RaisePropertyChanged("personaIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int ruc {
            get {
                return this.rucField;
            }
            set {
                this.rucField = value;
                this.RaisePropertyChanged("ruc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rucSpecified {
            get {
                return this.rucFieldSpecified;
            }
            set {
                this.rucFieldSpecified = value;
                this.RaisePropertyChanged("rucSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public sexo sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sexoSpecified {
            get {
                return this.sexoFieldSpecified;
            }
            set {
                this.sexoFieldSpecified = value;
                this.RaisePropertyChanged("sexoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public usuarioDto usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/")]
    public enum sexo {
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        O,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/")]
    public partial class metodoDePagoDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private int metodoDePagoIdField;
        
        private bool metodoDePagoIdFieldSpecified;
        
        private tipoMetodoPago nombreField;
        
        private bool nombreFieldSpecified;
        
        private string nombreStrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int metodoDePagoId {
            get {
                return this.metodoDePagoIdField;
            }
            set {
                this.metodoDePagoIdField = value;
                this.RaisePropertyChanged("metodoDePagoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool metodoDePagoIdSpecified {
            get {
                return this.metodoDePagoIdFieldSpecified;
            }
            set {
                this.metodoDePagoIdFieldSpecified = value;
                this.RaisePropertyChanged("metodoDePagoIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public tipoMetodoPago nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nombreSpecified {
            get {
                return this.nombreFieldSpecified;
            }
            set {
                this.nombreFieldSpecified = value;
                this.RaisePropertyChanged("nombreSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombreStr {
            get {
                return this.nombreStrField;
            }
            set {
                this.nombreStrField = value;
                this.RaisePropertyChanged("nombreStr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/")]
    public enum tipoMetodoPago {
        
        /// <remarks/>
        EFECTIVO,
        
        /// <remarks/>
        TRANSFERENCIA,
        
        /// <remarks/>
        YAPE,
        
        /// <remarks/>
        PLIN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/")]
    public enum tipoDocumentoDePago {
        
        /// <remarks/>
        BOLETA,
        
        /// <remarks/>
        FACTURA,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listar_por_fecha", WrapperNamespace="http://docpago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class listar_por_fechaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fecha;
        
        public listar_por_fechaRequest() {
        }
        
        public listar_por_fechaRequest(string fecha) {
            this.fecha = fecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listar_por_fechaResponse", WrapperNamespace="http://docpago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class listar_por_fechaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPetBussiness.DocumentoDePagoClient.documentoPagoDto[] @return;
        
        public listar_por_fechaResponse() {
        }
        
        public listar_por_fechaResponse(SoftPetBussiness.DocumentoDePagoClient.documentoPagoDto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generar_comprobante_de_pago_pdf", WrapperNamespace="http://docpago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class generar_comprobante_de_pago_pdfRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idcomprobante;
        
        public generar_comprobante_de_pago_pdfRequest() {
        }
        
        public generar_comprobante_de_pago_pdfRequest(string tipoDocumento, int idcomprobante) {
            this.tipoDocumento = tipoDocumento;
            this.idcomprobante = idcomprobante;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generar_comprobante_de_pago_pdfResponse", WrapperNamespace="http://docpago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class generar_comprobante_de_pago_pdfResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public generar_comprobante_de_pago_pdfResponse() {
        }
        
        public generar_comprobante_de_pago_pdfResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertar_Documento_De_Pago", WrapperNamespace="http://docpago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertar_Documento_De_PagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int metodoDePagoId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int personaId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string serie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numero;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaEmision;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double subtotal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double igvTotal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double total;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool activo;
        
        public insertar_Documento_De_PagoRequest() {
        }
        
        public insertar_Documento_De_PagoRequest(int metodoDePagoId, int personaId, string tipoDocumento, string serie, string numero, string fechaEmision, string estado, double subtotal, double igvTotal, double total, bool activo) {
            this.metodoDePagoId = metodoDePagoId;
            this.personaId = personaId;
            this.tipoDocumento = tipoDocumento;
            this.serie = serie;
            this.numero = numero;
            this.fechaEmision = fechaEmision;
            this.estado = estado;
            this.subtotal = subtotal;
            this.igvTotal = igvTotal;
            this.total = total;
            this.activo = activo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertar_Documento_De_PagoResponse", WrapperNamespace="http://docpago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertar_Documento_De_PagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertar_Documento_De_PagoResponse() {
        }
        
        public insertar_Documento_De_PagoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificar_Documento_De_Pago", WrapperNamespace="http://docpago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificar_Documento_De_PagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int documentoPagoId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int metodoDePagoId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int personaId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string serie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numero;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaEmision;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double subtotal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double igvTotal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double total;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool activo;
        
        public modificar_Documento_De_PagoRequest() {
        }
        
        public modificar_Documento_De_PagoRequest(int documentoPagoId, int metodoDePagoId, int personaId, string tipoDocumento, string serie, string numero, string fechaEmision, string estado, double subtotal, double igvTotal, double total, bool activo) {
            this.documentoPagoId = documentoPagoId;
            this.metodoDePagoId = metodoDePagoId;
            this.personaId = personaId;
            this.tipoDocumento = tipoDocumento;
            this.serie = serie;
            this.numero = numero;
            this.fechaEmision = fechaEmision;
            this.estado = estado;
            this.subtotal = subtotal;
            this.igvTotal = igvTotal;
            this.total = total;
            this.activo = activo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificar_Documento_De_PagoResponse", WrapperNamespace="http://docpago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificar_Documento_De_PagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificar_Documento_De_PagoResponse() {
        }
        
        public modificar_Documento_De_PagoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminar_Documento_De_Pago", WrapperNamespace="http://docpago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminar_Documento_De_PagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public eliminar_Documento_De_PagoRequest() {
        }
        
        public eliminar_Documento_De_PagoRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminar_Documento_De_PagoResponse", WrapperNamespace="http://docpago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminar_Documento_De_PagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminar_Documento_De_PagoResponse() {
        }
        
        public eliminar_Documento_De_PagoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtener_por_id", WrapperNamespace="http://docpago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtener_por_idRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtener_por_idRequest() {
        }
        
        public obtener_por_idRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtener_por_idResponse", WrapperNamespace="http://docpago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtener_por_idResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPetBussiness.DocumentoDePagoClient.documentoPagoDto @return;
        
        public obtener_por_idResponse() {
        }
        
        public obtener_por_idResponse(SoftPetBussiness.DocumentoDePagoClient.documentoPagoDto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listar_todos", WrapperNamespace="http://docpago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class listar_todosRequest {
        
        public listar_todosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listar_todosResponse", WrapperNamespace="http://docpago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class listar_todosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPetBussiness.DocumentoDePagoClient.documentoPagoDto[] @return;
        
        public listar_todosResponse() {
        }
        
        public listar_todosResponse(SoftPetBussiness.DocumentoDePagoClient.documentoPagoDto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GeneracionDeSiguienteBoletaOFactura", WrapperNamespace="http://docpago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class GeneracionDeSiguienteBoletaOFacturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoDocumento;
        
        public GeneracionDeSiguienteBoletaOFacturaRequest() {
        }
        
        public GeneracionDeSiguienteBoletaOFacturaRequest(string tipoDocumento) {
            this.tipoDocumento = tipoDocumento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GeneracionDeSiguienteBoletaOFacturaResponse", WrapperNamespace="http://docpago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class GeneracionDeSiguienteBoletaOFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docpago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public GeneracionDeSiguienteBoletaOFacturaResponse() {
        }
        
        public GeneracionDeSiguienteBoletaOFacturaResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DocumentosDePagoChannel : SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentosDePagoClient : System.ServiceModel.ClientBase<SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago>, SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago {
        
        public DocumentosDePagoClient() {
        }
        
        public DocumentosDePagoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentosDePagoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentosDePagoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentosDePagoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.DocumentoDePagoClient.enviar_comprobante_al_correoResponse SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago.enviar_comprobante_al_correo(SoftPetBussiness.DocumentoDePagoClient.enviar_comprobante_al_correoRequest request) {
            return base.Channel.enviar_comprobante_al_correo(request);
        }
        
        public string enviar_comprobante_al_correo(string correo, string tipoDocumento, int idcomprobante) {
            SoftPetBussiness.DocumentoDePagoClient.enviar_comprobante_al_correoRequest inValue = new SoftPetBussiness.DocumentoDePagoClient.enviar_comprobante_al_correoRequest();
            inValue.correo = correo;
            inValue.tipoDocumento = tipoDocumento;
            inValue.idcomprobante = idcomprobante;
            SoftPetBussiness.DocumentoDePagoClient.enviar_comprobante_al_correoResponse retVal = ((SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago)(this)).enviar_comprobante_al_correo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.DocumentoDePagoClient.enviar_comprobante_al_correoResponse> SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago.enviar_comprobante_al_correoAsync(SoftPetBussiness.DocumentoDePagoClient.enviar_comprobante_al_correoRequest request) {
            return base.Channel.enviar_comprobante_al_correoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.DocumentoDePagoClient.enviar_comprobante_al_correoResponse> enviar_comprobante_al_correoAsync(string correo, string tipoDocumento, int idcomprobante) {
            SoftPetBussiness.DocumentoDePagoClient.enviar_comprobante_al_correoRequest inValue = new SoftPetBussiness.DocumentoDePagoClient.enviar_comprobante_al_correoRequest();
            inValue.correo = correo;
            inValue.tipoDocumento = tipoDocumento;
            inValue.idcomprobante = idcomprobante;
            return ((SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago)(this)).enviar_comprobante_al_correoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.DocumentoDePagoClient.listar_por_fechaResponse SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago.listar_por_fecha(SoftPetBussiness.DocumentoDePagoClient.listar_por_fechaRequest request) {
            return base.Channel.listar_por_fecha(request);
        }
        
        public SoftPetBussiness.DocumentoDePagoClient.documentoPagoDto[] listar_por_fecha(string fecha) {
            SoftPetBussiness.DocumentoDePagoClient.listar_por_fechaRequest inValue = new SoftPetBussiness.DocumentoDePagoClient.listar_por_fechaRequest();
            inValue.fecha = fecha;
            SoftPetBussiness.DocumentoDePagoClient.listar_por_fechaResponse retVal = ((SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago)(this)).listar_por_fecha(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.DocumentoDePagoClient.listar_por_fechaResponse> SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago.listar_por_fechaAsync(SoftPetBussiness.DocumentoDePagoClient.listar_por_fechaRequest request) {
            return base.Channel.listar_por_fechaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.DocumentoDePagoClient.listar_por_fechaResponse> listar_por_fechaAsync(string fecha) {
            SoftPetBussiness.DocumentoDePagoClient.listar_por_fechaRequest inValue = new SoftPetBussiness.DocumentoDePagoClient.listar_por_fechaRequest();
            inValue.fecha = fecha;
            return ((SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago)(this)).listar_por_fechaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.DocumentoDePagoClient.generar_comprobante_de_pago_pdfResponse SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago.generar_comprobante_de_pago_pdf(SoftPetBussiness.DocumentoDePagoClient.generar_comprobante_de_pago_pdfRequest request) {
            return base.Channel.generar_comprobante_de_pago_pdf(request);
        }
        
        public byte[] generar_comprobante_de_pago_pdf(string tipoDocumento, int idcomprobante) {
            SoftPetBussiness.DocumentoDePagoClient.generar_comprobante_de_pago_pdfRequest inValue = new SoftPetBussiness.DocumentoDePagoClient.generar_comprobante_de_pago_pdfRequest();
            inValue.tipoDocumento = tipoDocumento;
            inValue.idcomprobante = idcomprobante;
            SoftPetBussiness.DocumentoDePagoClient.generar_comprobante_de_pago_pdfResponse retVal = ((SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago)(this)).generar_comprobante_de_pago_pdf(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.DocumentoDePagoClient.generar_comprobante_de_pago_pdfResponse> SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago.generar_comprobante_de_pago_pdfAsync(SoftPetBussiness.DocumentoDePagoClient.generar_comprobante_de_pago_pdfRequest request) {
            return base.Channel.generar_comprobante_de_pago_pdfAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.DocumentoDePagoClient.generar_comprobante_de_pago_pdfResponse> generar_comprobante_de_pago_pdfAsync(string tipoDocumento, int idcomprobante) {
            SoftPetBussiness.DocumentoDePagoClient.generar_comprobante_de_pago_pdfRequest inValue = new SoftPetBussiness.DocumentoDePagoClient.generar_comprobante_de_pago_pdfRequest();
            inValue.tipoDocumento = tipoDocumento;
            inValue.idcomprobante = idcomprobante;
            return ((SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago)(this)).generar_comprobante_de_pago_pdfAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.DocumentoDePagoClient.insertar_Documento_De_PagoResponse SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago.insertar_Documento_De_Pago(SoftPetBussiness.DocumentoDePagoClient.insertar_Documento_De_PagoRequest request) {
            return base.Channel.insertar_Documento_De_Pago(request);
        }
        
        public int insertar_Documento_De_Pago(int metodoDePagoId, int personaId, string tipoDocumento, string serie, string numero, string fechaEmision, string estado, double subtotal, double igvTotal, double total, bool activo) {
            SoftPetBussiness.DocumentoDePagoClient.insertar_Documento_De_PagoRequest inValue = new SoftPetBussiness.DocumentoDePagoClient.insertar_Documento_De_PagoRequest();
            inValue.metodoDePagoId = metodoDePagoId;
            inValue.personaId = personaId;
            inValue.tipoDocumento = tipoDocumento;
            inValue.serie = serie;
            inValue.numero = numero;
            inValue.fechaEmision = fechaEmision;
            inValue.estado = estado;
            inValue.subtotal = subtotal;
            inValue.igvTotal = igvTotal;
            inValue.total = total;
            inValue.activo = activo;
            SoftPetBussiness.DocumentoDePagoClient.insertar_Documento_De_PagoResponse retVal = ((SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago)(this)).insertar_Documento_De_Pago(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.DocumentoDePagoClient.insertar_Documento_De_PagoResponse> SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago.insertar_Documento_De_PagoAsync(SoftPetBussiness.DocumentoDePagoClient.insertar_Documento_De_PagoRequest request) {
            return base.Channel.insertar_Documento_De_PagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.DocumentoDePagoClient.insertar_Documento_De_PagoResponse> insertar_Documento_De_PagoAsync(int metodoDePagoId, int personaId, string tipoDocumento, string serie, string numero, string fechaEmision, string estado, double subtotal, double igvTotal, double total, bool activo) {
            SoftPetBussiness.DocumentoDePagoClient.insertar_Documento_De_PagoRequest inValue = new SoftPetBussiness.DocumentoDePagoClient.insertar_Documento_De_PagoRequest();
            inValue.metodoDePagoId = metodoDePagoId;
            inValue.personaId = personaId;
            inValue.tipoDocumento = tipoDocumento;
            inValue.serie = serie;
            inValue.numero = numero;
            inValue.fechaEmision = fechaEmision;
            inValue.estado = estado;
            inValue.subtotal = subtotal;
            inValue.igvTotal = igvTotal;
            inValue.total = total;
            inValue.activo = activo;
            return ((SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago)(this)).insertar_Documento_De_PagoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.DocumentoDePagoClient.modificar_Documento_De_PagoResponse SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago.modificar_Documento_De_Pago(SoftPetBussiness.DocumentoDePagoClient.modificar_Documento_De_PagoRequest request) {
            return base.Channel.modificar_Documento_De_Pago(request);
        }
        
        public int modificar_Documento_De_Pago(int documentoPagoId, int metodoDePagoId, int personaId, string tipoDocumento, string serie, string numero, string fechaEmision, string estado, double subtotal, double igvTotal, double total, bool activo) {
            SoftPetBussiness.DocumentoDePagoClient.modificar_Documento_De_PagoRequest inValue = new SoftPetBussiness.DocumentoDePagoClient.modificar_Documento_De_PagoRequest();
            inValue.documentoPagoId = documentoPagoId;
            inValue.metodoDePagoId = metodoDePagoId;
            inValue.personaId = personaId;
            inValue.tipoDocumento = tipoDocumento;
            inValue.serie = serie;
            inValue.numero = numero;
            inValue.fechaEmision = fechaEmision;
            inValue.estado = estado;
            inValue.subtotal = subtotal;
            inValue.igvTotal = igvTotal;
            inValue.total = total;
            inValue.activo = activo;
            SoftPetBussiness.DocumentoDePagoClient.modificar_Documento_De_PagoResponse retVal = ((SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago)(this)).modificar_Documento_De_Pago(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.DocumentoDePagoClient.modificar_Documento_De_PagoResponse> SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago.modificar_Documento_De_PagoAsync(SoftPetBussiness.DocumentoDePagoClient.modificar_Documento_De_PagoRequest request) {
            return base.Channel.modificar_Documento_De_PagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.DocumentoDePagoClient.modificar_Documento_De_PagoResponse> modificar_Documento_De_PagoAsync(int documentoPagoId, int metodoDePagoId, int personaId, string tipoDocumento, string serie, string numero, string fechaEmision, string estado, double subtotal, double igvTotal, double total, bool activo) {
            SoftPetBussiness.DocumentoDePagoClient.modificar_Documento_De_PagoRequest inValue = new SoftPetBussiness.DocumentoDePagoClient.modificar_Documento_De_PagoRequest();
            inValue.documentoPagoId = documentoPagoId;
            inValue.metodoDePagoId = metodoDePagoId;
            inValue.personaId = personaId;
            inValue.tipoDocumento = tipoDocumento;
            inValue.serie = serie;
            inValue.numero = numero;
            inValue.fechaEmision = fechaEmision;
            inValue.estado = estado;
            inValue.subtotal = subtotal;
            inValue.igvTotal = igvTotal;
            inValue.total = total;
            inValue.activo = activo;
            return ((SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago)(this)).modificar_Documento_De_PagoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.DocumentoDePagoClient.eliminar_Documento_De_PagoResponse SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago.eliminar_Documento_De_Pago(SoftPetBussiness.DocumentoDePagoClient.eliminar_Documento_De_PagoRequest request) {
            return base.Channel.eliminar_Documento_De_Pago(request);
        }
        
        public int eliminar_Documento_De_Pago(int arg0) {
            SoftPetBussiness.DocumentoDePagoClient.eliminar_Documento_De_PagoRequest inValue = new SoftPetBussiness.DocumentoDePagoClient.eliminar_Documento_De_PagoRequest();
            inValue.arg0 = arg0;
            SoftPetBussiness.DocumentoDePagoClient.eliminar_Documento_De_PagoResponse retVal = ((SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago)(this)).eliminar_Documento_De_Pago(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.DocumentoDePagoClient.eliminar_Documento_De_PagoResponse> SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago.eliminar_Documento_De_PagoAsync(SoftPetBussiness.DocumentoDePagoClient.eliminar_Documento_De_PagoRequest request) {
            return base.Channel.eliminar_Documento_De_PagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.DocumentoDePagoClient.eliminar_Documento_De_PagoResponse> eliminar_Documento_De_PagoAsync(int arg0) {
            SoftPetBussiness.DocumentoDePagoClient.eliminar_Documento_De_PagoRequest inValue = new SoftPetBussiness.DocumentoDePagoClient.eliminar_Documento_De_PagoRequest();
            inValue.arg0 = arg0;
            return ((SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago)(this)).eliminar_Documento_De_PagoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.DocumentoDePagoClient.obtener_por_idResponse SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago.obtener_por_id(SoftPetBussiness.DocumentoDePagoClient.obtener_por_idRequest request) {
            return base.Channel.obtener_por_id(request);
        }
        
        public SoftPetBussiness.DocumentoDePagoClient.documentoPagoDto obtener_por_id(int id) {
            SoftPetBussiness.DocumentoDePagoClient.obtener_por_idRequest inValue = new SoftPetBussiness.DocumentoDePagoClient.obtener_por_idRequest();
            inValue.id = id;
            SoftPetBussiness.DocumentoDePagoClient.obtener_por_idResponse retVal = ((SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago)(this)).obtener_por_id(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.DocumentoDePagoClient.obtener_por_idResponse> SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago.obtener_por_idAsync(SoftPetBussiness.DocumentoDePagoClient.obtener_por_idRequest request) {
            return base.Channel.obtener_por_idAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.DocumentoDePagoClient.obtener_por_idResponse> obtener_por_idAsync(int id) {
            SoftPetBussiness.DocumentoDePagoClient.obtener_por_idRequest inValue = new SoftPetBussiness.DocumentoDePagoClient.obtener_por_idRequest();
            inValue.id = id;
            return ((SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago)(this)).obtener_por_idAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.DocumentoDePagoClient.listar_todosResponse SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago.listar_todos(SoftPetBussiness.DocumentoDePagoClient.listar_todosRequest request) {
            return base.Channel.listar_todos(request);
        }
        
        public SoftPetBussiness.DocumentoDePagoClient.documentoPagoDto[] listar_todos() {
            SoftPetBussiness.DocumentoDePagoClient.listar_todosRequest inValue = new SoftPetBussiness.DocumentoDePagoClient.listar_todosRequest();
            SoftPetBussiness.DocumentoDePagoClient.listar_todosResponse retVal = ((SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago)(this)).listar_todos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.DocumentoDePagoClient.listar_todosResponse> SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago.listar_todosAsync(SoftPetBussiness.DocumentoDePagoClient.listar_todosRequest request) {
            return base.Channel.listar_todosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.DocumentoDePagoClient.listar_todosResponse> listar_todosAsync() {
            SoftPetBussiness.DocumentoDePagoClient.listar_todosRequest inValue = new SoftPetBussiness.DocumentoDePagoClient.listar_todosRequest();
            return ((SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago)(this)).listar_todosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.DocumentoDePagoClient.GeneracionDeSiguienteBoletaOFacturaResponse SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago.GeneracionDeSiguienteBoletaOFactura(SoftPetBussiness.DocumentoDePagoClient.GeneracionDeSiguienteBoletaOFacturaRequest request) {
            return base.Channel.GeneracionDeSiguienteBoletaOFactura(request);
        }
        
        public string[] GeneracionDeSiguienteBoletaOFactura(string tipoDocumento) {
            SoftPetBussiness.DocumentoDePagoClient.GeneracionDeSiguienteBoletaOFacturaRequest inValue = new SoftPetBussiness.DocumentoDePagoClient.GeneracionDeSiguienteBoletaOFacturaRequest();
            inValue.tipoDocumento = tipoDocumento;
            SoftPetBussiness.DocumentoDePagoClient.GeneracionDeSiguienteBoletaOFacturaResponse retVal = ((SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago)(this)).GeneracionDeSiguienteBoletaOFactura(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.DocumentoDePagoClient.GeneracionDeSiguienteBoletaOFacturaResponse> SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago.GeneracionDeSiguienteBoletaOFacturaAsync(SoftPetBussiness.DocumentoDePagoClient.GeneracionDeSiguienteBoletaOFacturaRequest request) {
            return base.Channel.GeneracionDeSiguienteBoletaOFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.DocumentoDePagoClient.GeneracionDeSiguienteBoletaOFacturaResponse> GeneracionDeSiguienteBoletaOFacturaAsync(string tipoDocumento) {
            SoftPetBussiness.DocumentoDePagoClient.GeneracionDeSiguienteBoletaOFacturaRequest inValue = new SoftPetBussiness.DocumentoDePagoClient.GeneracionDeSiguienteBoletaOFacturaRequest();
            inValue.tipoDocumento = tipoDocumento;
            return ((SoftPetBussiness.DocumentoDePagoClient.DocumentosDePago)(this)).GeneracionDeSiguienteBoletaOFacturaAsync(inValue);
        }
    }
}
