USE petmedicalcare;

-- Desactivamos la revisión de llaves foráneas para evitar errores de bloqueo
SET FOREIGN_KEY_CHECKS = 0;

-- 1. Tablas de Detalles / Transaccionales (Hijos)
DROP TABLE IF EXISTS `DETALLES_DOCUMENTO_DE_PAGO`;
DROP TABLE IF EXISTS `DETALLES_RECETA`;
DROP TABLE IF EXISTS `DETALLES_SERVICIO`;
DROP TABLE IF EXISTS `HORARIOS_LABORALES`;
DROP TABLE IF EXISTS `RECETAS_MEDICAS`;
DROP TABLE IF EXISTS `DOCUMENTOS_DE_PAGO`;
DROP TABLE IF EXISTS `CITAS_ATENCION`;

-- 2. Tablas Intermedias / Entidades (Padres intermedios)
DROP TABLE IF EXISTS `PRODUCTOS`;
DROP TABLE IF EXISTS `SERVICIOS`;
DROP TABLE IF EXISTS `TIPOS_PRODUCTO`;
DROP TABLE IF EXISTS `TIPOS_SERVICIO`;
DROP TABLE IF EXISTS `MASCOTAS`;
DROP TABLE IF EXISTS `VETERINARIOS`;
DROP TABLE IF EXISTS `ROLES_USUARIO`;

-- 3. Tablas Maestras (Padres principales)
DROP TABLE IF EXISTS `PERSONAS`;
DROP TABLE IF EXISTS `ROLES`;
DROP TABLE IF EXISTS `METODOS_DE_PAGO`;
DROP TABLE IF EXISTS `USUARIOS`;

-- Reactivamos la revisión de llaves
SET FOREIGN_KEY_CHECKS = 1;