USE petmedicalcare;

-- ==========================================
-- 1. TABLAS MAESTRAS
-- ==========================================

-- Tabla: USUARIOS
-- Nota: Se ha verificado que USERNAME y CORREO no tengan restricción UNIQUE.
CREATE TABLE IF NOT EXISTS USUARIOS (
  USUARIO_ID INT NOT NULL AUTO_INCREMENT,
  USERNAME VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL COMMENT 'Hash de la contraseña',
  CORREO VARCHAR(150) NULL DEFAULT NULL,
  ACTIVO TINYINT NULL DEFAULT NULL,
  USUARIO_CREADOR VARCHAR(50) NULL DEFAULT NULL,
  FECHA_CREACION DATETIME NULL DEFAULT NULL,
  USUARIO_MODIFICADOR VARCHAR(50) NULL DEFAULT NULL,
  FECHA_MODIFICACION DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (USUARIO_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

-- Tabla: METODOS_DE_PAGO
CREATE TABLE IF NOT EXISTS METODOS_DE_PAGO (
  METODO_DE_PAGO_ID INT NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(60) NOT NULL,
  ACTIVO TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (METODO_DE_PAGO_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

-- Tabla: ROLES
CREATE TABLE IF NOT EXISTS ROLES (
  ROL_ID INT NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(50) NOT NULL,
  ACTIVO TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (ROL_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

-- Tabla: TIPOS_PRODUCTO
CREATE TABLE IF NOT EXISTS TIPOS_PRODUCTO (
  TIPO_PRODUCTO_ID INT NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(80) NOT NULL,
  DESCRIPCION VARCHAR(200) NULL DEFAULT NULL,
  ACTIVO TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (TIPO_PRODUCTO_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

-- Tabla: TIPOS_SERVICIO
CREATE TABLE IF NOT EXISTS TIPOS_SERVICIO (
  TIPO_SERVICIO_ID INT NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(80) NOT NULL,
  DESCRIPCION VARCHAR(200) NULL DEFAULT NULL,
  ACTIVO TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (TIPO_SERVICIO_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

-- ==========================================
-- 2. TABLAS INTERMEDIAS
-- ==========================================

-- Tabla: PERSONAS
CREATE TABLE IF NOT EXISTS PERSONAS (
  PERSONA_ID INT NOT NULL AUTO_INCREMENT,
  USUARIO_ID INT NOT NULL,
  NOMBRE VARCHAR(120) NOT NULL,
  DIRECCION VARCHAR(200) NULL DEFAULT NULL,
  TELEFONO VARCHAR(20) NULL DEFAULT NULL,
  SEXO CHAR(1) NULL DEFAULT NULL COMMENT 'Valores: M, F, O',
  NRO_DOCUMENTO VARCHAR(20) NULL DEFAULT NULL,
  RUC VARCHAR(11) NULL DEFAULT NULL,
  TIPO_DOCUMENTO VARCHAR(60) NULL DEFAULT NULL,
  ACTIVO TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (PERSONA_ID),
  INDEX fk_PERSONAS_USUARIOS1_idx (USUARIO_ID ASC) VISIBLE,
  CONSTRAINT fk_PERSONAS_USUARIOS1
    FOREIGN KEY (USUARIO_ID)
    REFERENCES USUARIOS (USUARIO_ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

-- Tabla: ROLES_USUARIO
CREATE TABLE IF NOT EXISTS ROLES_USUARIO (
  ROL_USUARIO_ID INT NOT NULL AUTO_INCREMENT,
  ROL_ID INT NOT NULL,
  USUARIO_ID INT NOT NULL,
  ACTIVO TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (ROL_USUARIO_ID),
  UNIQUE INDEX uq_roles_usuario (ROL_ID ASC, USUARIO_ID ASC) VISIBLE,
  CONSTRAINT fk_ROLES_USUARIO_ROLES
    FOREIGN KEY (ROL_ID) REFERENCES ROLES (ROL_ID)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_ROLES_USUARIO_USUARIOS1
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS (USUARIO_ID)
    ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

-- Tabla: PRODUCTOS
CREATE TABLE IF NOT EXISTS PRODUCTOS (
  PRODUCTO_ID INT NOT NULL AUTO_INCREMENT,
  TIPO_PRODUCTO_ID INT NOT NULL,
  NOMBRE VARCHAR(120) NOT NULL,
  PRESENTACION VARCHAR(120) NULL DEFAULT NULL,
  PRECIO_UNITARIO DECIMAL(10,2) NULL DEFAULT NULL,
  STOCK INT NULL DEFAULT NULL,
  ACTIVO TINYINT(1) NULL DEFAULT NULL,
  USUARIO_CREADOR VARCHAR(50) NULL DEFAULT NULL,
  FECHA_CREACION DATETIME NULL DEFAULT NULL,
  USUARIO_MODIFICADOR VARCHAR(50) NULL DEFAULT NULL,
  FECHA_MODIFICACION DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (PRODUCTO_ID),
  CONSTRAINT fk_PRODUCTOS_TIPOS_PRODUCTO1
    FOREIGN KEY (TIPO_PRODUCTO_ID) REFERENCES TIPOS_PRODUCTO (TIPO_PRODUCTO_ID)
    ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

-- Tabla: SERVICIOS
CREATE TABLE IF NOT EXISTS SERVICIOS (
  SERVICIO_ID INT NOT NULL AUTO_INCREMENT,
  TIPO_SERVICIO_ID INT NOT NULL,
  NOMBRE VARCHAR(100) NOT NULL,
  DESCRIPCION VARCHAR(200) NULL DEFAULT NULL,
  COSTO DECIMAL(10,2) NULL DEFAULT NULL,
  ESTADO VARCHAR(20) NULL DEFAULT NULL,
  ACTIVO TINYINT(1) NULL DEFAULT NULL,
  USUARIO_CREADOR VARCHAR(50) NULL DEFAULT NULL,
  FECHA_CREACION DATETIME NULL DEFAULT NULL,
  USUARIO_MODIFICADOR VARCHAR(50) NULL DEFAULT NULL,
  FECHA_MODIFICACION DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (SERVICIO_ID),
  CONSTRAINT fk_SERVICIOS_TIPOS_SERVICIO1
    FOREIGN KEY (TIPO_SERVICIO_ID) REFERENCES TIPOS_SERVICIO (TIPO_SERVICIO_ID)
    ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

-- ==========================================
-- 3. TABLAS DE NEGOCIO
-- ==========================================

-- Tabla: MASCOTAS
CREATE TABLE IF NOT EXISTS MASCOTAS (
  MASCOTA_ID INT NOT NULL AUTO_INCREMENT,
  PERSONA_ID INT NOT NULL,
  NOMBRE VARCHAR(80) NOT NULL,
  ESPECIE VARCHAR(40) NULL DEFAULT NULL,
  SEXO CHAR(1) NULL DEFAULT NULL,
  RAZA VARCHAR(60) NULL DEFAULT NULL,
  COLOR VARCHAR(40) NULL DEFAULT NULL,
  FECHA_DEFUNCION DATE NULL DEFAULT NULL,
  ACTIVO TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (MASCOTA_ID),
  CONSTRAINT fk_MASCOTAS_PERSONAS1
    FOREIGN KEY (PERSONA_ID) REFERENCES PERSONAS (PERSONA_ID)
    ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

-- Tabla: VETERINARIOS
CREATE TABLE IF NOT EXISTS VETERINARIOS (
  VETERINARIO_ID INT NOT NULL AUTO_INCREMENT,
  PERSONA_ID INT NOT NULL,
  FECHA_DE_CONTRATACION DATE NULL DEFAULT NULL,
  ESTADO VARCHAR(20) NULL DEFAULT NULL,
  ESPECIALIDAD VARCHAR(50) NULL DEFAULT NULL,
  ACTIVO TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (VETERINARIO_ID),
  CONSTRAINT fk_VETERINARIOS_PERSONAS1
    FOREIGN KEY (PERSONA_ID) REFERENCES PERSONAS (PERSONA_ID)
    ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

-- Tabla: HORARIOS_LABORALES
CREATE TABLE IF NOT EXISTS HORARIOS_LABORALES (
  HORARIO_LABORAL_ID INT NOT NULL AUTO_INCREMENT,
  VETERINARIO_ID INT NOT NULL,
  FECHA DATE NULL DEFAULT NULL,
  ESTADO VARCHAR(45) NULL DEFAULT NULL,
  HORA_INICIO DATETIME NULL DEFAULT NULL,
  HORA_FIN DATETIME NULL DEFAULT NULL,
  ACTIVO TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (HORARIO_LABORAL_ID),
  CONSTRAINT fk_HORARIOS_LABORALES_VETERINARIOS1
    FOREIGN KEY (VETERINARIO_ID) REFERENCES VETERINARIOS (VETERINARIO_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

-- Tabla: CITAS_ATENCION
CREATE TABLE IF NOT EXISTS CITAS_ATENCION (
  CITA_ID INT NOT NULL AUTO_INCREMENT,
  VETERINARIO_ID INT NOT NULL,
  MASCOTA_ID INT NOT NULL,
  FECHA_REGISTRO DATE NULL DEFAULT NULL,
  FECHA_HORA_INICIO DATETIME NULL DEFAULT NULL,
  FECHA_HORA_FIN DATETIME NULL DEFAULT NULL,
  PESO_MASCOTA DECIMAL(6,2) NULL DEFAULT NULL,
  MONTO DECIMAL(10,2) NULL DEFAULT NULL,
  ESTADO_CITA VARCHAR(20) NULL DEFAULT NULL,
  OBSERVACION VARCHAR(250) NULL DEFAULT NULL,
  ACTIVO TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (CITA_ID),
  CONSTRAINT fk_CITAS_ATENCION_MASCOTAS1
    FOREIGN KEY (MASCOTA_ID) REFERENCES MASCOTAS (MASCOTA_ID)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_CITAS_ATENCION_VETERINARIOS1
    FOREIGN KEY (VETERINARIO_ID) REFERENCES VETERINARIOS (VETERINARIO_ID)
    ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

-- Tabla: RECETAS_MEDICAS
CREATE TABLE IF NOT EXISTS RECETAS_MEDICAS (
  RECETA_MEDICA_ID INT NOT NULL AUTO_INCREMENT,
  CITA_ID INT NOT NULL,
  FECHA_EMISION DATE NOT NULL,
  VIGENCIA_HASTA DATE NULL DEFAULT NULL,
  DIAGNOSTICO VARCHAR(250) NULL DEFAULT NULL,
  OBSERVACIONES VARCHAR(300) NULL DEFAULT NULL,
  ACTIVO TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (RECETA_MEDICA_ID),
  CONSTRAINT fk_RECETAS_MEDICAS_CITAS_ATENCION1
    FOREIGN KEY (CITA_ID) REFERENCES CITAS_ATENCION (CITA_ID)
    ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

-- Tabla: DETALLES_RECETA
CREATE TABLE IF NOT EXISTS DETALLES_RECETA (
  DETALLE_RECETA_ID INT NOT NULL AUTO_INCREMENT,
  RECETA_MEDICA_ID INT NOT NULL,
  DESCRIPCION_MEDICAMENTO VARCHAR(150) NOT NULL,
  PRESENTACION VARCHAR(50) NULL DEFAULT NULL,
  VIA_ADMINISTRACION VARCHAR(20) NULL DEFAULT NULL,
  DOSIS VARCHAR(50) NULL DEFAULT NULL,
  FRECUENCIA VARCHAR(50) NULL DEFAULT NULL,
  DURACION VARCHAR(50) NULL DEFAULT NULL,
  INDICACION VARCHAR(250) NULL DEFAULT NULL,
  CANTIDAD VARCHAR(50) NULL DEFAULT NULL,
  ACTIVO TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (DETALLE_RECETA_ID),
  CONSTRAINT fk_DETALLES_RECETA_RECETAS_MEDICAS1
    FOREIGN KEY (RECETA_MEDICA_ID) REFERENCES RECETAS_MEDICAS (RECETA_MEDICA_ID)
    ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

-- Tabla: DETALLES_SERVICIO
CREATE TABLE IF NOT EXISTS DETALLES_SERVICIO (
  DETALLE_SERVICIO_ID INT NOT NULL AUTO_INCREMENT,
  CITA_ID INT NOT NULL,
  SERVICIO_ID INT NOT NULL,
  DESCRIPCION VARCHAR(200) NULL DEFAULT NULL,
  COSTO DECIMAL(10,2) NULL DEFAULT NULL,
  ACTIVO TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (DETALLE_SERVICIO_ID),
  CONSTRAINT fk_DETALLES_SERVICIO_CITAS_ATENCION1
    FOREIGN KEY (CITA_ID) REFERENCES CITAS_ATENCION (CITA_ID)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_DETALLES_SERVICIO_SERVICIOS1
    FOREIGN KEY (SERVICIO_ID) REFERENCES SERVICIOS (SERVICIO_ID)
    ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

-- Tabla: DOCUMENTOS_DE_PAGO
CREATE TABLE IF NOT EXISTS DOCUMENTOS_DE_PAGO (
  DOCUMENTO_DE_PAGO_ID INT NOT NULL AUTO_INCREMENT,
  METODO_DE_PAGO_ID INT NOT NULL,
  PERSONA_ID INT NULL DEFAULT NULL,
  TIPO_DOCUMENTO VARCHAR(50) NOT NULL,
  SERIE VARCHAR(10) NOT NULL,
  NUMERO VARCHAR(12) NOT NULL,
  FECHA_EMISION DATE NOT NULL,
  ESTADO VARCHAR(20) NULL DEFAULT NULL,
  SUBTOTAL DECIMAL(12,2) NULL DEFAULT NULL,
  IGV_TOTAL DECIMAL(12,2) NULL DEFAULT NULL,
  TOTAL DECIMAL(12,2) NULL DEFAULT NULL,
  ACTIVO TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (DOCUMENTO_DE_PAGO_ID),
  UNIQUE INDEX uq_doc_pago_serie_numero (SERIE ASC, NUMERO ASC) VISIBLE,
  CONSTRAINT fk_DOC_PAGO_PERSONAS1
    FOREIGN KEY (PERSONA_ID) REFERENCES PERSONAS (PERSONA_ID)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_DOCUMENTOS_DE_PAGO_METODOS_DE_PAGO1
    FOREIGN KEY (METODO_DE_PAGO_ID) REFERENCES METODOS_DE_PAGO (METODO_DE_PAGO_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

-- Tabla: DETALLES_DOCUMENTO_DE_PAGO
CREATE TABLE IF NOT EXISTS DETALLES_DOCUMENTO_DE_PAGO (
  DDDP_ID INT NOT NULL AUTO_INCREMENT,
  DOCUMENTO_DE_PAGO_ID INT NOT NULL,
  SERVICIO_ID INT NULL DEFAULT NULL,
  PRODUCTO_ID INT NULL DEFAULT NULL,
  NRO_ITEM INT NULL DEFAULT NULL,
  DESCRIPCION VARCHAR(200) NULL DEFAULT NULL,
  CANTIDAD INT NULL DEFAULT NULL,
  PRECIO_UNITARIO DECIMAL(10,2) NULL DEFAULT NULL,
  VALOR_VENTA DECIMAL(12,2) NULL DEFAULT NULL,
  ACTIVO TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (DDDP_ID),
  CONSTRAINT fk_DDDP_DOCUMENTO_DE_PAGO1
    FOREIGN KEY (DOCUMENTO_DE_PAGO_ID) REFERENCES DOCUMENTOS_DE_PAGO (DOCUMENTO_DE_PAGO_ID)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_DDDP_PRODUCTOS1
    FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS (PRODUCTO_ID)
    ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_DDDP_SERVICIOS1
    FOREIGN KEY (SERVICIO_ID) REFERENCES SERVICIOS (SERVICIO_ID)
    ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;