USE petmedicalcare;

-- =========================================================
-- 1. AUDITORÍA USUARIOS (Creation / Modification)
-- =========================================================
DROP TRIGGER IF EXISTS trg_USUARIOS_bi_audit;
DELIMITER $$
CREATE TRIGGER trg_USUARIOS_bi_audit
BEFORE INSERT ON USUARIOS
FOR EACH ROW
BEGIN
  DECLARE v_user VARCHAR(50);
  SET v_user = COALESCE(NULLIF(@app_user, ''), SUBSTRING_INDEX(USER(), '@', 1));

  IF NEW.FECHA_CREACION IS NULL THEN SET NEW.FECHA_CREACION = NOW(); END IF;
  IF NEW.FECHA_MODIFICACION IS NULL THEN SET NEW.FECHA_MODIFICACION = NOW(); END IF;
  IF NEW.USUARIO_CREADOR IS NULL OR NEW.USUARIO_CREADOR = '' THEN SET NEW.USUARIO_CREADOR = v_user; END IF;
  IF NEW.USUARIO_MODIFICADOR IS NULL OR NEW.USUARIO_MODIFICADOR = '' THEN SET NEW.USUARIO_MODIFICADOR = v_user; END IF;
END $$
DELIMITER ;

DROP TRIGGER IF EXISTS trg_USUARIOS_bu_audit;
DELIMITER $$
CREATE TRIGGER trg_USUARIOS_bu_audit
BEFORE UPDATE ON USUARIOS
FOR EACH ROW
BEGIN
  DECLARE v_user VARCHAR(50);
  SET v_user = COALESCE(NULLIF(@app_user, ''), SUBSTRING_INDEX(USER(), '@', 1));

  SET NEW.FECHA_MODIFICACION = NOW();
  SET NEW.USUARIO_MODIFICADOR = v_user;
END $$
DELIMITER ;

-- =========================================================
-- 2. AUDITORÍA SERVICIOS (Creation / Modification)
-- =========================================================
DROP TRIGGER IF EXISTS trg_SERVICIOS_bi_audit;
DELIMITER $$
CREATE TRIGGER trg_SERVICIOS_bi_audit
BEFORE INSERT ON SERVICIOS
FOR EACH ROW
BEGIN
  DECLARE v_user VARCHAR(50);
  SET v_user = COALESCE(NULLIF(@app_user, ''), SUBSTRING_INDEX(USER(), '@', 1));

  IF NEW.FECHA_CREACION IS NULL THEN SET NEW.FECHA_CREACION = NOW(); END IF;
  IF NEW.FECHA_MODIFICACION IS NULL THEN SET NEW.FECHA_MODIFICACION = NOW(); END IF;
  IF NEW.USUARIO_CREADOR IS NULL OR NEW.USUARIO_CREADOR = '' THEN SET NEW.USUARIO_CREADOR = v_user; END IF;
  IF NEW.USUARIO_MODIFICADOR IS NULL OR NEW.USUARIO_MODIFICADOR = '' THEN SET NEW.USUARIO_MODIFICADOR = v_user; END IF;
END $$
DELIMITER ;

DROP TRIGGER IF EXISTS trg_SERVICIOS_bu_audit;
DELIMITER $$
CREATE TRIGGER trg_SERVICIOS_bu_audit
BEFORE UPDATE ON SERVICIOS
FOR EACH ROW
BEGIN
  DECLARE v_user VARCHAR(50);
  SET v_user = COALESCE(NULLIF(@app_user, ''), SUBSTRING_INDEX(USER(), '@', 1));

  SET NEW.FECHA_MODIFICACION = NOW();
  SET NEW.USUARIO_MODIFICADOR = v_user;
END $$
DELIMITER ;

-- =========================================================
-- 3. AUDITORÍA PRODUCTOS (Creation / Modification)
-- =========================================================
DROP TRIGGER IF EXISTS trg_PRODUCTOS_bi_audit;
DELIMITER $$
CREATE TRIGGER trg_PRODUCTOS_bi_audit
BEFORE INSERT ON PRODUCTOS
FOR EACH ROW
BEGIN
  DECLARE v_user VARCHAR(50);
  SET v_user = COALESCE(NULLIF(@app_user, ''), SUBSTRING_INDEX(USER(), '@', 1));

  IF NEW.FECHA_CREACION IS NULL THEN SET NEW.FECHA_CREACION = NOW(); END IF;
  IF NEW.FECHA_MODIFICACION IS NULL THEN SET NEW.FECHA_MODIFICACION = NOW(); END IF;
  IF NEW.USUARIO_CREADOR IS NULL OR NEW.USUARIO_CREADOR = '' THEN SET NEW.USUARIO_CREADOR = v_user; END IF;
  IF NEW.USUARIO_MODIFICADOR IS NULL OR NEW.USUARIO_MODIFICADOR = '' THEN SET NEW.USUARIO_MODIFICADOR = v_user; END IF;
END $$
DELIMITER ;

DROP TRIGGER IF EXISTS trg_PRODUCTOS_bu_audit;
DELIMITER $$
CREATE TRIGGER trg_PRODUCTOS_bu_audit
BEFORE UPDATE ON PRODUCTOS
FOR EACH ROW
BEGIN
  DECLARE v_user VARCHAR(50);
  SET v_user = COALESCE(NULLIF(@app_user, ''), SUBSTRING_INDEX(USER(), '@', 1));

  SET NEW.FECHA_MODIFICACION = NOW();
  SET NEW.USUARIO_MODIFICADOR = v_user;
END $$
DELIMITER ;

-- =========================================================
-- 4. INTEGRIDAD REFERENCIAL (Cascada Manual en Citas)
-- =========================================================
DROP TRIGGER IF EXISTS trg_citas_atencion_before_delete;
DELIMITER $$
CREATE TRIGGER trg_citas_atencion_before_delete
BEFORE DELETE ON CITAS_ATENCION
FOR EACH ROW
BEGIN
    -- 1. Eliminar los detalles de servicio asociados a la cita
    DELETE FROM DETALLES_SERVICIO 
    WHERE CITA_ID = OLD.CITA_ID;

    -- 2. Eliminar las recetas médicas asociadas
    DELETE FROM RECETAS_MEDICAS 
    WHERE CITA_ID = OLD.CITA_ID;
END$$
DELIMITER ;