-- =====================================================
-- DDL CORREGIDO para SQL Server (MSSQL)
-- Solución error: cycles or multiple cascade paths
-- =====================================================

USE master;
GO

-- Crear base de datos limpia si es necesario
IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'petmedicalcare')
BEGIN
    CREATE DATABASE petmedicalcare;
END
GO

USE petmedicalcare;
GO

-- Borrar tablas en orden inverso para evitar errores de FK al limpiar
IF OBJECT_ID('ROLES_USUARIO', 'U') IS NOT NULL DROP TABLE ROLES_USUARIO;
IF OBJECT_ID('ROLES', 'U') IS NOT NULL DROP TABLE ROLES;
IF OBJECT_ID('HORARIOS_LABORALES', 'U') IS NOT NULL DROP TABLE HORARIOS_LABORALES;
IF OBJECT_ID('DETALLES_SERVICIO', 'U') IS NOT NULL DROP TABLE DETALLES_SERVICIO;
IF OBJECT_ID('DETALLES_RECETA', 'U') IS NOT NULL DROP TABLE DETALLES_RECETA;
IF OBJECT_ID('RECETAS_MEDICAS', 'U') IS NOT NULL DROP TABLE RECETAS_MEDICAS;
IF OBJECT_ID('DETALLES_DOCUMENTO_DE_PAGO', 'U') IS NOT NULL DROP TABLE DETALLES_DOCUMENTO_DE_PAGO;
IF OBJECT_ID('SERVICIOS', 'U') IS NOT NULL DROP TABLE SERVICIOS;
IF OBJECT_ID('TIPOS_SERVICIO', 'U') IS NOT NULL DROP TABLE TIPOS_SERVICIO;
IF OBJECT_ID('PRODUCTOS', 'U') IS NOT NULL DROP TABLE PRODUCTOS;
IF OBJECT_ID('TIPOS_PRODUCTO', 'U') IS NOT NULL DROP TABLE TIPOS_PRODUCTO;
IF OBJECT_ID('DOCUMENTOS_DE_PAGO', 'U') IS NOT NULL DROP TABLE DOCUMENTOS_DE_PAGO;
IF OBJECT_ID('METODOS_DE_PAGO', 'U') IS NOT NULL DROP TABLE METODOS_DE_PAGO;
IF OBJECT_ID('CITAS_ATENCION', 'U') IS NOT NULL DROP TABLE CITAS_ATENCION;
IF OBJECT_ID('VETERINARIOS', 'U') IS NOT NULL DROP TABLE VETERINARIOS;
IF OBJECT_ID('MASCOTAS', 'U') IS NOT NULL DROP TABLE MASCOTAS;
IF OBJECT_ID('PERSONAS', 'U') IS NOT NULL DROP TABLE PERSONAS;
IF OBJECT_ID('USUARIOS', 'U') IS NOT NULL DROP TABLE USUARIOS;
GO

-- -----------------------------------------------------
-- USUARIOS
-- -----------------------------------------------------
CREATE TABLE USUARIOS (
  USUARIO_ID INT IDENTITY(1,1) NOT NULL,
  USERNAME VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  CORREO VARCHAR(150) NULL,
  ACTIVO BIT NULL,
  USUARIO_CREADOR VARCHAR(50) NULL,
  FECHA_CREACION DATETIME NULL,
  USUARIO_MODIFICADOR VARCHAR(50) NULL,
  FECHA_MODIFICACION DATETIME NULL,
  CONSTRAINT PK_USUARIOS PRIMARY KEY (USUARIO_ID),
  CONSTRAINT UQ_USUARIOS_USERNAME UNIQUE (USERNAME),
  CONSTRAINT UQ_USUARIOS_CORREO UNIQUE (CORREO)
);
GO

-- -----------------------------------------------------
-- PERSONAS
-- -----------------------------------------------------
CREATE TABLE PERSONAS (
  PERSONA_ID INT IDENTITY(1,1) NOT NULL,
  USUARIO_ID INT NOT NULL,
  NOMBRE VARCHAR(120) NOT NULL,
  DIRECCION VARCHAR(200) NULL,
  TELEFONO VARCHAR(20) NULL,
  SEXO CHAR(1) NULL,
  NRO_DOCUMENTO VARCHAR(20) NULL,
  RUC VARCHAR(11) NULL,
  TIPO_DOCUMENTO VARCHAR(60) NULL,
  ACTIVO BIT NULL,
  CONSTRAINT PK_PERSONAS PRIMARY KEY (PERSONA_ID),
  CONSTRAINT FK_PERSONAS_USUARIOS 
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS (USUARIO_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION 
);
GO

-- -----------------------------------------------------
-- MASCOTAS
-- -----------------------------------------------------
CREATE TABLE MASCOTAS (
  MASCOTA_ID INT IDENTITY(1,1) NOT NULL,
  PERSONA_ID INT NOT NULL,
  NOMBRE VARCHAR(80) NOT NULL,
  ESPECIE VARCHAR(40) NULL,
  SEXO CHAR(1) NULL,
  RAZA VARCHAR(60) NULL,
  COLOR VARCHAR(40) NULL,
  FECHA_DEFUNCION DATE NULL,
  ACTIVO BIT NULL,
  CONSTRAINT PK_MASCOTAS PRIMARY KEY (MASCOTA_ID),
  CONSTRAINT FK_MASCOTAS_PERSONAS 
    FOREIGN KEY (PERSONA_ID) REFERENCES PERSONAS (PERSONA_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
GO

-- -----------------------------------------------------
-- VETERINARIOS
-- -----------------------------------------------------
CREATE TABLE VETERINARIOS (
  VETERINARIO_ID INT IDENTITY(1,1) NOT NULL,
  PERSONA_ID INT NOT NULL,
  FECHA_DE_CONTRATACION DATE NULL,
  ESTADO VARCHAR(20) NULL,
  ESPECIALIDAD VARCHAR(50) NULL,
  ACTIVO BIT NULL,
  CONSTRAINT PK_VETERINARIOS PRIMARY KEY (VETERINARIO_ID),
  CONSTRAINT FK_VETERINARIOS_PERSONAS 
    FOREIGN KEY (PERSONA_ID) REFERENCES PERSONAS (PERSONA_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
GO

-- -----------------------------------------------------
-- CITAS_ATENCION (Aquí estaba el conflicto principal)
-- -----------------------------------------------------
CREATE TABLE CITAS_ATENCION (
  CITA_ID INT IDENTITY(1,1) NOT NULL,
  VETERINARIO_ID INT NOT NULL,
  MASCOTA_ID INT NOT NULL,
  FECHA_REGISTRO DATE NULL,
  FECHA_HORA_INICIO DATETIME NULL,
  FECHA_HORA_FIN DATETIME NULL,
  PESO_MASCOTA DECIMAL(6,2) NULL,
  MONTO DECIMAL(10,2) NULL,
  ESTADO_CITA VARCHAR(20) NULL,
  OBSERVACION VARCHAR(250) NULL,
  ACTIVO BIT NULL,
  CONSTRAINT PK_CITAS_ATENCION PRIMARY KEY (CITA_ID),
  CONSTRAINT FK_CITAS_ATENCION_VETERINARIOS 
    FOREIGN KEY (VETERINARIO_ID) REFERENCES VETERINARIOS (VETERINARIO_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION, -- Cambiado a NO ACTION para evitar ciclos
  CONSTRAINT FK_CITAS_ATENCION_MASCOTAS 
    FOREIGN KEY (MASCOTA_ID) REFERENCES MASCOTAS (MASCOTA_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION  -- Cambiado a NO ACTION para evitar ciclos
);
GO

-- -----------------------------------------------------
-- METODOS_DE_PAGO
-- -----------------------------------------------------
CREATE TABLE METODOS_DE_PAGO (
  METODO_DE_PAGO_ID INT IDENTITY(1,1) NOT NULL,
  NOMBRE VARCHAR(60) NOT NULL,
  ACTIVO BIT NULL,
  CONSTRAINT PK_METODOS_DE_PAGO PRIMARY KEY (METODO_DE_PAGO_ID)
);
GO

-- -----------------------------------------------------
-- DOCUMENTOS_DE_PAGO
-- -----------------------------------------------------
CREATE TABLE DOCUMENTOS_DE_PAGO (
  DOCUMENTO_DE_PAGO_ID INT IDENTITY(1,1) NOT NULL,
  METODO_DE_PAGO_ID INT NOT NULL,
  PERSONA_ID INT NULL,
  TIPO_DOCUMENTO VARCHAR(50) NOT NULL,
  SERIE VARCHAR(10) NOT NULL,
  NUMERO VARCHAR(12) NOT NULL,
  FECHA_EMISION DATE NOT NULL,
  ESTADO VARCHAR(20) NULL,
  SUBTOTAL DECIMAL(12,2) NULL,
  IGV_TOTAL DECIMAL(12,2) NULL,
  TOTAL DECIMAL(12,2) NULL,
  ACTIVO BIT NULL,
  CONSTRAINT PK_DOCUMENTOS_DE_PAGO PRIMARY KEY (DOCUMENTO_DE_PAGO_ID),
  CONSTRAINT UQ_DOC_PAGO_SERIE_NUMERO UNIQUE (SERIE, NUMERO),
  CONSTRAINT FK_DOC_PAGO_PERSONAS 
    FOREIGN KEY (PERSONA_ID) REFERENCES PERSONAS (PERSONA_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_DOCUMENTOS_DE_PAGO_METODOS 
    FOREIGN KEY (METODO_DE_PAGO_ID) REFERENCES METODOS_DE_PAGO (METODO_DE_PAGO_ID)
);
GO

-- -----------------------------------------------------
-- TIPOS_PRODUCTO
-- -----------------------------------------------------
CREATE TABLE TIPOS_PRODUCTO (
  TIPO_PRODUCTO_ID INT IDENTITY(1,1) NOT NULL,
  NOMBRE VARCHAR(80) NOT NULL,
  DESCRIPCION VARCHAR(200) NULL,
  ACTIVO BIT NULL,
  CONSTRAINT PK_TIPOS_PRODUCTO PRIMARY KEY (TIPO_PRODUCTO_ID)
);
GO

-- -----------------------------------------------------
-- PRODUCTOS
-- -----------------------------------------------------
CREATE TABLE PRODUCTOS (
  PRODUCTO_ID INT IDENTITY(1,1) NOT NULL,
  TIPO_PRODUCTO_ID INT NOT NULL,
  NOMBRE VARCHAR(120) NOT NULL,
  PRESENTACION VARCHAR(120) NULL,
  PRECIO_UNITARIO DECIMAL(10,2) NULL,
  STOCK INT NULL,
  ACTIVO BIT NULL,
  USUARIO_CREADOR VARCHAR(50) NULL,
  FECHA_CREACION DATETIME NULL,
  USUARIO_MODIFICADOR VARCHAR(50) NULL,
  FECHA_MODIFICACION DATETIME NULL,
  CONSTRAINT PK_PRODUCTOS PRIMARY KEY (PRODUCTO_ID),
  CONSTRAINT FK_PRODUCTOS_TIPOS_PRODUCTO 
    FOREIGN KEY (TIPO_PRODUCTO_ID) REFERENCES TIPOS_PRODUCTO (TIPO_PRODUCTO_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
GO

-- -----------------------------------------------------
-- TIPOS_SERVICIO
-- -----------------------------------------------------
CREATE TABLE TIPOS_SERVICIO (
  TIPO_SERVICIO_ID INT IDENTITY(1,1) NOT NULL,
  NOMBRE VARCHAR(80) NOT NULL,
  DESCRIPCION VARCHAR(200) NULL,
  ACTIVO BIT NULL,
  CONSTRAINT PK_TIPOS_SERVICIO PRIMARY KEY (TIPO_SERVICIO_ID)
);
GO

-- -----------------------------------------------------
-- SERVICIOS
-- -----------------------------------------------------
CREATE TABLE SERVICIOS (
  SERVICIO_ID INT IDENTITY(1,1) NOT NULL,
  TIPO_SERVICIO_ID INT NOT NULL,
  NOMBRE VARCHAR(100) NOT NULL,
  DESCRIPCION VARCHAR(200) NULL,
  COSTO DECIMAL(10,2) NULL,
  ESTADO VARCHAR(20) NULL,
  ACTIVO BIT NULL,
  USUARIO_CREADOR VARCHAR(50) NULL,
  FECHA_CREACION DATETIME NULL,
  USUARIO_MODIFICADOR VARCHAR(50) NULL,
  FECHA_MODIFICACION DATETIME NULL,
  CONSTRAINT PK_SERVICIOS PRIMARY KEY (SERVICIO_ID),
  CONSTRAINT FK_SERVICIOS_TIPOS_SERVICIO 
    FOREIGN KEY (TIPO_SERVICIO_ID) REFERENCES TIPOS_SERVICIO (TIPO_SERVICIO_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
GO

-- -----------------------------------------------------
-- DETALLES_DOCUMENTO_DE_PAGO
-- -----------------------------------------------------
CREATE TABLE DETALLES_DOCUMENTO_DE_PAGO (
  DDDP_ID INT IDENTITY(1,1) NOT NULL,
  DOCUMENTO_DE_PAGO_ID INT NOT NULL,
  SERVICIO_ID INT NULL,
  PRODUCTO_ID INT NULL,
  NRO_ITEM INT NULL,
  DESCRIPCION VARCHAR(200) NULL,
  CANTIDAD INT NULL,
  PRECIO_UNITARIO DECIMAL(10,2) NULL,
  VALOR_VENTA DECIMAL(12,2) NULL,
  ACTIVO BIT NULL,
  CONSTRAINT PK_DETALLES_DOC_PAGO PRIMARY KEY (DDDP_ID),
  CONSTRAINT FK_DDDP_DOCUMENTO_DE_PAGO 
    FOREIGN KEY (DOCUMENTO_DE_PAGO_ID) REFERENCES DOCUMENTOS_DE_PAGO (DOCUMENTO_DE_PAGO_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_DDDP_PRODUCTOS 
    FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS (PRODUCTO_ID)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT FK_DDDP_SERVICIOS 
    FOREIGN KEY (SERVICIO_ID) REFERENCES SERVICIOS (SERVICIO_ID)
    ON DELETE SET NULL
    ON UPDATE NO ACTION
);
GO

-- -----------------------------------------------------
-- RECETAS_MEDICAS
-- -----------------------------------------------------
CREATE TABLE RECETAS_MEDICAS (
  RECETA_MEDICA_ID INT IDENTITY(1,1) NOT NULL,
  CITA_ID INT NOT NULL,
  FECHA_EMISION DATE NOT NULL,
  VIGENCIA_HASTA DATE NULL,
  DIAGNOSTICO VARCHAR(250) NULL,
  OBSERVACIONES VARCHAR(300) NULL,
  ACTIVO BIT NULL,
  CONSTRAINT PK_RECETAS_MEDICAS PRIMARY KEY (RECETA_MEDICA_ID),
  CONSTRAINT FK_RECETAS_MEDICAS_CITAS 
    FOREIGN KEY (CITA_ID) REFERENCES CITAS_ATENCION (CITA_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
GO

-- -----------------------------------------------------
-- DETALLES_RECETA
-- -----------------------------------------------------
CREATE TABLE DETALLES_RECETA (
  DETALLE_RECETA_ID INT IDENTITY(1,1) NOT NULL,
  RECETA_MEDICA_ID INT NOT NULL,
  DESCRIPCION_MEDICAMENTO VARCHAR(150) NOT NULL,
  PRESENTACION VARCHAR(50) NULL,
  VIA_ADMINISTRACION VARCHAR(20) NULL,
  DOSIS VARCHAR(50) NULL,
  FRECUENCIA VARCHAR(50) NULL,
  DURACION VARCHAR(50) NULL,
  INDICACION VARCHAR(250) NULL,
  CANTIDAD VARCHAR(50) NULL,
  ACTIVO BIT NULL,
  CONSTRAINT PK_DETALLES_RECETA PRIMARY KEY (DETALLE_RECETA_ID),
  CONSTRAINT FK_DETALLES_RECETA_RECETAS 
    FOREIGN KEY (RECETA_MEDICA_ID) REFERENCES RECETAS_MEDICAS (RECETA_MEDICA_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
GO

-- -----------------------------------------------------
-- DETALLES_SERVICIO
-- -----------------------------------------------------
CREATE TABLE DETALLES_SERVICIO (
  DETALLE_SERVICIO_ID INT IDENTITY(1,1) NOT NULL,
  CITA_ID INT NOT NULL,
  SERVICIO_ID INT NOT NULL,
  DESCRIPCION VARCHAR(200) NULL,
  COSTO DECIMAL(10,2) NULL,
  ACTIVO BIT NULL,
  CONSTRAINT PK_DETALLES_SERVICIO PRIMARY KEY (DETALLE_SERVICIO_ID),
  CONSTRAINT FK_DETALLES_SERVICIO_CITAS 
    FOREIGN KEY (CITA_ID) REFERENCES CITAS_ATENCION (CITA_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_DETALLES_SERVICIO_SERVICIOS 
    FOREIGN KEY (SERVICIO_ID) REFERENCES SERVICIOS (SERVICIO_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
GO

-- -----------------------------------------------------
-- HORARIOS_LABORALES
-- -----------------------------------------------------
CREATE TABLE HORARIOS_LABORALES (
  HORARIO_LABORAL_ID INT IDENTITY(1,1) NOT NULL,
  VETERINARIO_ID INT NOT NULL,
  FECHA DATE NULL,
  ESTADO VARCHAR(45) NULL,
  HORA_INICIO DATETIME NULL,
  HORA_FIN DATETIME NULL,
  ACTIVO BIT NULL,
  CONSTRAINT PK_HORARIOS_LABORALES PRIMARY KEY (HORARIO_LABORAL_ID),
  CONSTRAINT FK_HORARIOS_LABORALES_VETS 
    FOREIGN KEY (VETERINARIO_ID) REFERENCES VETERINARIOS (VETERINARIO_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
GO

-- -----------------------------------------------------
-- ROLES
-- -----------------------------------------------------
CREATE TABLE ROLES (
  ROL_ID INT IDENTITY(1,1) NOT NULL,
  NOMBRE VARCHAR(50) NOT NULL,
  ACTIVO BIT NULL,
  CONSTRAINT PK_ROLES PRIMARY KEY (ROL_ID)
);
GO

-- -----------------------------------------------------
-- ROLES_USUARIO
-- -----------------------------------------------------
CREATE TABLE ROLES_USUARIO (
  ROL_USUARIO_ID INT IDENTITY(1,1) NOT NULL,
  ROL_ID INT NOT NULL,
  USUARIO_ID INT NOT NULL,
  ACTIVO BIT NULL,
  CONSTRAINT PK_ROLES_USUARIO PRIMARY KEY (ROL_USUARIO_ID),
  CONSTRAINT UQ_ROLES_USUARIO UNIQUE (ROL_ID, USUARIO_ID),
  CONSTRAINT FK_ROLES_USUARIO_ROLES 
    FOREIGN KEY (ROL_ID) REFERENCES ROLES (ROL_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_ROLES_USUARIO_USUARIOS 
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS (USUARIO_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
GO