USE petmedicalcare;
GO

-- INSERT TRIGGER
IF OBJECT_ID('trg_SERVICIOS_audit_insert', 'TR') IS NOT NULL DROP TRIGGER trg_SERVICIOS_audit_insert;
GO

CREATE TRIGGER trg_SERVICIOS_audit_insert
ON SERVICIOS
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE S
    SET 
        FECHA_CREACION = COALESCE(i.FECHA_CREACION, GETDATE()),
        FECHA_MODIFICACION = COALESCE(i.FECHA_MODIFICACION, GETDATE()),
        USUARIO_CREADOR = COALESCE(NULLIF(i.USUARIO_CREADOR, ''), SYSTEM_USER),
        USUARIO_MODIFICADOR = COALESCE(NULLIF(i.USUARIO_MODIFICADOR, ''), SYSTEM_USER)
    FROM SERVICIOS S
    INNER JOIN inserted i ON S.SERVICIO_ID = i.SERVICIO_ID;
END
GO

-- UPDATE TRIGGER
IF OBJECT_ID('trg_SERVICIOS_audit_update', 'TR') IS NOT NULL DROP TRIGGER trg_SERVICIOS_audit_update;
GO

CREATE TRIGGER trg_SERVICIOS_audit_update
ON SERVICIOS
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE S
    SET 
        FECHA_MODIFICACION = GETDATE(),
        USUARIO_MODIFICADOR = SYSTEM_USER
    FROM SERVICIOS S
    INNER JOIN inserted i ON S.SERVICIO_ID = i.SERVICIO_ID;
END
GO