USE petmedicalcare;
GO

-- INSERT TRIGGER
IF OBJECT_ID('trg_USUARIOS_audit_insert', 'TR') IS NOT NULL DROP TRIGGER trg_USUARIOS_audit_insert;
GO

CREATE TRIGGER trg_USUARIOS_audit_insert
ON USUARIOS
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE U
    SET 
        FECHA_CREACION = COALESCE(i.FECHA_CREACION, GETDATE()),
        FECHA_MODIFICACION = COALESCE(i.FECHA_MODIFICACION, GETDATE()),
        USUARIO_CREADOR = COALESCE(NULLIF(i.USUARIO_CREADOR, ''), SYSTEM_USER),
        USUARIO_MODIFICADOR = COALESCE(NULLIF(i.USUARIO_MODIFICADOR, ''), SYSTEM_USER)
    FROM USUARIOS U
    INNER JOIN inserted i ON U.USUARIO_ID = i.USUARIO_ID;
END
GO

-- UPDATE TRIGGER
IF OBJECT_ID('trg_USUARIOS_audit_update', 'TR') IS NOT NULL DROP TRIGGER trg_USUARIOS_audit_update;
GO

CREATE TRIGGER trg_USUARIOS_audit_update
ON USUARIOS
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE U
    SET 
        FECHA_MODIFICACION = GETDATE(),
        USUARIO_MODIFICADOR = SYSTEM_USER
    FROM USUARIOS U
    INNER JOIN inserted i ON U.USUARIO_ID = i.USUARIO_ID;
END
GO