//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPetBussiness.MetodoDePagoClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://metodopago.softpetws.pucp.edu.pe/", ConfigurationName="MetodoDePagoClient.MetodosDePago")]
    public interface MetodosDePago {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://metodopago.softpetws.pucp.edu.pe/MetodosDePago/insertar_MetodoDePagoReques" +
            "t", ReplyAction="http://metodopago.softpetws.pucp.edu.pe/MetodosDePago/insertar_MetodoDePagoRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.MetodoDePagoClient.insertar_MetodoDePagoResponse insertar_MetodoDePago(SoftPetBussiness.MetodoDePagoClient.insertar_MetodoDePagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://metodopago.softpetws.pucp.edu.pe/MetodosDePago/insertar_MetodoDePagoReques" +
            "t", ReplyAction="http://metodopago.softpetws.pucp.edu.pe/MetodosDePago/insertar_MetodoDePagoRespon" +
            "se")]
        System.Threading.Tasks.Task<SoftPetBussiness.MetodoDePagoClient.insertar_MetodoDePagoResponse> insertar_MetodoDePagoAsync(SoftPetBussiness.MetodoDePagoClient.insertar_MetodoDePagoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://metodopago.softpetws.pucp.edu.pe/MetodosDePago/modificar_MetodoDePagoReque" +
            "st", ReplyAction="http://metodopago.softpetws.pucp.edu.pe/MetodosDePago/modificar_MetodoDePagoRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.MetodoDePagoClient.modificar_MetodoDePagoResponse modificar_MetodoDePago(SoftPetBussiness.MetodoDePagoClient.modificar_MetodoDePagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://metodopago.softpetws.pucp.edu.pe/MetodosDePago/modificar_MetodoDePagoReque" +
            "st", ReplyAction="http://metodopago.softpetws.pucp.edu.pe/MetodosDePago/modificar_MetodoDePagoRespo" +
            "nse")]
        System.Threading.Tasks.Task<SoftPetBussiness.MetodoDePagoClient.modificar_MetodoDePagoResponse> modificar_MetodoDePagoAsync(SoftPetBussiness.MetodoDePagoClient.modificar_MetodoDePagoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://metodopago.softpetws.pucp.edu.pe/MetodosDePago/eliminar_modificar_MetodoDe" +
            "PagoRequest", ReplyAction="http://metodopago.softpetws.pucp.edu.pe/MetodosDePago/eliminar_modificar_MetodoDe" +
            "PagoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.MetodoDePagoClient.eliminar_modificar_MetodoDePagoResponse eliminar_modificar_MetodoDePago(SoftPetBussiness.MetodoDePagoClient.eliminar_modificar_MetodoDePagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://metodopago.softpetws.pucp.edu.pe/MetodosDePago/eliminar_modificar_MetodoDe" +
            "PagoRequest", ReplyAction="http://metodopago.softpetws.pucp.edu.pe/MetodosDePago/eliminar_modificar_MetodoDe" +
            "PagoResponse")]
        System.Threading.Tasks.Task<SoftPetBussiness.MetodoDePagoClient.eliminar_modificar_MetodoDePagoResponse> eliminar_modificar_MetodoDePagoAsync(SoftPetBussiness.MetodoDePagoClient.eliminar_modificar_MetodoDePagoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://metodopago.softpetws.pucp.edu.pe/MetodosDePago/obtener_por_idRequest", ReplyAction="http://metodopago.softpetws.pucp.edu.pe/MetodosDePago/obtener_por_idResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.MetodoDePagoClient.obtener_por_idResponse obtener_por_id(SoftPetBussiness.MetodoDePagoClient.obtener_por_idRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://metodopago.softpetws.pucp.edu.pe/MetodosDePago/obtener_por_idRequest", ReplyAction="http://metodopago.softpetws.pucp.edu.pe/MetodosDePago/obtener_por_idResponse")]
        System.Threading.Tasks.Task<SoftPetBussiness.MetodoDePagoClient.obtener_por_idResponse> obtener_por_idAsync(SoftPetBussiness.MetodoDePagoClient.obtener_por_idRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://metodopago.softpetws.pucp.edu.pe/MetodosDePago/listar_todosRequest", ReplyAction="http://metodopago.softpetws.pucp.edu.pe/MetodosDePago/listar_todosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.MetodoDePagoClient.listar_todosResponse listar_todos(SoftPetBussiness.MetodoDePagoClient.listar_todosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://metodopago.softpetws.pucp.edu.pe/MetodosDePago/listar_todosRequest", ReplyAction="http://metodopago.softpetws.pucp.edu.pe/MetodosDePago/listar_todosResponse")]
        System.Threading.Tasks.Task<SoftPetBussiness.MetodoDePagoClient.listar_todosResponse> listar_todosAsync(SoftPetBussiness.MetodoDePagoClient.listar_todosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertar_MetodoDePago", WrapperNamespace="http://metodopago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertar_MetodoDePagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://metodopago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://metodopago.softpetws.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool activo;
        
        public insertar_MetodoDePagoRequest() {
        }
        
        public insertar_MetodoDePagoRequest(string nombre, bool activo) {
            this.nombre = nombre;
            this.activo = activo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertar_MetodoDePagoResponse", WrapperNamespace="http://metodopago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertar_MetodoDePagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://metodopago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertar_MetodoDePagoResponse() {
        }
        
        public insertar_MetodoDePagoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificar_MetodoDePago", WrapperNamespace="http://metodopago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificar_MetodoDePagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://metodopago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int metodoDePagoId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://metodopago.softpetws.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://metodopago.softpetws.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool activo;
        
        public modificar_MetodoDePagoRequest() {
        }
        
        public modificar_MetodoDePagoRequest(int metodoDePagoId, string nombre, bool activo) {
            this.metodoDePagoId = metodoDePagoId;
            this.nombre = nombre;
            this.activo = activo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificar_MetodoDePagoResponse", WrapperNamespace="http://metodopago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificar_MetodoDePagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://metodopago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificar_MetodoDePagoResponse() {
        }
        
        public modificar_MetodoDePagoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminar_modificar_MetodoDePago", WrapperNamespace="http://metodopago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminar_modificar_MetodoDePagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://metodopago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public eliminar_modificar_MetodoDePagoRequest() {
        }
        
        public eliminar_modificar_MetodoDePagoRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminar_modificar_MetodoDePagoResponse", WrapperNamespace="http://metodopago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminar_modificar_MetodoDePagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://metodopago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminar_modificar_MetodoDePagoResponse() {
        }
        
        public eliminar_modificar_MetodoDePagoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://metodopago.softpetws.pucp.edu.pe/")]
    public partial class metodoDePagoDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private int metodoDePagoIdField;
        
        private bool metodoDePagoIdFieldSpecified;
        
        private tipoMetodoPago nombreField;
        
        private bool nombreFieldSpecified;
        
        private string nombreStrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int metodoDePagoId {
            get {
                return this.metodoDePagoIdField;
            }
            set {
                this.metodoDePagoIdField = value;
                this.RaisePropertyChanged("metodoDePagoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool metodoDePagoIdSpecified {
            get {
                return this.metodoDePagoIdFieldSpecified;
            }
            set {
                this.metodoDePagoIdFieldSpecified = value;
                this.RaisePropertyChanged("metodoDePagoIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public tipoMetodoPago nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nombreSpecified {
            get {
                return this.nombreFieldSpecified;
            }
            set {
                this.nombreFieldSpecified = value;
                this.RaisePropertyChanged("nombreSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombreStr {
            get {
                return this.nombreStrField;
            }
            set {
                this.nombreStrField = value;
                this.RaisePropertyChanged("nombreStr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://metodopago.softpetws.pucp.edu.pe/")]
    public enum tipoMetodoPago {
        
        /// <remarks/>
        EFECTIVO,
        
        /// <remarks/>
        TRANSFERENCIA,
        
        /// <remarks/>
        YAPE,
        
        /// <remarks/>
        PLIN,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtener_por_id", WrapperNamespace="http://metodopago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtener_por_idRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://metodopago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtener_por_idRequest() {
        }
        
        public obtener_por_idRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtener_por_idResponse", WrapperNamespace="http://metodopago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtener_por_idResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://metodopago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPetBussiness.MetodoDePagoClient.metodoDePagoDto @return;
        
        public obtener_por_idResponse() {
        }
        
        public obtener_por_idResponse(SoftPetBussiness.MetodoDePagoClient.metodoDePagoDto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listar_todos", WrapperNamespace="http://metodopago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class listar_todosRequest {
        
        public listar_todosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listar_todosResponse", WrapperNamespace="http://metodopago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class listar_todosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://metodopago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPetBussiness.MetodoDePagoClient.metodoDePagoDto[] @return;
        
        public listar_todosResponse() {
        }
        
        public listar_todosResponse(SoftPetBussiness.MetodoDePagoClient.metodoDePagoDto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MetodosDePagoChannel : SoftPetBussiness.MetodoDePagoClient.MetodosDePago, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MetodosDePagoClient : System.ServiceModel.ClientBase<SoftPetBussiness.MetodoDePagoClient.MetodosDePago>, SoftPetBussiness.MetodoDePagoClient.MetodosDePago {
        
        public MetodosDePagoClient() {
        }
        
        public MetodosDePagoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MetodosDePagoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MetodosDePagoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MetodosDePagoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.MetodoDePagoClient.insertar_MetodoDePagoResponse SoftPetBussiness.MetodoDePagoClient.MetodosDePago.insertar_MetodoDePago(SoftPetBussiness.MetodoDePagoClient.insertar_MetodoDePagoRequest request) {
            return base.Channel.insertar_MetodoDePago(request);
        }
        
        public int insertar_MetodoDePago(string nombre, bool activo) {
            SoftPetBussiness.MetodoDePagoClient.insertar_MetodoDePagoRequest inValue = new SoftPetBussiness.MetodoDePagoClient.insertar_MetodoDePagoRequest();
            inValue.nombre = nombre;
            inValue.activo = activo;
            SoftPetBussiness.MetodoDePagoClient.insertar_MetodoDePagoResponse retVal = ((SoftPetBussiness.MetodoDePagoClient.MetodosDePago)(this)).insertar_MetodoDePago(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.MetodoDePagoClient.insertar_MetodoDePagoResponse> SoftPetBussiness.MetodoDePagoClient.MetodosDePago.insertar_MetodoDePagoAsync(SoftPetBussiness.MetodoDePagoClient.insertar_MetodoDePagoRequest request) {
            return base.Channel.insertar_MetodoDePagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.MetodoDePagoClient.insertar_MetodoDePagoResponse> insertar_MetodoDePagoAsync(string nombre, bool activo) {
            SoftPetBussiness.MetodoDePagoClient.insertar_MetodoDePagoRequest inValue = new SoftPetBussiness.MetodoDePagoClient.insertar_MetodoDePagoRequest();
            inValue.nombre = nombre;
            inValue.activo = activo;
            return ((SoftPetBussiness.MetodoDePagoClient.MetodosDePago)(this)).insertar_MetodoDePagoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.MetodoDePagoClient.modificar_MetodoDePagoResponse SoftPetBussiness.MetodoDePagoClient.MetodosDePago.modificar_MetodoDePago(SoftPetBussiness.MetodoDePagoClient.modificar_MetodoDePagoRequest request) {
            return base.Channel.modificar_MetodoDePago(request);
        }
        
        public int modificar_MetodoDePago(int metodoDePagoId, string nombre, bool activo) {
            SoftPetBussiness.MetodoDePagoClient.modificar_MetodoDePagoRequest inValue = new SoftPetBussiness.MetodoDePagoClient.modificar_MetodoDePagoRequest();
            inValue.metodoDePagoId = metodoDePagoId;
            inValue.nombre = nombre;
            inValue.activo = activo;
            SoftPetBussiness.MetodoDePagoClient.modificar_MetodoDePagoResponse retVal = ((SoftPetBussiness.MetodoDePagoClient.MetodosDePago)(this)).modificar_MetodoDePago(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.MetodoDePagoClient.modificar_MetodoDePagoResponse> SoftPetBussiness.MetodoDePagoClient.MetodosDePago.modificar_MetodoDePagoAsync(SoftPetBussiness.MetodoDePagoClient.modificar_MetodoDePagoRequest request) {
            return base.Channel.modificar_MetodoDePagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.MetodoDePagoClient.modificar_MetodoDePagoResponse> modificar_MetodoDePagoAsync(int metodoDePagoId, string nombre, bool activo) {
            SoftPetBussiness.MetodoDePagoClient.modificar_MetodoDePagoRequest inValue = new SoftPetBussiness.MetodoDePagoClient.modificar_MetodoDePagoRequest();
            inValue.metodoDePagoId = metodoDePagoId;
            inValue.nombre = nombre;
            inValue.activo = activo;
            return ((SoftPetBussiness.MetodoDePagoClient.MetodosDePago)(this)).modificar_MetodoDePagoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.MetodoDePagoClient.eliminar_modificar_MetodoDePagoResponse SoftPetBussiness.MetodoDePagoClient.MetodosDePago.eliminar_modificar_MetodoDePago(SoftPetBussiness.MetodoDePagoClient.eliminar_modificar_MetodoDePagoRequest request) {
            return base.Channel.eliminar_modificar_MetodoDePago(request);
        }
        
        public int eliminar_modificar_MetodoDePago(int arg0) {
            SoftPetBussiness.MetodoDePagoClient.eliminar_modificar_MetodoDePagoRequest inValue = new SoftPetBussiness.MetodoDePagoClient.eliminar_modificar_MetodoDePagoRequest();
            inValue.arg0 = arg0;
            SoftPetBussiness.MetodoDePagoClient.eliminar_modificar_MetodoDePagoResponse retVal = ((SoftPetBussiness.MetodoDePagoClient.MetodosDePago)(this)).eliminar_modificar_MetodoDePago(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.MetodoDePagoClient.eliminar_modificar_MetodoDePagoResponse> SoftPetBussiness.MetodoDePagoClient.MetodosDePago.eliminar_modificar_MetodoDePagoAsync(SoftPetBussiness.MetodoDePagoClient.eliminar_modificar_MetodoDePagoRequest request) {
            return base.Channel.eliminar_modificar_MetodoDePagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.MetodoDePagoClient.eliminar_modificar_MetodoDePagoResponse> eliminar_modificar_MetodoDePagoAsync(int arg0) {
            SoftPetBussiness.MetodoDePagoClient.eliminar_modificar_MetodoDePagoRequest inValue = new SoftPetBussiness.MetodoDePagoClient.eliminar_modificar_MetodoDePagoRequest();
            inValue.arg0 = arg0;
            return ((SoftPetBussiness.MetodoDePagoClient.MetodosDePago)(this)).eliminar_modificar_MetodoDePagoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.MetodoDePagoClient.obtener_por_idResponse SoftPetBussiness.MetodoDePagoClient.MetodosDePago.obtener_por_id(SoftPetBussiness.MetodoDePagoClient.obtener_por_idRequest request) {
            return base.Channel.obtener_por_id(request);
        }
        
        public SoftPetBussiness.MetodoDePagoClient.metodoDePagoDto obtener_por_id(int id) {
            SoftPetBussiness.MetodoDePagoClient.obtener_por_idRequest inValue = new SoftPetBussiness.MetodoDePagoClient.obtener_por_idRequest();
            inValue.id = id;
            SoftPetBussiness.MetodoDePagoClient.obtener_por_idResponse retVal = ((SoftPetBussiness.MetodoDePagoClient.MetodosDePago)(this)).obtener_por_id(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.MetodoDePagoClient.obtener_por_idResponse> SoftPetBussiness.MetodoDePagoClient.MetodosDePago.obtener_por_idAsync(SoftPetBussiness.MetodoDePagoClient.obtener_por_idRequest request) {
            return base.Channel.obtener_por_idAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.MetodoDePagoClient.obtener_por_idResponse> obtener_por_idAsync(int id) {
            SoftPetBussiness.MetodoDePagoClient.obtener_por_idRequest inValue = new SoftPetBussiness.MetodoDePagoClient.obtener_por_idRequest();
            inValue.id = id;
            return ((SoftPetBussiness.MetodoDePagoClient.MetodosDePago)(this)).obtener_por_idAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.MetodoDePagoClient.listar_todosResponse SoftPetBussiness.MetodoDePagoClient.MetodosDePago.listar_todos(SoftPetBussiness.MetodoDePagoClient.listar_todosRequest request) {
            return base.Channel.listar_todos(request);
        }
        
        public SoftPetBussiness.MetodoDePagoClient.metodoDePagoDto[] listar_todos() {
            SoftPetBussiness.MetodoDePagoClient.listar_todosRequest inValue = new SoftPetBussiness.MetodoDePagoClient.listar_todosRequest();
            SoftPetBussiness.MetodoDePagoClient.listar_todosResponse retVal = ((SoftPetBussiness.MetodoDePagoClient.MetodosDePago)(this)).listar_todos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.MetodoDePagoClient.listar_todosResponse> SoftPetBussiness.MetodoDePagoClient.MetodosDePago.listar_todosAsync(SoftPetBussiness.MetodoDePagoClient.listar_todosRequest request) {
            return base.Channel.listar_todosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.MetodoDePagoClient.listar_todosResponse> listar_todosAsync() {
            SoftPetBussiness.MetodoDePagoClient.listar_todosRequest inValue = new SoftPetBussiness.MetodoDePagoClient.listar_todosRequest();
            return ((SoftPetBussiness.MetodoDePagoClient.MetodosDePago)(this)).listar_todosAsync(inValue);
        }
    }
}
