//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPetBussiness.TipoProductoClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tipoproducto.softpetws.pucp.edu.pe/", ConfigurationName="TipoProductoClient.TiposProducto")]
    public interface TiposProducto {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tipoproducto.softpetws.pucp.edu.pe/TiposProducto/insertar_tipoproductosReq" +
            "uest", ReplyAction="http://tipoproducto.softpetws.pucp.edu.pe/TiposProducto/insertar_tipoproductosRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.TipoProductoClient.insertar_tipoproductosResponse insertar_tipoproductos(SoftPetBussiness.TipoProductoClient.insertar_tipoproductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tipoproducto.softpetws.pucp.edu.pe/TiposProducto/insertar_tipoproductosReq" +
            "uest", ReplyAction="http://tipoproducto.softpetws.pucp.edu.pe/TiposProducto/insertar_tipoproductosRes" +
            "ponse")]
        System.Threading.Tasks.Task<SoftPetBussiness.TipoProductoClient.insertar_tipoproductosResponse> insertar_tipoproductosAsync(SoftPetBussiness.TipoProductoClient.insertar_tipoproductosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tipoproducto.softpetws.pucp.edu.pe/TiposProducto/modificar_tipoproductosRe" +
            "quest", ReplyAction="http://tipoproducto.softpetws.pucp.edu.pe/TiposProducto/modificar_tipoproductosRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.TipoProductoClient.modificar_tipoproductosResponse modificar_tipoproductos(SoftPetBussiness.TipoProductoClient.modificar_tipoproductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tipoproducto.softpetws.pucp.edu.pe/TiposProducto/modificar_tipoproductosRe" +
            "quest", ReplyAction="http://tipoproducto.softpetws.pucp.edu.pe/TiposProducto/modificar_tipoproductosRe" +
            "sponse")]
        System.Threading.Tasks.Task<SoftPetBussiness.TipoProductoClient.modificar_tipoproductosResponse> modificar_tipoproductosAsync(SoftPetBussiness.TipoProductoClient.modificar_tipoproductosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tipoproducto.softpetws.pucp.edu.pe/TiposProducto/eliminar_tipoproductosReq" +
            "uest", ReplyAction="http://tipoproducto.softpetws.pucp.edu.pe/TiposProducto/eliminar_tipoproductosRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.TipoProductoClient.eliminar_tipoproductosResponse eliminar_tipoproductos(SoftPetBussiness.TipoProductoClient.eliminar_tipoproductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tipoproducto.softpetws.pucp.edu.pe/TiposProducto/eliminar_tipoproductosReq" +
            "uest", ReplyAction="http://tipoproducto.softpetws.pucp.edu.pe/TiposProducto/eliminar_tipoproductosRes" +
            "ponse")]
        System.Threading.Tasks.Task<SoftPetBussiness.TipoProductoClient.eliminar_tipoproductosResponse> eliminar_tipoproductosAsync(SoftPetBussiness.TipoProductoClient.eliminar_tipoproductosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tipoproducto.softpetws.pucp.edu.pe/TiposProducto/obtener_por_idRequest", ReplyAction="http://tipoproducto.softpetws.pucp.edu.pe/TiposProducto/obtener_por_idResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.TipoProductoClient.obtener_por_idResponse obtener_por_id(SoftPetBussiness.TipoProductoClient.obtener_por_idRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tipoproducto.softpetws.pucp.edu.pe/TiposProducto/obtener_por_idRequest", ReplyAction="http://tipoproducto.softpetws.pucp.edu.pe/TiposProducto/obtener_por_idResponse")]
        System.Threading.Tasks.Task<SoftPetBussiness.TipoProductoClient.obtener_por_idResponse> obtener_por_idAsync(SoftPetBussiness.TipoProductoClient.obtener_por_idRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tipoproducto.softpetws.pucp.edu.pe/TiposProducto/listar_todosRequest", ReplyAction="http://tipoproducto.softpetws.pucp.edu.pe/TiposProducto/listar_todosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.TipoProductoClient.listar_todosResponse listar_todos(SoftPetBussiness.TipoProductoClient.listar_todosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tipoproducto.softpetws.pucp.edu.pe/TiposProducto/listar_todosRequest", ReplyAction="http://tipoproducto.softpetws.pucp.edu.pe/TiposProducto/listar_todosResponse")]
        System.Threading.Tasks.Task<SoftPetBussiness.TipoProductoClient.listar_todosResponse> listar_todosAsync(SoftPetBussiness.TipoProductoClient.listar_todosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertar_tipoproductos", WrapperNamespace="http://tipoproducto.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertar_tipoproductosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tipoproducto.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tipoproducto.softpetws.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tipoproducto.softpetws.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool activo;
        
        public insertar_tipoproductosRequest() {
        }
        
        public insertar_tipoproductosRequest(string nombre, string descripcion, bool activo) {
            this.nombre = nombre;
            this.descripcion = descripcion;
            this.activo = activo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertar_tipoproductosResponse", WrapperNamespace="http://tipoproducto.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertar_tipoproductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tipoproducto.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertar_tipoproductosResponse() {
        }
        
        public insertar_tipoproductosResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificar_tipoproductos", WrapperNamespace="http://tipoproducto.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificar_tipoproductosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tipoproducto.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int tipoProductoId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tipoproducto.softpetws.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tipoproducto.softpetws.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tipoproducto.softpetws.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool activo;
        
        public modificar_tipoproductosRequest() {
        }
        
        public modificar_tipoproductosRequest(int tipoProductoId, string nombre, string descripcion, bool activo) {
            this.tipoProductoId = tipoProductoId;
            this.nombre = nombre;
            this.descripcion = descripcion;
            this.activo = activo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificar_tipoproductosResponse", WrapperNamespace="http://tipoproducto.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificar_tipoproductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tipoproducto.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificar_tipoproductosResponse() {
        }
        
        public modificar_tipoproductosResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminar_tipoproductos", WrapperNamespace="http://tipoproducto.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminar_tipoproductosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tipoproducto.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int tipoProductoId;
        
        public eliminar_tipoproductosRequest() {
        }
        
        public eliminar_tipoproductosRequest(int tipoProductoId) {
            this.tipoProductoId = tipoProductoId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminar_tipoproductosResponse", WrapperNamespace="http://tipoproducto.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminar_tipoproductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tipoproducto.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminar_tipoproductosResponse() {
        }
        
        public eliminar_tipoproductosResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tipoproducto.softpetws.pucp.edu.pe/")]
    public partial class tipoProductoDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private string descripcionField;
        
        private string nombreField;
        
        private int tipoProductoIdField;
        
        private bool tipoProductoIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int tipoProductoId {
            get {
                return this.tipoProductoIdField;
            }
            set {
                this.tipoProductoIdField = value;
                this.RaisePropertyChanged("tipoProductoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoProductoIdSpecified {
            get {
                return this.tipoProductoIdFieldSpecified;
            }
            set {
                this.tipoProductoIdFieldSpecified = value;
                this.RaisePropertyChanged("tipoProductoIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtener_por_id", WrapperNamespace="http://tipoproducto.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtener_por_idRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tipoproducto.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtener_por_idRequest() {
        }
        
        public obtener_por_idRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtener_por_idResponse", WrapperNamespace="http://tipoproducto.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtener_por_idResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tipoproducto.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPetBussiness.TipoProductoClient.tipoProductoDto @return;
        
        public obtener_por_idResponse() {
        }
        
        public obtener_por_idResponse(SoftPetBussiness.TipoProductoClient.tipoProductoDto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listar_todos", WrapperNamespace="http://tipoproducto.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class listar_todosRequest {
        
        public listar_todosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listar_todosResponse", WrapperNamespace="http://tipoproducto.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class listar_todosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tipoproducto.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPetBussiness.TipoProductoClient.tipoProductoDto[] @return;
        
        public listar_todosResponse() {
        }
        
        public listar_todosResponse(SoftPetBussiness.TipoProductoClient.tipoProductoDto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TiposProductoChannel : SoftPetBussiness.TipoProductoClient.TiposProducto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TiposProductoClient : System.ServiceModel.ClientBase<SoftPetBussiness.TipoProductoClient.TiposProducto>, SoftPetBussiness.TipoProductoClient.TiposProducto {
        
        public TiposProductoClient() {
        }
        
        public TiposProductoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TiposProductoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TiposProductoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TiposProductoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.TipoProductoClient.insertar_tipoproductosResponse SoftPetBussiness.TipoProductoClient.TiposProducto.insertar_tipoproductos(SoftPetBussiness.TipoProductoClient.insertar_tipoproductosRequest request) {
            return base.Channel.insertar_tipoproductos(request);
        }
        
        public int insertar_tipoproductos(string nombre, string descripcion, bool activo) {
            SoftPetBussiness.TipoProductoClient.insertar_tipoproductosRequest inValue = new SoftPetBussiness.TipoProductoClient.insertar_tipoproductosRequest();
            inValue.nombre = nombre;
            inValue.descripcion = descripcion;
            inValue.activo = activo;
            SoftPetBussiness.TipoProductoClient.insertar_tipoproductosResponse retVal = ((SoftPetBussiness.TipoProductoClient.TiposProducto)(this)).insertar_tipoproductos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.TipoProductoClient.insertar_tipoproductosResponse> SoftPetBussiness.TipoProductoClient.TiposProducto.insertar_tipoproductosAsync(SoftPetBussiness.TipoProductoClient.insertar_tipoproductosRequest request) {
            return base.Channel.insertar_tipoproductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.TipoProductoClient.insertar_tipoproductosResponse> insertar_tipoproductosAsync(string nombre, string descripcion, bool activo) {
            SoftPetBussiness.TipoProductoClient.insertar_tipoproductosRequest inValue = new SoftPetBussiness.TipoProductoClient.insertar_tipoproductosRequest();
            inValue.nombre = nombre;
            inValue.descripcion = descripcion;
            inValue.activo = activo;
            return ((SoftPetBussiness.TipoProductoClient.TiposProducto)(this)).insertar_tipoproductosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.TipoProductoClient.modificar_tipoproductosResponse SoftPetBussiness.TipoProductoClient.TiposProducto.modificar_tipoproductos(SoftPetBussiness.TipoProductoClient.modificar_tipoproductosRequest request) {
            return base.Channel.modificar_tipoproductos(request);
        }
        
        public int modificar_tipoproductos(int tipoProductoId, string nombre, string descripcion, bool activo) {
            SoftPetBussiness.TipoProductoClient.modificar_tipoproductosRequest inValue = new SoftPetBussiness.TipoProductoClient.modificar_tipoproductosRequest();
            inValue.tipoProductoId = tipoProductoId;
            inValue.nombre = nombre;
            inValue.descripcion = descripcion;
            inValue.activo = activo;
            SoftPetBussiness.TipoProductoClient.modificar_tipoproductosResponse retVal = ((SoftPetBussiness.TipoProductoClient.TiposProducto)(this)).modificar_tipoproductos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.TipoProductoClient.modificar_tipoproductosResponse> SoftPetBussiness.TipoProductoClient.TiposProducto.modificar_tipoproductosAsync(SoftPetBussiness.TipoProductoClient.modificar_tipoproductosRequest request) {
            return base.Channel.modificar_tipoproductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.TipoProductoClient.modificar_tipoproductosResponse> modificar_tipoproductosAsync(int tipoProductoId, string nombre, string descripcion, bool activo) {
            SoftPetBussiness.TipoProductoClient.modificar_tipoproductosRequest inValue = new SoftPetBussiness.TipoProductoClient.modificar_tipoproductosRequest();
            inValue.tipoProductoId = tipoProductoId;
            inValue.nombre = nombre;
            inValue.descripcion = descripcion;
            inValue.activo = activo;
            return ((SoftPetBussiness.TipoProductoClient.TiposProducto)(this)).modificar_tipoproductosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.TipoProductoClient.eliminar_tipoproductosResponse SoftPetBussiness.TipoProductoClient.TiposProducto.eliminar_tipoproductos(SoftPetBussiness.TipoProductoClient.eliminar_tipoproductosRequest request) {
            return base.Channel.eliminar_tipoproductos(request);
        }
        
        public int eliminar_tipoproductos(int tipoProductoId) {
            SoftPetBussiness.TipoProductoClient.eliminar_tipoproductosRequest inValue = new SoftPetBussiness.TipoProductoClient.eliminar_tipoproductosRequest();
            inValue.tipoProductoId = tipoProductoId;
            SoftPetBussiness.TipoProductoClient.eliminar_tipoproductosResponse retVal = ((SoftPetBussiness.TipoProductoClient.TiposProducto)(this)).eliminar_tipoproductos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.TipoProductoClient.eliminar_tipoproductosResponse> SoftPetBussiness.TipoProductoClient.TiposProducto.eliminar_tipoproductosAsync(SoftPetBussiness.TipoProductoClient.eliminar_tipoproductosRequest request) {
            return base.Channel.eliminar_tipoproductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.TipoProductoClient.eliminar_tipoproductosResponse> eliminar_tipoproductosAsync(int tipoProductoId) {
            SoftPetBussiness.TipoProductoClient.eliminar_tipoproductosRequest inValue = new SoftPetBussiness.TipoProductoClient.eliminar_tipoproductosRequest();
            inValue.tipoProductoId = tipoProductoId;
            return ((SoftPetBussiness.TipoProductoClient.TiposProducto)(this)).eliminar_tipoproductosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.TipoProductoClient.obtener_por_idResponse SoftPetBussiness.TipoProductoClient.TiposProducto.obtener_por_id(SoftPetBussiness.TipoProductoClient.obtener_por_idRequest request) {
            return base.Channel.obtener_por_id(request);
        }
        
        public SoftPetBussiness.TipoProductoClient.tipoProductoDto obtener_por_id(int id) {
            SoftPetBussiness.TipoProductoClient.obtener_por_idRequest inValue = new SoftPetBussiness.TipoProductoClient.obtener_por_idRequest();
            inValue.id = id;
            SoftPetBussiness.TipoProductoClient.obtener_por_idResponse retVal = ((SoftPetBussiness.TipoProductoClient.TiposProducto)(this)).obtener_por_id(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.TipoProductoClient.obtener_por_idResponse> SoftPetBussiness.TipoProductoClient.TiposProducto.obtener_por_idAsync(SoftPetBussiness.TipoProductoClient.obtener_por_idRequest request) {
            return base.Channel.obtener_por_idAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.TipoProductoClient.obtener_por_idResponse> obtener_por_idAsync(int id) {
            SoftPetBussiness.TipoProductoClient.obtener_por_idRequest inValue = new SoftPetBussiness.TipoProductoClient.obtener_por_idRequest();
            inValue.id = id;
            return ((SoftPetBussiness.TipoProductoClient.TiposProducto)(this)).obtener_por_idAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.TipoProductoClient.listar_todosResponse SoftPetBussiness.TipoProductoClient.TiposProducto.listar_todos(SoftPetBussiness.TipoProductoClient.listar_todosRequest request) {
            return base.Channel.listar_todos(request);
        }
        
        public SoftPetBussiness.TipoProductoClient.tipoProductoDto[] listar_todos() {
            SoftPetBussiness.TipoProductoClient.listar_todosRequest inValue = new SoftPetBussiness.TipoProductoClient.listar_todosRequest();
            SoftPetBussiness.TipoProductoClient.listar_todosResponse retVal = ((SoftPetBussiness.TipoProductoClient.TiposProducto)(this)).listar_todos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.TipoProductoClient.listar_todosResponse> SoftPetBussiness.TipoProductoClient.TiposProducto.listar_todosAsync(SoftPetBussiness.TipoProductoClient.listar_todosRequest request) {
            return base.Channel.listar_todosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.TipoProductoClient.listar_todosResponse> listar_todosAsync() {
            SoftPetBussiness.TipoProductoClient.listar_todosRequest inValue = new SoftPetBussiness.TipoProductoClient.listar_todosRequest();
            return ((SoftPetBussiness.TipoProductoClient.TiposProducto)(this)).listar_todosAsync(inValue);
        }
    }
}
