-- ===============================================
-- DROP de todas las tablas (ordenado por FKs)
-- ===============================================
use petmedicalcare;
DROP TABLE IF EXISTS `DETALLES_DOCUMENTO_DE_PAGO`;
DROP TABLE IF EXISTS `DETALLES_RECETA`;
DROP TABLE IF EXISTS `DOCUMENTOS_DE_PAGO`;
DROP TABLE IF EXISTS `TIPOS_DOCUMENTO`;
DROP TABLE IF EXISTS `RECETAS_MEDICA`;
DROP TABLE IF EXISTS `PRODUCTOS`;
DROP TABLE IF EXISTS `TIPOS_PRODUCTO`;
DROP TABLE IF EXISTS `DETALLES_SERVICIO`;
DROP TABLE IF EXISTS `CITAS_ATENCION`;
DROP TABLE IF EXISTS `SERVICIOS`;
DROP TABLE IF EXISTS `TIPOS_SERVICIO`;
DROP TABLE IF EXISTS `VETERINARIOS`;
DROP TABLE IF EXISTS `MASCOTAS`;
DROP TABLE IF EXISTS `PERSONAS`;
DROP TABLE IF EXISTS `ROLES_USUARIO`;
DROP TABLE IF EXISTS `USUARIOS`;
DROP TABLE IF EXISTS `ROLES`;
