use petmedicalcare;
-- ===============================================
-- SELECTS DE VERIFICACIÓN (todas las tablas)
-- ===============================================
-- ===============================================
-- SELECTS DE ROLES, USUSARIO Y ROLES USUARIO
-- ===============================================
SELECT * FROM ROLES;
SELECT * FROM USUARIOS;
SELECT * FROM ROLES_USUARIO;
-- SELECT PARA ROLES USUARIOS
SELECT 
    u.USUARIO_ID,
    u.USENAME AS Usuario,
    r.NOMBRE AS Rol
FROM USUARIOS u
INNER JOIN ROLES_USUARIO ru ON u.USUARIO_ID = ru.USUARIO_ID
INNER JOIN ROLES r ON ru.ROL_ID = r.ROL_ID
ORDER BY u.USUARIO_ID, r.NOMBRE;



SELECT * FROM PERSONAS;
SELECT * FROM MASCOTAS;
SELECT * FROM VETERINARIOS;
SELECT * FROM TIPOS_SERVICIO;
SELECT * FROM SERVICIOS;
SELECT * FROM CITAS_ATENCION;
SELECT * FROM DETALLES_SERVICIO;
SELECT * FROM TIPOS_PRODUCTO;
SELECT * FROM PRODUCTOS;
SELECT * FROM RECETAS_MEDICA;
SELECT * FROM TIPOS_DOCUMENTO;
SELECT * FROM DOCUMENTOS_DE_PAGO;
SELECT * FROM DETALLES_RECETA;
SELECT * FROM DETALLES_DOCUMENTO_DE_PAGO;
