-- Usamos DELIMITER para poder definir triggers con bloques BEGIN..END
DELIMITER $$

-- Limpieza por si ya existen
DROP TRIGGER IF EXISTS trg_PRODUCTOS_bi_audit $$
DROP TRIGGER IF EXISTS trg_PRODUCTOS_bu_audit $$

-- =====================================================
-- BEFORE INSERT: completa creación y (si faltan) modificación
-- NOTA IMPORTANTE!!! SI QUEREMOS PONER A LA PERSONA QUE HIZO LA MODIFICACION 
-- AGREGRAR : SET @app_user := 'admin'; (cambiar admin por el que modifica)
-- =====================================================
DELIMITER $$

DROP TRIGGER IF EXISTS trg_PRODUCTOS_bi_audit $$
DROP TRIGGER IF EXISTS trg_PRODUCTOS_bu_audit $$

CREATE TRIGGER trg_PRODUCTOS_bi_audit
BEFORE INSERT ON PRODUCTOS
FOR EACH ROW
BEGIN
  -- Fechas con hora
  IF NEW.FECHA_CREACION IS NULL THEN
    SET NEW.FECHA_CREACION = NOW();            -- fecha y hora
  END IF;

  IF NEW.FECHA_MODIFICACION IS NULL THEN
    SET NEW.FECHA_MODIFICACION = NOW();        -- fecha y hora
  END IF;

  -- Usuarios (de la app si lo pasas; si no, user de MySQL)
  IF NEW.USUARIO_CREADOR IS NULL OR NEW.USUARIO_CREADOR = '' THEN
    SET NEW.USUARIO_CREADOR = COALESCE(@app_user, SUBSTRING_INDEX(CURRENT_USER(), '@', 1));
  END IF;

  IF NEW.USUARIO_MOFICADOR IS NULL OR NEW.USUARIO_MOFICADOR = '' THEN
    SET NEW.USUARIO_MOFICADOR = COALESCE(@app_user, SUBSTRING_INDEX(CURRENT_USER(), '@', 1));
  END IF;
END $$

CREATE TRIGGER trg_PRODUCTOS_bu_audit
BEFORE UPDATE ON PRODUCTOS
FOR EACH ROW
BEGIN
  SET NEW.FECHA_MODIFICACION = NOW();  -- siempre con hora
  SET NEW.USUARIO_MOFICADOR = COALESCE(@app_user, SUBSTRING_INDEX(CURRENT_USER(), '@', 1));
END $$

DELIMITER ;

INSERT INTO PRODUCTOS (NOMBRE, PRESENTACION, PRECIO_UNITARIO, ACTIVO, TIPO_PRODUCTO_ID)
VALUES ('Antipulgas Z', 'Talla M', 32.30, 1, 1);
UPDATE PRODUCTOS SET PRECIO_UNITARIO = 33.90 WHERE PRODUCTO_ID = LAST_INSERT_ID();


SELECT PRODUCTO_ID, NOMBRE, FECHA_CREACION, USUARIO_CREADOR,
       FECHA_MODIFICACION, USUARIO_MOFICADOR
FROM PRODUCTOS
