//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPetBussiness.DetalleDocumentoDePagoClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/", ConfigurationName="DetalleDocumentoDePagoClient.DetallesDocumentoDePago")]
    public interface DetallesDocumentoDePago {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://detalledocpago.softpetws.pucp.edu.pe/DetallesDocumentoDePago/insertar_Deta" +
            "lle_Documento_De_PagoRequest", ReplyAction="http://detalledocpago.softpetws.pucp.edu.pe/DetallesDocumentoDePago/insertar_Deta" +
            "lle_Documento_De_PagoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.DetalleDocumentoDePagoClient.insertar_Detalle_Documento_De_PagoResponse insertar_Detalle_Documento_De_Pago(SoftPetBussiness.DetalleDocumentoDePagoClient.insertar_Detalle_Documento_De_PagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://detalledocpago.softpetws.pucp.edu.pe/DetallesDocumentoDePago/insertar_Deta" +
            "lle_Documento_De_PagoRequest", ReplyAction="http://detalledocpago.softpetws.pucp.edu.pe/DetallesDocumentoDePago/insertar_Deta" +
            "lle_Documento_De_PagoResponse")]
        System.Threading.Tasks.Task<SoftPetBussiness.DetalleDocumentoDePagoClient.insertar_Detalle_Documento_De_PagoResponse> insertar_Detalle_Documento_De_PagoAsync(SoftPetBussiness.DetalleDocumentoDePagoClient.insertar_Detalle_Documento_De_PagoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://detalledocpago.softpetws.pucp.edu.pe/DetallesDocumentoDePago/modificar_Det" +
            "alle_Documento_De_PagoRequest", ReplyAction="http://detalledocpago.softpetws.pucp.edu.pe/DetallesDocumentoDePago/modificar_Det" +
            "alle_Documento_De_PagoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.DetalleDocumentoDePagoClient.modificar_Detalle_Documento_De_PagoResponse modificar_Detalle_Documento_De_Pago(SoftPetBussiness.DetalleDocumentoDePagoClient.modificar_Detalle_Documento_De_PagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://detalledocpago.softpetws.pucp.edu.pe/DetallesDocumentoDePago/modificar_Det" +
            "alle_Documento_De_PagoRequest", ReplyAction="http://detalledocpago.softpetws.pucp.edu.pe/DetallesDocumentoDePago/modificar_Det" +
            "alle_Documento_De_PagoResponse")]
        System.Threading.Tasks.Task<SoftPetBussiness.DetalleDocumentoDePagoClient.modificar_Detalle_Documento_De_PagoResponse> modificar_Detalle_Documento_De_PagoAsync(SoftPetBussiness.DetalleDocumentoDePagoClient.modificar_Detalle_Documento_De_PagoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://detalledocpago.softpetws.pucp.edu.pe/DetallesDocumentoDePago/eliminar_Deta" +
            "lle_Documento_De_PagoRequest", ReplyAction="http://detalledocpago.softpetws.pucp.edu.pe/DetallesDocumentoDePago/eliminar_Deta" +
            "lle_Documento_De_PagoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.DetalleDocumentoDePagoClient.eliminar_Detalle_Documento_De_PagoResponse eliminar_Detalle_Documento_De_Pago(SoftPetBussiness.DetalleDocumentoDePagoClient.eliminar_Detalle_Documento_De_PagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://detalledocpago.softpetws.pucp.edu.pe/DetallesDocumentoDePago/eliminar_Deta" +
            "lle_Documento_De_PagoRequest", ReplyAction="http://detalledocpago.softpetws.pucp.edu.pe/DetallesDocumentoDePago/eliminar_Deta" +
            "lle_Documento_De_PagoResponse")]
        System.Threading.Tasks.Task<SoftPetBussiness.DetalleDocumentoDePagoClient.eliminar_Detalle_Documento_De_PagoResponse> eliminar_Detalle_Documento_De_PagoAsync(SoftPetBussiness.DetalleDocumentoDePagoClient.eliminar_Detalle_Documento_De_PagoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://detalledocpago.softpetws.pucp.edu.pe/DetallesDocumentoDePago/obtener_por_i" +
            "dRequest", ReplyAction="http://detalledocpago.softpetws.pucp.edu.pe/DetallesDocumentoDePago/obtener_por_i" +
            "dResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.DetalleDocumentoDePagoClient.obtener_por_idResponse obtener_por_id(SoftPetBussiness.DetalleDocumentoDePagoClient.obtener_por_idRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://detalledocpago.softpetws.pucp.edu.pe/DetallesDocumentoDePago/obtener_por_i" +
            "dRequest", ReplyAction="http://detalledocpago.softpetws.pucp.edu.pe/DetallesDocumentoDePago/obtener_por_i" +
            "dResponse")]
        System.Threading.Tasks.Task<SoftPetBussiness.DetalleDocumentoDePagoClient.obtener_por_idResponse> obtener_por_idAsync(SoftPetBussiness.DetalleDocumentoDePagoClient.obtener_por_idRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://detalledocpago.softpetws.pucp.edu.pe/DetallesDocumentoDePago/listar_todosR" +
            "equest", ReplyAction="http://detalledocpago.softpetws.pucp.edu.pe/DetallesDocumentoDePago/listar_todosR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPetBussiness.DetalleDocumentoDePagoClient.listar_todosResponse listar_todos(SoftPetBussiness.DetalleDocumentoDePagoClient.listar_todosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://detalledocpago.softpetws.pucp.edu.pe/DetallesDocumentoDePago/listar_todosR" +
            "equest", ReplyAction="http://detalledocpago.softpetws.pucp.edu.pe/DetallesDocumentoDePago/listar_todosR" +
            "esponse")]
        System.Threading.Tasks.Task<SoftPetBussiness.DetalleDocumentoDePagoClient.listar_todosResponse> listar_todosAsync(SoftPetBussiness.DetalleDocumentoDePagoClient.listar_todosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertar_Detalle_Documento_De_Pago", WrapperNamespace="http://detalledocpago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertar_Detalle_Documento_De_PagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int documentoPagoId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int servicioId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int productoId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int nroItem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double precioUnitario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double valorVenta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool activo;
        
        public insertar_Detalle_Documento_De_PagoRequest() {
        }
        
        public insertar_Detalle_Documento_De_PagoRequest(int documentoPagoId, int servicioId, int productoId, int nroItem, string descripcion, int cantidad, double precioUnitario, double valorVenta, bool activo) {
            this.documentoPagoId = documentoPagoId;
            this.servicioId = servicioId;
            this.productoId = productoId;
            this.nroItem = nroItem;
            this.descripcion = descripcion;
            this.cantidad = cantidad;
            this.precioUnitario = precioUnitario;
            this.valorVenta = valorVenta;
            this.activo = activo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertar_Detalle_Documento_De_PagoResponse", WrapperNamespace="http://detalledocpago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertar_Detalle_Documento_De_PagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertar_Detalle_Documento_De_PagoResponse() {
        }
        
        public insertar_Detalle_Documento_De_PagoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificar_Detalle_Documento_De_Pago", WrapperNamespace="http://detalledocpago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificar_Detalle_Documento_De_PagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ddpId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int documentoPagoId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int servicioId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int productoId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int nroItem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double precioUnitario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double valorVenta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool activo;
        
        public modificar_Detalle_Documento_De_PagoRequest() {
        }
        
        public modificar_Detalle_Documento_De_PagoRequest(int ddpId, int documentoPagoId, int servicioId, int productoId, int nroItem, string descripcion, int cantidad, double precioUnitario, double valorVenta, bool activo) {
            this.ddpId = ddpId;
            this.documentoPagoId = documentoPagoId;
            this.servicioId = servicioId;
            this.productoId = productoId;
            this.nroItem = nroItem;
            this.descripcion = descripcion;
            this.cantidad = cantidad;
            this.precioUnitario = precioUnitario;
            this.valorVenta = valorVenta;
            this.activo = activo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificar_Detalle_Documento_De_PagoResponse", WrapperNamespace="http://detalledocpago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificar_Detalle_Documento_De_PagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificar_Detalle_Documento_De_PagoResponse() {
        }
        
        public modificar_Detalle_Documento_De_PagoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminar_Detalle_Documento_De_Pago", WrapperNamespace="http://detalledocpago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminar_Detalle_Documento_De_PagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public eliminar_Detalle_Documento_De_PagoRequest() {
        }
        
        public eliminar_Detalle_Documento_De_PagoRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminar_Detalle_Documento_De_PagoResponse", WrapperNamespace="http://detalledocpago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminar_Detalle_Documento_De_PagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminar_Detalle_Documento_De_PagoResponse() {
        }
        
        public eliminar_Detalle_Documento_De_PagoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/")]
    public partial class detalleDocumentoPagoDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private int cantidadField;
        
        private bool cantidadFieldSpecified;
        
        private int dddpIdField;
        
        private bool dddpIdFieldSpecified;
        
        private string descripcionField;
        
        private documentoPagoDto documentoPagoField;
        
        private int nroItemField;
        
        private bool nroItemFieldSpecified;
        
        private double precioUnitarioField;
        
        private bool precioUnitarioFieldSpecified;
        
        private productoDto productoField;
        
        private servicioDto servicioField;
        
        private double valorVentaField;
        
        private bool valorVentaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadSpecified {
            get {
                return this.cantidadFieldSpecified;
            }
            set {
                this.cantidadFieldSpecified = value;
                this.RaisePropertyChanged("cantidadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int dddpId {
            get {
                return this.dddpIdField;
            }
            set {
                this.dddpIdField = value;
                this.RaisePropertyChanged("dddpId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dddpIdSpecified {
            get {
                return this.dddpIdFieldSpecified;
            }
            set {
                this.dddpIdFieldSpecified = value;
                this.RaisePropertyChanged("dddpIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public documentoPagoDto documentoPago {
            get {
                return this.documentoPagoField;
            }
            set {
                this.documentoPagoField = value;
                this.RaisePropertyChanged("documentoPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int nroItem {
            get {
                return this.nroItemField;
            }
            set {
                this.nroItemField = value;
                this.RaisePropertyChanged("nroItem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nroItemSpecified {
            get {
                return this.nroItemFieldSpecified;
            }
            set {
                this.nroItemFieldSpecified = value;
                this.RaisePropertyChanged("nroItemSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double precioUnitario {
            get {
                return this.precioUnitarioField;
            }
            set {
                this.precioUnitarioField = value;
                this.RaisePropertyChanged("precioUnitario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precioUnitarioSpecified {
            get {
                return this.precioUnitarioFieldSpecified;
            }
            set {
                this.precioUnitarioFieldSpecified = value;
                this.RaisePropertyChanged("precioUnitarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public productoDto producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public servicioDto servicio {
            get {
                return this.servicioField;
            }
            set {
                this.servicioField = value;
                this.RaisePropertyChanged("servicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public double valorVenta {
            get {
                return this.valorVentaField;
            }
            set {
                this.valorVentaField = value;
                this.RaisePropertyChanged("valorVenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorVentaSpecified {
            get {
                return this.valorVentaFieldSpecified;
            }
            set {
                this.valorVentaFieldSpecified = value;
                this.RaisePropertyChanged("valorVentaSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/")]
    public partial class documentoPagoDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private int documentoPagoIdField;
        
        private bool documentoPagoIdFieldSpecified;
        
        private estadoDocumentoDePago estadoField;
        
        private bool estadoFieldSpecified;
        
        private date fechaEmisionField;
        
        private string fechaEmisionStringField;
        
        private double iGVTotalField;
        
        private bool iGVTotalFieldSpecified;
        
        private metodoDePagoDto metodoDePagoField;
        
        private string numeroField;
        
        private personaDto personaField;
        
        private string serieField;
        
        private double subtotalField;
        
        private bool subtotalFieldSpecified;
        
        private tipoDocumentoDePago tipoDocumentoField;
        
        private bool tipoDocumentoFieldSpecified;
        
        private double totalField;
        
        private bool totalFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int documentoPagoId {
            get {
                return this.documentoPagoIdField;
            }
            set {
                this.documentoPagoIdField = value;
                this.RaisePropertyChanged("documentoPagoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool documentoPagoIdSpecified {
            get {
                return this.documentoPagoIdFieldSpecified;
            }
            set {
                this.documentoPagoIdFieldSpecified = value;
                this.RaisePropertyChanged("documentoPagoIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public estadoDocumentoDePago estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public date fechaEmision {
            get {
                return this.fechaEmisionField;
            }
            set {
                this.fechaEmisionField = value;
                this.RaisePropertyChanged("fechaEmision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string fechaEmisionString {
            get {
                return this.fechaEmisionStringField;
            }
            set {
                this.fechaEmisionStringField = value;
                this.RaisePropertyChanged("fechaEmisionString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double IGVTotal {
            get {
                return this.iGVTotalField;
            }
            set {
                this.iGVTotalField = value;
                this.RaisePropertyChanged("IGVTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IGVTotalSpecified {
            get {
                return this.iGVTotalFieldSpecified;
            }
            set {
                this.iGVTotalFieldSpecified = value;
                this.RaisePropertyChanged("IGVTotalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public metodoDePagoDto metodoDePago {
            get {
                return this.metodoDePagoField;
            }
            set {
                this.metodoDePagoField = value;
                this.RaisePropertyChanged("metodoDePago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public personaDto persona {
            get {
                return this.personaField;
            }
            set {
                this.personaField = value;
                this.RaisePropertyChanged("persona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
                this.RaisePropertyChanged("serie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public double subtotal {
            get {
                return this.subtotalField;
            }
            set {
                this.subtotalField = value;
                this.RaisePropertyChanged("subtotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subtotalSpecified {
            get {
                return this.subtotalFieldSpecified;
            }
            set {
                this.subtotalFieldSpecified = value;
                this.RaisePropertyChanged("subtotalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public tipoDocumentoDePago tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoDocumentoSpecified {
            get {
                return this.tipoDocumentoFieldSpecified;
            }
            set {
                this.tipoDocumentoFieldSpecified = value;
                this.RaisePropertyChanged("tipoDocumentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public double total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalSpecified {
            get {
                return this.totalFieldSpecified;
            }
            set {
                this.totalFieldSpecified = value;
                this.RaisePropertyChanged("totalSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/")]
    public enum estadoDocumentoDePago {
        
        /// <remarks/>
        EMITIDO,
        
        /// <remarks/>
        PAGADO,
        
        /// <remarks/>
        ANULADO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/")]
    public partial class date : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/")]
    public partial class tipoServicioDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private string descripcionField;
        
        private string nombreField;
        
        private int tipoServicioIdField;
        
        private bool tipoServicioIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int tipoServicioId {
            get {
                return this.tipoServicioIdField;
            }
            set {
                this.tipoServicioIdField = value;
                this.RaisePropertyChanged("tipoServicioId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoServicioIdSpecified {
            get {
                return this.tipoServicioIdFieldSpecified;
            }
            set {
                this.tipoServicioIdFieldSpecified = value;
                this.RaisePropertyChanged("tipoServicioIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/")]
    public partial class servicioDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private double costoField;
        
        private bool costoFieldSpecified;
        
        private string descripcionField;
        
        private string estadoField;
        
        private date fechaCreacionField;
        
        private date fechaModificacionField;
        
        private string nombreField;
        
        private int servicioIdField;
        
        private bool servicioIdFieldSpecified;
        
        private tipoServicioDto tipoServicioField;
        
        private string usuarioCreadorField;
        
        private string usuarioModificadorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double costo {
            get {
                return this.costoField;
            }
            set {
                this.costoField = value;
                this.RaisePropertyChanged("costo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool costoSpecified {
            get {
                return this.costoFieldSpecified;
            }
            set {
                this.costoFieldSpecified = value;
                this.RaisePropertyChanged("costoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public date fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public date fechaModificacion {
            get {
                return this.fechaModificacionField;
            }
            set {
                this.fechaModificacionField = value;
                this.RaisePropertyChanged("fechaModificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int servicioId {
            get {
                return this.servicioIdField;
            }
            set {
                this.servicioIdField = value;
                this.RaisePropertyChanged("servicioId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool servicioIdSpecified {
            get {
                return this.servicioIdFieldSpecified;
            }
            set {
                this.servicioIdFieldSpecified = value;
                this.RaisePropertyChanged("servicioIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public tipoServicioDto tipoServicio {
            get {
                return this.tipoServicioField;
            }
            set {
                this.tipoServicioField = value;
                this.RaisePropertyChanged("tipoServicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string usuarioCreador {
            get {
                return this.usuarioCreadorField;
            }
            set {
                this.usuarioCreadorField = value;
                this.RaisePropertyChanged("usuarioCreador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string usuarioModificador {
            get {
                return this.usuarioModificadorField;
            }
            set {
                this.usuarioModificadorField = value;
                this.RaisePropertyChanged("usuarioModificador");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/")]
    public partial class tipoProductoDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private string descripcionField;
        
        private string nombreField;
        
        private int tipoProductoIdField;
        
        private bool tipoProductoIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int tipoProductoId {
            get {
                return this.tipoProductoIdField;
            }
            set {
                this.tipoProductoIdField = value;
                this.RaisePropertyChanged("tipoProductoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoProductoIdSpecified {
            get {
                return this.tipoProductoIdFieldSpecified;
            }
            set {
                this.tipoProductoIdFieldSpecified = value;
                this.RaisePropertyChanged("tipoProductoIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/")]
    public partial class productoDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private date fechaCreacionField;
        
        private date fechaModificacionField;
        
        private string nombreField;
        
        private double precioUnitarioField;
        
        private bool precioUnitarioFieldSpecified;
        
        private string presentacionField;
        
        private int productoIdField;
        
        private bool productoIdFieldSpecified;
        
        private int stockField;
        
        private bool stockFieldSpecified;
        
        private tipoProductoDto tipoProductoField;
        
        private string usuarioCreadorField;
        
        private string usuarioModificadorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public date fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public date fechaModificacion {
            get {
                return this.fechaModificacionField;
            }
            set {
                this.fechaModificacionField = value;
                this.RaisePropertyChanged("fechaModificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double precioUnitario {
            get {
                return this.precioUnitarioField;
            }
            set {
                this.precioUnitarioField = value;
                this.RaisePropertyChanged("precioUnitario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precioUnitarioSpecified {
            get {
                return this.precioUnitarioFieldSpecified;
            }
            set {
                this.precioUnitarioFieldSpecified = value;
                this.RaisePropertyChanged("precioUnitarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string presentacion {
            get {
                return this.presentacionField;
            }
            set {
                this.presentacionField = value;
                this.RaisePropertyChanged("presentacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int productoId {
            get {
                return this.productoIdField;
            }
            set {
                this.productoIdField = value;
                this.RaisePropertyChanged("productoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool productoIdSpecified {
            get {
                return this.productoIdFieldSpecified;
            }
            set {
                this.productoIdFieldSpecified = value;
                this.RaisePropertyChanged("productoIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
                this.RaisePropertyChanged("stock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stockSpecified {
            get {
                return this.stockFieldSpecified;
            }
            set {
                this.stockFieldSpecified = value;
                this.RaisePropertyChanged("stockSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public tipoProductoDto tipoProducto {
            get {
                return this.tipoProductoField;
            }
            set {
                this.tipoProductoField = value;
                this.RaisePropertyChanged("tipoProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string usuarioCreador {
            get {
                return this.usuarioCreadorField;
            }
            set {
                this.usuarioCreadorField = value;
                this.RaisePropertyChanged("usuarioCreador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string usuarioModificador {
            get {
                return this.usuarioModificadorField;
            }
            set {
                this.usuarioModificadorField = value;
                this.RaisePropertyChanged("usuarioModificador");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/")]
    public partial class usuarioDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private string correoField;
        
        private date fechaCreacionField;
        
        private date fechaModificacionField;
        
        private string passwordField;
        
        private string usernameField;
        
        private string usuarioCreadorField;
        
        private int usuarioIdField;
        
        private bool usuarioIdFieldSpecified;
        
        private string usuarioModificadorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public date fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public date fechaModificacion {
            get {
                return this.fechaModificacionField;
            }
            set {
                this.fechaModificacionField = value;
                this.RaisePropertyChanged("fechaModificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string usuarioCreador {
            get {
                return this.usuarioCreadorField;
            }
            set {
                this.usuarioCreadorField = value;
                this.RaisePropertyChanged("usuarioCreador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int usuarioId {
            get {
                return this.usuarioIdField;
            }
            set {
                this.usuarioIdField = value;
                this.RaisePropertyChanged("usuarioId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usuarioIdSpecified {
            get {
                return this.usuarioIdFieldSpecified;
            }
            set {
                this.usuarioIdFieldSpecified = value;
                this.RaisePropertyChanged("usuarioIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string usuarioModificador {
            get {
                return this.usuarioModificadorField;
            }
            set {
                this.usuarioModificadorField = value;
                this.RaisePropertyChanged("usuarioModificador");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/")]
    public partial class personaDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private string direccionField;
        
        private string nombreField;
        
        private int nroDocumentoField;
        
        private bool nroDocumentoFieldSpecified;
        
        private int personaIdField;
        
        private bool personaIdFieldSpecified;
        
        private int rucField;
        
        private bool rucFieldSpecified;
        
        private sexo sexoField;
        
        private bool sexoFieldSpecified;
        
        private string telefonoField;
        
        private string tipoDocumentoField;
        
        private usuarioDto usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int nroDocumento {
            get {
                return this.nroDocumentoField;
            }
            set {
                this.nroDocumentoField = value;
                this.RaisePropertyChanged("nroDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nroDocumentoSpecified {
            get {
                return this.nroDocumentoFieldSpecified;
            }
            set {
                this.nroDocumentoFieldSpecified = value;
                this.RaisePropertyChanged("nroDocumentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int personaId {
            get {
                return this.personaIdField;
            }
            set {
                this.personaIdField = value;
                this.RaisePropertyChanged("personaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool personaIdSpecified {
            get {
                return this.personaIdFieldSpecified;
            }
            set {
                this.personaIdFieldSpecified = value;
                this.RaisePropertyChanged("personaIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int ruc {
            get {
                return this.rucField;
            }
            set {
                this.rucField = value;
                this.RaisePropertyChanged("ruc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rucSpecified {
            get {
                return this.rucFieldSpecified;
            }
            set {
                this.rucFieldSpecified = value;
                this.RaisePropertyChanged("rucSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public sexo sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sexoSpecified {
            get {
                return this.sexoFieldSpecified;
            }
            set {
                this.sexoFieldSpecified = value;
                this.RaisePropertyChanged("sexoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public usuarioDto usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/")]
    public enum sexo {
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        O,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/")]
    public partial class metodoDePagoDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private int metodoDePagoIdField;
        
        private bool metodoDePagoIdFieldSpecified;
        
        private tipoMetodoPago nombreField;
        
        private bool nombreFieldSpecified;
        
        private string nombreStrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int metodoDePagoId {
            get {
                return this.metodoDePagoIdField;
            }
            set {
                this.metodoDePagoIdField = value;
                this.RaisePropertyChanged("metodoDePagoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool metodoDePagoIdSpecified {
            get {
                return this.metodoDePagoIdFieldSpecified;
            }
            set {
                this.metodoDePagoIdFieldSpecified = value;
                this.RaisePropertyChanged("metodoDePagoIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public tipoMetodoPago nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nombreSpecified {
            get {
                return this.nombreFieldSpecified;
            }
            set {
                this.nombreFieldSpecified = value;
                this.RaisePropertyChanged("nombreSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombreStr {
            get {
                return this.nombreStrField;
            }
            set {
                this.nombreStrField = value;
                this.RaisePropertyChanged("nombreStr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/")]
    public enum tipoMetodoPago {
        
        /// <remarks/>
        EFECTIVO,
        
        /// <remarks/>
        TRANSFERENCIA,
        
        /// <remarks/>
        YAPE,
        
        /// <remarks/>
        PLIN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/")]
    public enum tipoDocumentoDePago {
        
        /// <remarks/>
        BOLETA,
        
        /// <remarks/>
        FACTURA,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtener_por_id", WrapperNamespace="http://detalledocpago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtener_por_idRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtener_por_idRequest() {
        }
        
        public obtener_por_idRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtener_por_idResponse", WrapperNamespace="http://detalledocpago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtener_por_idResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPetBussiness.DetalleDocumentoDePagoClient.detalleDocumentoPagoDto @return;
        
        public obtener_por_idResponse() {
        }
        
        public obtener_por_idResponse(SoftPetBussiness.DetalleDocumentoDePagoClient.detalleDocumentoPagoDto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listar_todos", WrapperNamespace="http://detalledocpago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class listar_todosRequest {
        
        public listar_todosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listar_todosResponse", WrapperNamespace="http://detalledocpago.softpetws.pucp.edu.pe/", IsWrapped=true)]
    public partial class listar_todosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detalledocpago.softpetws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPetBussiness.DetalleDocumentoDePagoClient.detalleDocumentoPagoDto[] @return;
        
        public listar_todosResponse() {
        }
        
        public listar_todosResponse(SoftPetBussiness.DetalleDocumentoDePagoClient.detalleDocumentoPagoDto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DetallesDocumentoDePagoChannel : SoftPetBussiness.DetalleDocumentoDePagoClient.DetallesDocumentoDePago, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DetallesDocumentoDePagoClient : System.ServiceModel.ClientBase<SoftPetBussiness.DetalleDocumentoDePagoClient.DetallesDocumentoDePago>, SoftPetBussiness.DetalleDocumentoDePagoClient.DetallesDocumentoDePago {
        
        public DetallesDocumentoDePagoClient() {
        }
        
        public DetallesDocumentoDePagoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DetallesDocumentoDePagoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DetallesDocumentoDePagoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DetallesDocumentoDePagoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.DetalleDocumentoDePagoClient.insertar_Detalle_Documento_De_PagoResponse SoftPetBussiness.DetalleDocumentoDePagoClient.DetallesDocumentoDePago.insertar_Detalle_Documento_De_Pago(SoftPetBussiness.DetalleDocumentoDePagoClient.insertar_Detalle_Documento_De_PagoRequest request) {
            return base.Channel.insertar_Detalle_Documento_De_Pago(request);
        }
        
        public int insertar_Detalle_Documento_De_Pago(int documentoPagoId, int servicioId, int productoId, int nroItem, string descripcion, int cantidad, double precioUnitario, double valorVenta, bool activo) {
            SoftPetBussiness.DetalleDocumentoDePagoClient.insertar_Detalle_Documento_De_PagoRequest inValue = new SoftPetBussiness.DetalleDocumentoDePagoClient.insertar_Detalle_Documento_De_PagoRequest();
            inValue.documentoPagoId = documentoPagoId;
            inValue.servicioId = servicioId;
            inValue.productoId = productoId;
            inValue.nroItem = nroItem;
            inValue.descripcion = descripcion;
            inValue.cantidad = cantidad;
            inValue.precioUnitario = precioUnitario;
            inValue.valorVenta = valorVenta;
            inValue.activo = activo;
            SoftPetBussiness.DetalleDocumentoDePagoClient.insertar_Detalle_Documento_De_PagoResponse retVal = ((SoftPetBussiness.DetalleDocumentoDePagoClient.DetallesDocumentoDePago)(this)).insertar_Detalle_Documento_De_Pago(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.DetalleDocumentoDePagoClient.insertar_Detalle_Documento_De_PagoResponse> SoftPetBussiness.DetalleDocumentoDePagoClient.DetallesDocumentoDePago.insertar_Detalle_Documento_De_PagoAsync(SoftPetBussiness.DetalleDocumentoDePagoClient.insertar_Detalle_Documento_De_PagoRequest request) {
            return base.Channel.insertar_Detalle_Documento_De_PagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.DetalleDocumentoDePagoClient.insertar_Detalle_Documento_De_PagoResponse> insertar_Detalle_Documento_De_PagoAsync(int documentoPagoId, int servicioId, int productoId, int nroItem, string descripcion, int cantidad, double precioUnitario, double valorVenta, bool activo) {
            SoftPetBussiness.DetalleDocumentoDePagoClient.insertar_Detalle_Documento_De_PagoRequest inValue = new SoftPetBussiness.DetalleDocumentoDePagoClient.insertar_Detalle_Documento_De_PagoRequest();
            inValue.documentoPagoId = documentoPagoId;
            inValue.servicioId = servicioId;
            inValue.productoId = productoId;
            inValue.nroItem = nroItem;
            inValue.descripcion = descripcion;
            inValue.cantidad = cantidad;
            inValue.precioUnitario = precioUnitario;
            inValue.valorVenta = valorVenta;
            inValue.activo = activo;
            return ((SoftPetBussiness.DetalleDocumentoDePagoClient.DetallesDocumentoDePago)(this)).insertar_Detalle_Documento_De_PagoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.DetalleDocumentoDePagoClient.modificar_Detalle_Documento_De_PagoResponse SoftPetBussiness.DetalleDocumentoDePagoClient.DetallesDocumentoDePago.modificar_Detalle_Documento_De_Pago(SoftPetBussiness.DetalleDocumentoDePagoClient.modificar_Detalle_Documento_De_PagoRequest request) {
            return base.Channel.modificar_Detalle_Documento_De_Pago(request);
        }
        
        public int modificar_Detalle_Documento_De_Pago(int ddpId, int documentoPagoId, int servicioId, int productoId, int nroItem, string descripcion, int cantidad, double precioUnitario, double valorVenta, bool activo) {
            SoftPetBussiness.DetalleDocumentoDePagoClient.modificar_Detalle_Documento_De_PagoRequest inValue = new SoftPetBussiness.DetalleDocumentoDePagoClient.modificar_Detalle_Documento_De_PagoRequest();
            inValue.ddpId = ddpId;
            inValue.documentoPagoId = documentoPagoId;
            inValue.servicioId = servicioId;
            inValue.productoId = productoId;
            inValue.nroItem = nroItem;
            inValue.descripcion = descripcion;
            inValue.cantidad = cantidad;
            inValue.precioUnitario = precioUnitario;
            inValue.valorVenta = valorVenta;
            inValue.activo = activo;
            SoftPetBussiness.DetalleDocumentoDePagoClient.modificar_Detalle_Documento_De_PagoResponse retVal = ((SoftPetBussiness.DetalleDocumentoDePagoClient.DetallesDocumentoDePago)(this)).modificar_Detalle_Documento_De_Pago(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.DetalleDocumentoDePagoClient.modificar_Detalle_Documento_De_PagoResponse> SoftPetBussiness.DetalleDocumentoDePagoClient.DetallesDocumentoDePago.modificar_Detalle_Documento_De_PagoAsync(SoftPetBussiness.DetalleDocumentoDePagoClient.modificar_Detalle_Documento_De_PagoRequest request) {
            return base.Channel.modificar_Detalle_Documento_De_PagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.DetalleDocumentoDePagoClient.modificar_Detalle_Documento_De_PagoResponse> modificar_Detalle_Documento_De_PagoAsync(int ddpId, int documentoPagoId, int servicioId, int productoId, int nroItem, string descripcion, int cantidad, double precioUnitario, double valorVenta, bool activo) {
            SoftPetBussiness.DetalleDocumentoDePagoClient.modificar_Detalle_Documento_De_PagoRequest inValue = new SoftPetBussiness.DetalleDocumentoDePagoClient.modificar_Detalle_Documento_De_PagoRequest();
            inValue.ddpId = ddpId;
            inValue.documentoPagoId = documentoPagoId;
            inValue.servicioId = servicioId;
            inValue.productoId = productoId;
            inValue.nroItem = nroItem;
            inValue.descripcion = descripcion;
            inValue.cantidad = cantidad;
            inValue.precioUnitario = precioUnitario;
            inValue.valorVenta = valorVenta;
            inValue.activo = activo;
            return ((SoftPetBussiness.DetalleDocumentoDePagoClient.DetallesDocumentoDePago)(this)).modificar_Detalle_Documento_De_PagoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.DetalleDocumentoDePagoClient.eliminar_Detalle_Documento_De_PagoResponse SoftPetBussiness.DetalleDocumentoDePagoClient.DetallesDocumentoDePago.eliminar_Detalle_Documento_De_Pago(SoftPetBussiness.DetalleDocumentoDePagoClient.eliminar_Detalle_Documento_De_PagoRequest request) {
            return base.Channel.eliminar_Detalle_Documento_De_Pago(request);
        }
        
        public int eliminar_Detalle_Documento_De_Pago(int arg0) {
            SoftPetBussiness.DetalleDocumentoDePagoClient.eliminar_Detalle_Documento_De_PagoRequest inValue = new SoftPetBussiness.DetalleDocumentoDePagoClient.eliminar_Detalle_Documento_De_PagoRequest();
            inValue.arg0 = arg0;
            SoftPetBussiness.DetalleDocumentoDePagoClient.eliminar_Detalle_Documento_De_PagoResponse retVal = ((SoftPetBussiness.DetalleDocumentoDePagoClient.DetallesDocumentoDePago)(this)).eliminar_Detalle_Documento_De_Pago(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.DetalleDocumentoDePagoClient.eliminar_Detalle_Documento_De_PagoResponse> SoftPetBussiness.DetalleDocumentoDePagoClient.DetallesDocumentoDePago.eliminar_Detalle_Documento_De_PagoAsync(SoftPetBussiness.DetalleDocumentoDePagoClient.eliminar_Detalle_Documento_De_PagoRequest request) {
            return base.Channel.eliminar_Detalle_Documento_De_PagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.DetalleDocumentoDePagoClient.eliminar_Detalle_Documento_De_PagoResponse> eliminar_Detalle_Documento_De_PagoAsync(int arg0) {
            SoftPetBussiness.DetalleDocumentoDePagoClient.eliminar_Detalle_Documento_De_PagoRequest inValue = new SoftPetBussiness.DetalleDocumentoDePagoClient.eliminar_Detalle_Documento_De_PagoRequest();
            inValue.arg0 = arg0;
            return ((SoftPetBussiness.DetalleDocumentoDePagoClient.DetallesDocumentoDePago)(this)).eliminar_Detalle_Documento_De_PagoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.DetalleDocumentoDePagoClient.obtener_por_idResponse SoftPetBussiness.DetalleDocumentoDePagoClient.DetallesDocumentoDePago.obtener_por_id(SoftPetBussiness.DetalleDocumentoDePagoClient.obtener_por_idRequest request) {
            return base.Channel.obtener_por_id(request);
        }
        
        public SoftPetBussiness.DetalleDocumentoDePagoClient.detalleDocumentoPagoDto obtener_por_id(int id) {
            SoftPetBussiness.DetalleDocumentoDePagoClient.obtener_por_idRequest inValue = new SoftPetBussiness.DetalleDocumentoDePagoClient.obtener_por_idRequest();
            inValue.id = id;
            SoftPetBussiness.DetalleDocumentoDePagoClient.obtener_por_idResponse retVal = ((SoftPetBussiness.DetalleDocumentoDePagoClient.DetallesDocumentoDePago)(this)).obtener_por_id(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.DetalleDocumentoDePagoClient.obtener_por_idResponse> SoftPetBussiness.DetalleDocumentoDePagoClient.DetallesDocumentoDePago.obtener_por_idAsync(SoftPetBussiness.DetalleDocumentoDePagoClient.obtener_por_idRequest request) {
            return base.Channel.obtener_por_idAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.DetalleDocumentoDePagoClient.obtener_por_idResponse> obtener_por_idAsync(int id) {
            SoftPetBussiness.DetalleDocumentoDePagoClient.obtener_por_idRequest inValue = new SoftPetBussiness.DetalleDocumentoDePagoClient.obtener_por_idRequest();
            inValue.id = id;
            return ((SoftPetBussiness.DetalleDocumentoDePagoClient.DetallesDocumentoDePago)(this)).obtener_por_idAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPetBussiness.DetalleDocumentoDePagoClient.listar_todosResponse SoftPetBussiness.DetalleDocumentoDePagoClient.DetallesDocumentoDePago.listar_todos(SoftPetBussiness.DetalleDocumentoDePagoClient.listar_todosRequest request) {
            return base.Channel.listar_todos(request);
        }
        
        public SoftPetBussiness.DetalleDocumentoDePagoClient.detalleDocumentoPagoDto[] listar_todos() {
            SoftPetBussiness.DetalleDocumentoDePagoClient.listar_todosRequest inValue = new SoftPetBussiness.DetalleDocumentoDePagoClient.listar_todosRequest();
            SoftPetBussiness.DetalleDocumentoDePagoClient.listar_todosResponse retVal = ((SoftPetBussiness.DetalleDocumentoDePagoClient.DetallesDocumentoDePago)(this)).listar_todos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPetBussiness.DetalleDocumentoDePagoClient.listar_todosResponse> SoftPetBussiness.DetalleDocumentoDePagoClient.DetallesDocumentoDePago.listar_todosAsync(SoftPetBussiness.DetalleDocumentoDePagoClient.listar_todosRequest request) {
            return base.Channel.listar_todosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPetBussiness.DetalleDocumentoDePagoClient.listar_todosResponse> listar_todosAsync() {
            SoftPetBussiness.DetalleDocumentoDePagoClient.listar_todosRequest inValue = new SoftPetBussiness.DetalleDocumentoDePagoClient.listar_todosRequest();
            return ((SoftPetBussiness.DetalleDocumentoDePagoClient.DetallesDocumentoDePago)(this)).listar_todosAsync(inValue);
        }
    }
}
